/*
 * headless_dialog_verbs.c - Dialog processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains Phase 2A interactive dialog prompt implementations.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status (Phase 2A):
 * - dialog.ask(): COMPLETE - Yes/No prompt with arrow key selection
 * - dialog.getInt(): COMPLETE - Integer input with default
 * - dialog.getString() (via getuserinfo): COMPLETE - String input with default
 * - dialog.getPassword(): COMPLETE - Password input with dots
 *
 * See planning/phase3/HEADLESS_INTERACTIVE_MODE.md for complete roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Include interactive dialog prompt functions */
#include "../frontier-cli/dialog_prompts.h"
#include "../frontier-cli/cli_utils.h"

/* Token enum for all verbs in the dialog processor */
enum {
    diav_alert = 0,
    diav_run = 1,
    diav_runmodeless = 2,
    diav_runcard = 3,
    diav_runmodalcard = 4,
    diav_ismodalcard = 5,
    diav_setmodalcardtimeout = 6,
    diav_getvalue = 7,
    diav_setvalue = 8,
    diav_setitemenable = 9,
    diav_showitem = 10,
    diav_hideitem = 11,
    diav_twoway = 12,
    diav_threeway = 13,
    diav_ask = 14,
    diav_getint = 15,
    diav_notify = 16,
    diav_getuserinfo = 17,
    diav_getpassword = 18
};

static boolean dialog_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case diav_alert:
            /* Verb: dialog.alert - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_run:
            /* Verb: dialog.run - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_runmodeless:
            /* Verb: dialog.runmodeless - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_runcard:
            /* dialog.runcard - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't use modal dialog verbs because GUI is not available in headless mode"), bserror);
            return false;
        case diav_runmodalcard:
            /* Verb: dialog.runmodalcard - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_ismodalcard:
            /* dialog.ismodalcard - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't use modal dialog verbs because GUI is not available in headless mode"), bserror);
            return false;
        case diav_setmodalcardtimeout:
            /* dialog.setmodalcardtimeout - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't use modal dialog verbs because GUI is not available in headless mode"), bserror);
            return false;
        case diav_getvalue:
            /* Verb: dialog.getvalue - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_setvalue:
            /* Verb: dialog.setvalue - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_setitemenable:
            /* Verb: dialog.setitemenable - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_showitem:
            /* dialog.showitem - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't use modal dialog verbs because GUI is not available in headless mode"), bserror);
            return false;
        case diav_hideitem:
            /* dialog.hideitem - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't use modal dialog verbs because GUI is not available in headless mode"), bserror);
            return false;
        case diav_twoway:
            /* Verb: dialog.twoway - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_threeway:
            /* Verb: dialog.threeway - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_ask: {
            /* dialog.ask(prompt) - Yes/No prompt with arrow key selection */
            bigstring bsprompt;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            flnextparamislast = true;
            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            /* Convert Pascal string to C string */
            char prompt[256];
            copyptocstring(bsprompt, prompt);

            /* Call interactive prompt */
            boolean result = dialog_ask(prompt);

            return setbooleanvalue(result, vreturned);
        }
        case diav_getint: {
            /* dialog.getInt(prompt, [default]) - Integer input with optional default */
            bigstring bsprompt;
            long default_value = 0;  /* Default to 0 if not specified */

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            /* Check if second parameter (default) is provided */
            if (langgetparamcount(hparam1) >= 2) {
                flnextparamislast = true;
                if (!getlongvalue(hparam1, 2, &default_value))
                    return false;
            }
            /* else: No default provided, use 0 */

            /* Convert Pascal string to C string */
            char prompt[256];
            copyptocstring(bsprompt, prompt);

            /* Call interactive prompt */
            long result = dialog_get_int(prompt, default_value);

            return setlongvalue(result, vreturned);
        }
        case diav_notify:
            /* Verb: dialog.notify - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case diav_getuserinfo: {
            /* dialog.getuserinfo(prompt, [default]) - String input (legacy name for getString) */
            bigstring bsprompt, bsdefault;
            boolean has_default = false;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            /* Check if second parameter (default) is provided */
            if (langgetparamcount(hparam1) >= 2) {
                flnextparamislast = true;
                if (!getstringvalue(hparam1, 2, bsdefault))
                    return false;
                has_default = true;
            } else {
                /* No default - use empty string */
                setemptystring(bsdefault);
            }

            /* Convert Pascal strings to C strings */
            char prompt[256];
            char default_value[256];
            copyptocstring(bsprompt, prompt);
            copyptocstring(bsdefault, default_value);

            /* Call interactive prompt */
            char *result = dialog_get_string(prompt, default_value);
            if (!result) {
                if (bserror) copystring(BIGSTRING("\pUser cancelled string entry"), bserror);
                return false;
            }

            /* Convert to Frontier string and return */
            bigstring bsresult;
            copyctopstring(result, bsresult);
            free(result);

            return setstringvalue(bsresult, vreturned);
        }
        case diav_getpassword: {
            /* dialog.getPassword(prompt) - Password input with dots */
            bigstring bsprompt;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            flnextparamislast = true;
            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            /* Convert Pascal string to C string */
            char prompt[256];
            copyptocstring(bsprompt, prompt);

            /* Call interactive prompt */
            char *password = dialog_get_password(prompt);
            if (!password) {
                if (bserror) copystring(BIGSTRING("\pUser cancelled password entry"), bserror);
                return false;
            }

            /* Convert to Frontier string and return */
            bigstring bspassword;
            copyctopstring(password, bspassword);
            free(password);

            return setstringvalue(bspassword, vreturned);
        }
        default:
            return false;
    }
}

boolean dialoginitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pdialog"), bsname);

    if (!newfunctionprocessor(bsname, &dialog_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\palert"), diav_alert);
    ADD_VERB(BIGSTRING("\prun"), diav_run);
    ADD_VERB(BIGSTRING("\prunmodeless"), diav_runmodeless);
    ADD_VERB(BIGSTRING("\pruncard"), diav_runcard);
    ADD_VERB(BIGSTRING("\prunmodalcard"), diav_runmodalcard);
    ADD_VERB(BIGSTRING("\pismodalcard"), diav_ismodalcard);
    ADD_VERB(BIGSTRING("\psetmodalcardtimeout"), diav_setmodalcardtimeout);
    ADD_VERB(BIGSTRING("\pgetvalue"), diav_getvalue);
    ADD_VERB(BIGSTRING("\psetvalue"), diav_setvalue);
    ADD_VERB(BIGSTRING("\psetitemenable"), diav_setitemenable);
    ADD_VERB(BIGSTRING("\pshowitem"), diav_showitem);
    ADD_VERB(BIGSTRING("\phideitem"), diav_hideitem);
    ADD_VERB(BIGSTRING("\ptwoway"), diav_twoway);
    ADD_VERB(BIGSTRING("\pthreeway"), diav_threeway);
    ADD_VERB(BIGSTRING("\pask"), diav_ask);
    ADD_VERB(BIGSTRING("\pgetint"), diav_getint);
    ADD_VERB(BIGSTRING("\pnotify"), diav_notify);
    ADD_VERB(BIGSTRING("\pgetuserinfo"), diav_getuserinfo);
    ADD_VERB(BIGSTRING("\pgetpassword"), diav_getpassword);

    #undef ADD_VERB

    pophashtable();
    return true;
}
