/*
 * headless_rgb_verbs.c - Rgb processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains hand-written implementations for rgb verbs.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status:
 * - rgb.set (r, g, b) -> rgbvalue: COMPLETE
 * - rgb.get (rgbvalue, @r, @g, @b): COMPLETE
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the rgb processor */
enum {
    rgbv_get = 0,
    rgbv_set = 1
};

static boolean rgb_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;
    switch(token) {
        case rgbv_get: {
            /* rgb.get (rgbvalue, @red, @green, @blue) - Extract RGB components */
            RGBColor rgb;

            if (!langcheckparamcount(hparam1, 4))
                return false;

            /* Get the RGB value from first parameter */
            if (!getrgbvalue(hparam1, 1, &rgb))
                return false;

            /* Set the red component via address parameter */
            if (!setintvarparam(hparam1, 2, rgb.red))
                return false;

            /* Set the green component via address parameter */
            if (!setintvarparam(hparam1, 3, rgb.green))
                return false;

            /* Set the blue component via address parameter (last param) */
            flnextparamislast = true;
            if (!setintvarparam(hparam1, 4, rgb.blue))
                return false;

            /* Return true to indicate success */
            return setbooleanvalue(true, vreturned);
        }

        case rgbv_set: {
            /* rgb.set (red, green, blue) -> rgbvalue - Create RGB from components */
            RGBColor rgb;

            /* Get red component (0-65535) */
            if (!getintvalue(hparam1, 1, (short *) &rgb.red))
                return false;

            /* Get green component (0-65535) */
            if (!getintvalue(hparam1, 2, (short *) &rgb.green))
                return false;

            /* Get blue component (0-65535) - last parameter */
            flnextparamislast = true;
            if (!getintvalue(hparam1, 3, (short *) &rgb.blue))
                return false;

            /* Create and return RGB value */
            return newheapvalue(&rgb, longsizeof(rgb), rgbvaluetype, vreturned);
        }

        default:
            return false;
    }
}

boolean rgbinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\prgb"), bsname);

    if (!newfunctionprocessor(bsname, &rgb_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pget"), rgbv_get);
    ADD_VERB(BIGSTRING("\pset"), rgbv_set);

    #undef ADD_VERB

    pophashtable();
    return true;
}
