/*
 * headless_clock_verbs.c - Clock processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 *
 * 2025-12-15 Codex: Implemented clock.now, clock.ticks, clock.milliseconds
 * using portable time layer (frontier_time_*).
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "timedate.h"
#include "time_portable.h"

/* Token enum for all verbs in the clock processor */
enum {
    clov_now = 0,
    clov_set = 1,
    clov_sleepfor = 2,
    clov_ticks = 3,
    clov_milliseconds = 4,
    clov_waitseconds = 5,
    clov_waitsixtieths = 6
};

static boolean clock_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;  /* Suppress unused parameter warning for implemented verbs */

    switch(token) {
        case clov_now:
            /* Verb: clock.now - implemented using portable timenow() */
            if (!langcheckparamcount(hparam1, 0))
                return false;
            return setdatevalue(timenow(), vreturned);

        case clov_set:
            /* clock.set - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't set system time because it requires administrator privileges"), bserror);
            return false;

        case clov_sleepfor: {
            /* Verb: clock.sleepfor - headless implementation using portable sleep */
            long ctseconds;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 1, &ctseconds))
                return false;

            /* Validate non-negative duration */
            if (ctseconds < 0) {
                if (bserror) copystring(BIGSTRING("\pCan't sleep because negative duration is invalid"), bserror);
                return false;
            }

            /* Sleep for the specified number of seconds */
            if (ctseconds > 0)
                frontier_time_sleep_millis((uint32_t)(ctseconds * 1000));

            (*vreturned).data.flvalue = true;
            return true;
        }

        case clov_ticks:
            /* Verb: clock.ticks - implemented using portable gettickcount() */
            if (!langcheckparamcount(hparam1, 0))
                return false;
            return setlongvalue(gettickcount(), vreturned);

        case clov_milliseconds:
            /* Verb: clock.milliseconds - implemented using portable getmilliseconds() */
            if (!langcheckparamcount(hparam1, 0))
                return false;
            return setlongvalue(getmilliseconds(), vreturned);

        case clov_waitseconds: {
            /* Verb: clock.waitseconds - headless implementation using portable sleep */
            long ctseconds;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 1, &ctseconds))
                return false;

            /* Validate non-negative duration */
            if (ctseconds < 0) {
                if (bserror) copystring(BIGSTRING("\pCan't wait because negative duration is invalid"), bserror);
                return false;
            }

            /* Sleep for the specified number of seconds */
            if (ctseconds > 0)
                frontier_time_sleep_millis((uint32_t)(ctseconds * 1000));

            (*vreturned).data.flvalue = true;
            return true;
        }

        case clov_waitsixtieths: {
            /* Verb: clock.waitsixtieths - headless implementation using portable sleep */
            /* Sixtieths = 1/60th second, convert to milliseconds: ticks * 1000 / 60 ≈ ticks * 50 / 3 */
            long ctsixtieths;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 1, &ctsixtieths))
                return false;

            /* Convert 60ths of a second to milliseconds */
            if (ctsixtieths < 0) {
                if (bserror) copystring(BIGSTRING("\pCan't wait because negative duration is invalid"), bserror);
                return false;
            }

            if (ctsixtieths > 0) {
                /* Prevent overflow by casting to int64_t before multiplication */
                uint32_t millis = (uint32_t)(((int64_t)ctsixtieths * 1000) / 60);
                frontier_time_sleep_millis(millis);
            }

            (*vreturned).data.flvalue = true;
            return true;
        }

        default:
            return false;
    }
}

boolean clockinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pclock"), bsname);

    if (!newfunctionprocessor(bsname, &clock_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pnow"), clov_now);
    ADD_VERB(BIGSTRING("\pset"), clov_set);
    ADD_VERB(BIGSTRING("\psleepfor"), clov_sleepfor);
    ADD_VERB(BIGSTRING("\pticks"), clov_ticks);
    ADD_VERB(BIGSTRING("\pmilliseconds"), clov_milliseconds);
    ADD_VERB(BIGSTRING("\pwaitseconds"), clov_waitseconds);
    ADD_VERB(BIGSTRING("\pwaitsixtieths"), clov_waitsixtieths);

    #undef ADD_VERB

    pophashtable();
    return true;
}
