/*
 * headless_filemenu_verbs.c - Filemenu processor verbs for headless mode
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * but now contains real implementations for critical verbs.
 *
 * Implemented:
 *   - fileMenu.open(path, hidden=false) - Opens guest database, mounts into system.compiler.files
 *   - fileMenu.close() - Closes current target guest database
 *   - fileMenu.closeall() - Closes all guest databases
 *   - fileMenu.save([f]) - Saves system root or guest database
 *
 * Implemented (New / Save As / Save Copy):
 *   - fileMenu.new(path, hidden=false) - Creates new empty ODB database, opens and mounts it
 *   - fileMenu.saveAs(path) / fileMenu.saveCopy(path) - Saves copy of current target database
 *
 * Stub implementations (return "not implemented"):
 *   - fileMenu.revert, print, quit
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "db.h"
#include "file.h"
#include "logging.h"
#include "odbinternal.h"
#include "db_format.h"
#include "cancoon.h"
#include "ops.h"

/*
 * Safe null-termination for bigstring before passing to C string APIs.
 * bigstring is unsigned char[256]: byte 0 = length (0-255), bytes 1-255 = data.
 * If length is 255, nullterminate would write at s[256] (1 byte OOB).
 * This macro caps the length at 254 before null-terminating to stay in bounds,
 * which is acceptable for logging — paths over 254 chars are truncated.
 */
#define safenullterminate(s) do { \
    if (stringlength(s) > 254) setstringlength(s, 254); \
    nullterminate(s); \
} while (0)

/*
 * Log verb failures at error level only when NOT inside a UserTalk try block.
 * Inside a try block the script is expected to handle the error via tryError,
 * so C-level error logging is noise. langerrorlogenabled() returns false when
 * the interpreter has entered a try block (via disablelangerrorlog).
 */
#define log_verb_error(...) do { \
    if (langerrorlogenabled()) \
        log_error(__VA_ARGS__); \
    else \
        log_debug(__VA_ARGS__); \
} while (0)

/* tyodbrecord/hdlodbrecord defined in odbinternal.h (shared with dbverbs.c) */
extern hdlodbrecord hodblist;

/* From tablestructure.c - the system.compiler.files table */
extern hdlhashtable filewindowtable;

/* Token enum for all verbs in the filemenu processor */
enum {
    filv_new = 0,
    filv_open = 1,
    filv_close = 2,
    filv_closeall = 3,
    filv_save = 4,
    filv_savecopy = 5,
    filv_revert = 6,
    filv_print = 7,
    filv_quit = 8,
    filv_saveas = 9
};

/*
 * filemenu_save_systemroot - Save the system root database to disk
 *
 * Saves all dirty (modified) objects in the system root database (Frontier.root)
 * to disk. This is the headless equivalent of File > Save in the GUI.
 *
 * Thread Safety: Not thread-safe. Should only be called from the main thread
 * or with appropriate synchronization.
 *
 * Prerequisites:
 *   - Database must be open (databasedata != nil)
 *   - Root variable must exist (rootvariable != nil) for non-empty saves
 *
 * Side Effects:
 *   - Calls dbclose() to flush buffers to disk
 *   - Updates views[0] with new root table address
 *   - Database remains open and usable after save
 *
 * Note: Safe to call during normal operation. Do NOT call during v6->v7 migration
 * as the database state may be incomplete.
 *
 * Returns: true on success, false on failure (with error logged)
 */
static boolean filemenu_save_systemroot(void) {
    dbaddress root_adr;
    db_context ctx;

    log_debug(LOG_COMP_DB, "filemenu_save_systemroot: saving system root database");

    /* Check if we have a database open */
    if (databasedata == nil) {
        log_verb_error(LOG_COMP_DB, "filemenu_save_systemroot: no database open");
        return false;
    }

    /* Check if we have a root variable to save */
    if (rootvariable == nil) {
        log_debug(LOG_COMP_DB, "filemenu_save_systemroot: database is empty, nothing to save");
        return true;  /* Empty database is technically saved */
    }

    /* Save the root table using v7 format */
    {
        boolean repack_scope = false;
        db_format_mode mode = {true, false, false};  /* 64-bit, no adapter_repack, no drop_cancoon */
        db_format_mode_push(&mode);
        repack_scope = true;

        if (!tablesavesystemtable(rootvariable, &root_adr)) {
            if (repack_scope) {
                db_format_mode_pop();
            }
            log_verb_error(LOG_COMP_DB, "filemenu_save_systemroot: tablesavesystemtable failed");
            return false;
        }

        if (repack_scope) {
            db_format_mode_pop();
        }
    }

    /* Flush release stack */
    db_context_init(&ctx);
    dbflushreleasestack_context(&ctx);

    /* Update views[0] to point to the saved root table */
    dbsetview(cancoonview, root_adr);

    /* Flush to disk - required for changes to persist */
    if (!dbclose()) {
        log_verb_error(LOG_COMP_DB, "filemenu_save_systemroot: dbclose failed");
        langerrormessage(BIGSTRING("\x1d" "Can't save: disk flush failed"));
        return false;
    }

    log_debug(LOG_COMP_DB, "filemenu_save_systemroot: saved and flushed, views[0] = 0x%llx",
              (unsigned long long)root_adr);

    return true;
}

/*
 * filemenu_save_guestdb - Save a guest database by file path
 *
 * Looks up a guest database in the global hodblist by its file path and saves
 * all dirty objects to disk. Guest databases are any databases opened via
 * fileMenu.open() other than the system root.
 *
 * Thread Safety: Not thread-safe. Should only be called from the main thread.
 *
 * Parameters:
 *   hparam1 - Tree node containing the file path parameter (bigstring)
 *
 * Algorithm:
 *   1. Extract file path from parameter
 *   2. Search hodblist for matching database (O(n) linear search)
 *   3. If found, call odbSaveFile() to save
 *   4. If not found, return error
 *
 * Note: The linear search is acceptable since guest database lists are typically
 * small (< 10 databases in normal use).
 *
 * Returns: true on success, false on failure (with error message set)
 */
static boolean filemenu_save_guestdb(hdltreenode hparam1) {
    tyfilespec fs;
    hdlodbrecord hodb;
    bigstring bspath;

    /* Get the file path parameter */
    flnextparamislast = true;
    if (!getfilespecvalue(hparam1, 1, &fs)) {
        log_verb_error(LOG_COMP_DB, "filemenu_save_guestdb: failed to get file path parameter");
        return false;
    }

    filespectopath(&fs, bspath);
    safenullterminate(bspath);
    log_debug(LOG_COMP_DB, "filemenu_save_guestdb: looking for database at path=%s",
              stringbaseaddress(bspath));

    /* Search hodblist for the database (skip sentinel at hodblist itself) */
    if (hodblist == nil) {
        log_verb_error(LOG_COMP_DB, "filemenu_save_guestdb: hodblist not initialized");
        langerrormessage(BIGSTRING("\031db: no databases are open"));
        return false;
    }

    for (hodb = (**hodblist).hnext; hodb != nil && hodb != hodblist; hodb = (**hodb).hnext) {
        /* Defensive: skip nil or corrupted entries in the list */
        if (*hodb == nil) {
            log_warn(LOG_COMP_DB, "filemenu_save_guestdb: found nil entry in hodblist");
            continue;
        }
        if (equalfilespecs(&(**hodb).fs, &fs)) {
            /* Found it - check if read-only */
            if ((**hodb).flreadonly) {
                log_verb_error(LOG_COMP_DB, "filemenu_save_guestdb: database is read-only");
                langerrormessage(BIGSTRING("\041Can't save: database is read-only"));
                return false;
            }

            /* Save the database — guard globals since odbSaveFile calls
             * setcancoonglobals which overwrites currenthashtable et al. */
            {
                odb_context_guard guard;
                boolean fl;

                log_debug(LOG_COMP_DB, "filemenu_save_guestdb: saving database");
                odb_guard_enter(&guard);
                fl = odbSaveFile((**hodb).odb);
                odb_guard_exit(&guard);

                if (!fl) {
                    log_verb_error(LOG_COMP_DB, "filemenu_save_guestdb: odbSaveFile failed");
                    return false;
                }
            }

            log_debug(LOG_COMP_DB, "filemenu_save_guestdb: saved successfully");
            return true;
        }
    }

    /* Database not found in open list */
    log_verb_error(LOG_COMP_DB, "filemenu_save_guestdb: database not found in open list");
    lang2paramerror(dbnotopenederror, BIGSTRING("\x0dfileMenu.save"), bspath);
    return false;
}

/*
 * filemenu_open - Open a guest database and mount into system.compiler.files
 *
 * This is the headless equivalent of File > Open in the GUI. It:
 *   1. Opens the ODB file (openfile + odbopenfile)
 *   2. Adds to hodblist (for db.* verb access)
 *   3. Mounts the root table into system.compiler.files (for bracket syntax access)
 *
 * Parameters:
 *   hparam1 - Tree node: param 1 = file path, param 2 = hidden (optional, ignored)
 *
 * Returns: true on success, false on failure
 */
static boolean filemenu_open(hdltreenode hparam1, tyvaluerecord *vreturned) {
    tyodbrecord odbrec;
    hdlodbrecord hodb;
    bigstring bspath;
    boolean flhidden = false;
    short ctconsumed = 0;
    short ctpositional;
    tyvaluerecord vhidden;

    setbooleanvalue(false, vreturned);

    odbrec.fref = 0;
    odbrec.flreadonly = false;

    /* Get the file path (param 1) */
    if (!getfilespecvalue(hparam1, ++ctconsumed, &odbrec.fs)) {
        log_verb_error(LOG_COMP_DB, "filemenu_open: getfilespecvalue failed");
        return false;
    }

    /* Consume optional 'hidden' param — supports both positional and named styles:
     *   filemenu.open(f, true)         — positional
     *   filemenu.open(f, hidden:true)  — named
     */
    flnextparamislast = true;
    ctpositional = ctconsumed;
    setbooleanvalue(false, &vhidden);

    if (!getoptionalparamvalue(hparam1, &ctconsumed, &ctpositional, BIGSTRING("\x06" "hidden"), &vhidden))
        return false;

    flhidden = vhidden.data.flvalue;

    filespectopath(&odbrec.fs, bspath);
    safenullterminate(bspath);
    log_debug(LOG_COMP_DB, "filemenu_open: opening %s", stringbaseaddress(bspath));

    /* Check if already open in hodblist */
    if (hodblist != nil) {
        hdlodbrecord h;
        for (h = (**hodblist).hnext; h != nil; h = (**h).hnext) {
            if (equalfilespecs(&(**h).fs, &odbrec.fs)) {
                log_debug(LOG_COMP_DB, "filemenu_open: database already open");
                return setbooleanvalue(true, vreturned);
            }
        }
    }

    /* Open the OS file */
    if (!openfile(&odbrec.fs, &odbrec.fref, odbrec.flreadonly)) {
        log_verb_error(LOG_COMP_DB, "filemenu_open: openfile failed for %s", stringbaseaddress(bspath));
        langerrormessage(BIGSTRING("\x1f" "Can't open: file does not exist"));
        return false;
    }

    /* Open the ODB — use context guard to save/restore system root globals */
    {
        odb_context_guard guard;

        odb_guard_enter(&guard);

        if (!odbOpenFile(odbrec.fref, &odbrec.odb, odbrec.flreadonly)) {
            odb_guard_exit(&guard);
            log_verb_error(LOG_COMP_DB, "filemenu_open: odbOpenFile failed");
            closefile(odbrec.fref);
            langerrormessage(BIGSTRING("\x22" "Can't open: invalid database file"));
            return false;
        }

        odb_guard_exit(&guard);
    }

    log_debug(LOG_COMP_DB, "filemenu_open: odbOpenFile succeeded, odb=%p", odbrec.odb);

    /* Create handle for the odb record and add to hodblist */
    if (!newfilledhandle(&odbrec, sizeof(odbrec), (Handle *) &hodb)) {
        odb_context_guard guard;
        log_verb_error(LOG_COMP_DB, "filemenu_open: newfilledhandle failed");
        odb_guard_enter(&guard);
        odbCloseFile(odbrec.odb);
        odb_guard_exit(&guard);
        closefile(odbrec.fref);
        return false;
    }

    /* Add to hodblist after sentinel */
    if (hodblist == nil) {
        log_verb_error(LOG_COMP_DB, "filemenu_open: hodblist not initialized");
        odb_context_guard guard;
        odb_guard_enter(&guard);
        odbCloseFile(odbrec.odb);
        odb_guard_exit(&guard);
        closefile(odbrec.fref);
        disposehandle((Handle) hodb);
        return false;
    }

    if ((**hodblist).hnext == nil) {
        (**hodblist).hnext = hodb;
        (**hodb).hnext = nil;
    }
    else {
        listlink((hdllinkedlist) (**hodblist).hnext, (hdllinkedlist) hodb);
    }

    /* Mount into system.compiler.files for bracket syntax access */
    if (filewindowtable != nil) {
        Handle hrootvar = odbGetRootVariable(odbrec.odb);

        if (hrootvar == nil) {
            log_debug(LOG_COMP_DB, "filemenu_open: odbGetRootVariable returned nil for %s", stringbaseaddress(bspath));
        }

        if (hrootvar != nil) {
            tyvaluerecord val;

            setexternalvalue(hrootvar, &val);

            if (!hashtableassign(filewindowtable, bspath, val)) {
                log_warn(LOG_COMP_DB, "filemenu_open: failed to mount in system.compiler.files");
                /* Non-fatal: database is still open in hodblist */
            }
            else {
                log_debug(LOG_COMP_DB, "filemenu_open: mounted in system.compiler.files as '%s'",
                          stringbaseaddress(bspath));
            }
        }
    }

    return setbooleanvalue(true, vreturned);
}


/*
 * filemenu_close_guestdb - Close a specific guest database by its hodblist handle
 *
 * Closes the ODB file, removes from hodblist, and unmounts from system.compiler.files.
 *
 * Parameters:
 *   hodb - Handle to the odb record in hodblist
 *
 * Returns: true on success
 */
static boolean filemenu_close_guestdb(hdlodbrecord hodb) {
    bigstring bspath;

    filespectopath(&(**hodb).fs, bspath);
    safenullterminate(bspath);
    log_debug(LOG_COMP_DB, "filemenu_close_guestdb: closing %s", stringbaseaddress(bspath));

    /* Close the ODB file first — use context guard to protect system root globals */
    {
        odb_context_guard guard;

        odb_guard_enter(&guard);

        if (!odbCloseFile((**hodb).odb)) {
            odb_guard_exit(&guard);
            log_verb_error(LOG_COMP_DB, "filemenu_close_guestdb: odbCloseFile failed");
            return false;
        }

        odb_guard_exit(&guard);
    }

    /* Remove from system.compiler.files (after successful close) */
    if (filewindowtable != nil) {
        pushhashtable(filewindowtable);
        hashdelete(bspath, false, false);
        pophashtable();
    }

    /* Close the OS file */
    closefile((**hodb).fref);

    /* Unlink from hodblist and dispose */
    listunlink((hdllinkedlist) hodblist, (hdllinkedlist) hodb);
    disposehandle((Handle) hodb);

    return true;
}


/*
 * filemenu_close - Close the current target guest database
 *
 * In headless mode, operates on the current target (set via target.set).
 * If no target is set, or target is not a guest database root table, no-op.
 *
 * Returns: true on success (including no-op cases)
 */
static boolean filemenu_close(tyvaluerecord *vreturned) {
    hdlhashtable htargettable;
    bigstring bstargetname;
    hdlodbrecord hodb;

    setbooleanvalue(true, vreturned);

    /* Get current target */
    if (!langgettarget(&htargettable, bstargetname)) {
        log_debug(LOG_COMP_DB, "filemenu_close: no target set, no-op");
        return true;  /* No target set - nothing to close */
    }

    log_debug(LOG_COMP_DB, "filemenu_close: target='%s'", stringbaseaddress(bstargetname));

    /* Check if target is in system.compiler.files (i.e., it's a guest database) */
    if (filewindowtable == nil || htargettable != filewindowtable) {
        log_debug(LOG_COMP_DB, "filemenu_close: target is not a guest database, no-op");
        return true;
    }

    /* Target name is the file path - find it in hodblist */
    if (hodblist == nil)
        return true;

    for (hodb = (**hodblist).hnext; hodb != nil; hodb = (**hodb).hnext) {
        bigstring bsodbpath;
        filespectopath(&(**hodb).fs, bsodbpath);
        safenullterminate(bsodbpath);

        if (equalstrings(bstargetname, bsodbpath)) {
            return filemenu_close_guestdb(hodb) ? true : false;
        }
    }

    log_debug(LOG_COMP_DB, "filemenu_close: target not found in hodblist, no-op");
    return true;
}


/*
 * filemenu_closeall - Close all guest databases
 *
 * Walks hodblist and closes each guest database, removing them from
 * system.compiler.files as well.
 *
 * Returns: true on success
 */
static boolean filemenu_closeall(tyvaluerecord *vreturned) {
    hdlodbrecord hodb, hnext;

    setbooleanvalue(true, vreturned);

    if (hodblist == nil)
        return true;

    log_debug(LOG_COMP_DB, "filemenu_closeall: closing all guest databases");

    /* Walk the list, closing each database */
    hodb = (**hodblist).hnext;

    while (hodb != nil) {
        hnext = (**hodb).hnext;  /* Save next before we dispose current */

        if (!filemenu_close_guestdb(hodb)) {
            /* Not gated on try-block state: closeall continues and returns true,
             * so this warning is the only runtime signal of a close failure. */
            log_warn(LOG_COMP_DB, "filemenu_closeall: failed to close a database");
            /* Continue closing others */
        }

        hodb = hnext;
    }

    log_debug(LOG_COMP_DB, "filemenu_closeall: done");
    return true;
}


/*
 * filemenu_saveas - Save a copy of the current target database to a new file
 *
 * This is the headless equivalent of File > Save As / Save A Copy.
 * Both fileMenu.saveAs(path) and fileMenu.saveCopy(path) call this function.
 *
 * Precondition: The database being copied must already be open.
 *
 * Implementation: Save-then-copy approach.
 *   1. Save the source database to flush all dirty data to disk
 *   2. Copy the on-disk file to the destination path
 *
 * This avoids the dbstartsaveas/dbendsaveas machinery which modifies in-memory
 * data structures (address pointers) during save, corrupting the source for
 * subsequent use. The file copy approach gives a perfect, consistent copy
 * while leaving the source completely untouched.
 *
 * Parameters:
 *   hparam1 - Tree node: param 1 = destination file path (required)
 *   vreturned - Return value (boolean)
 *
 * Returns: true on success
 */
static boolean filemenu_saveas(hdltreenode hparam1, tyvaluerecord *vreturned) {

    tyfilespec fsdest, fssource;
    bigstring bsdest;
    boolean fl = false;
    short ctparams;

    /* Validate param count: exactly 1 */
    ctparams = langgetparamcount(hparam1);

    if (ctparams != 1) {
        langerrormessage(BIGSTRING("\x33" "fileMenu.saveAs requires exactly 1 parameter (path)"));
        return false;
    }

    /* Get destination file path */
    flnextparamislast = true;

    if (!getfilespecvalue(hparam1, 1, &fsdest))
        return false;

    filespectopath(&fsdest, bsdest);
    safenullterminate(bsdest);
    log_debug(LOG_COMP_DB, "filemenu_saveas: destination=%s", stringbaseaddress(bsdest));

    /* Determine source database: check current target */
    {
        hdlhashtable htargettable;
        bigstring bstargetname;
        boolean fl_is_guest = false;
        hdlodbrecord hodb_source = nil;

        if (langgettarget(&htargettable, bstargetname) &&
            filewindowtable != nil &&
            htargettable == filewindowtable) {

            /* Target is in system.compiler.files → guest database */
            log_debug(LOG_COMP_DB, "filemenu_saveas: target is guest db '%s'", stringbaseaddress(bstargetname));

            /* Find the guest DB in hodblist */
            if (hodblist == nil) {
                langerrormessage(BIGSTRING("\x1d" "Can't save: no databases open"));
                return false;
            }

            for (hodb_source = (**hodblist).hnext; hodb_source != nil; hodb_source = (**hodb_source).hnext) {
                bigstring bsodbpath;
                filespectopath(&(**hodb_source).fs, bsodbpath);

                if (equalstrings(bstargetname, bsodbpath)) {
                    fl_is_guest = true;
                    break;
                }
            }

            if (!fl_is_guest) {
                langerrormessage(BIGSTRING("\x25" "Can't save: target database not found"));
                return false;
            }
        }

        if (fl_is_guest) {
            /* Guest database: save it first, then copy the file.
             * Use odb_guard to protect system root globals since odbSaveFile
             * sets cancoonglobals to the guest's cancoon. */
            {
                odb_context_guard guard;

                odb_guard_enter(&guard);
                fl = odbSaveFile((**hodb_source).odb);
                odb_guard_exit(&guard);

                if (!fl) {
                    log_verb_error(LOG_COMP_DB, "filemenu_saveas: failed to save guest db before copy");
                    return false;
                }
            }

            /* Get source file path from the odb record */
            fssource = (**hodb_source).fs;
        } else {
            /* System root: save it first, then copy the file */
            if (!filemenu_save_systemroot()) {
                log_verb_error(LOG_COMP_DB, "filemenu_saveas: failed to save system root before copy");
                return false;
            }

            /* Get source file path from the database file number */
            if (databasedata == nil) {
                langerrormessage(BIGSTRING("\x1c" "Can't save: no database open"));
                return false;
            }

            {
                const char *srcpath = headless_fnum_path((hdlfilenum) (**databasedata).fnumdatabase);
                bigstring bssrcpath;

                if (srcpath == nil) {
                    log_verb_error(LOG_COMP_DB, "filemenu_saveas: can't resolve system root file path");
                    langerrormessage(BIGSTRING("\x27" "Can't save: can't find source file path"));
                    return false;
                }

                /* Convert C string to bigstring, then to filespec */
                copyctopstring(srcpath, bssrcpath);
                pathtofilespec(bssrcpath, &fssource);
            }
        }
    }

    /* Copy the source file to the destination.
     * We do a simple byte-for-byte copy at the OS level. This gives a perfect,
     * consistent copy without modifying any in-memory state. */
    {
        bigstring bssource;
        FILE *fin, *fout;
        char buf[8192];
        size_t n;

        filespectopath(&fssource, bssource);

        /* Use safenullterminate to get C strings from Pascal strings */
        safenullterminate(bssource);
        safenullterminate(bsdest);

        fin = fopen(stringbaseaddress(bssource), "rb");

        if (fin == NULL) {
            log_verb_error(LOG_COMP_DB, "filemenu_saveas: can't open source %s", stringbaseaddress(bssource));
            langerrormessage(BIGSTRING("\x22" "Can't save: can't read source file"));
            return false;
        }

        fout = fopen(stringbaseaddress(bsdest), "wb");

        if (fout == NULL) {
            fclose(fin);
            log_verb_error(LOG_COMP_DB, "filemenu_saveas: can't create destination %s", stringbaseaddress(bsdest));
            langerrormessage(BIGSTRING("\x21" "Can't save: can't create new file"));
            return false;
        }

        while ((n = fread(buf, 1, sizeof(buf), fin)) > 0) {
            if (fwrite(buf, 1, n, fout) != n) {
                fclose(fin);
                fclose(fout);
                remove(stringbaseaddress(bsdest));
                log_verb_error(LOG_COMP_DB, "filemenu_saveas: write error");
                langerrormessage(BIGSTRING("\x1c" "Can't save: file write error"));
                return false;
            }
        }

        if (ferror(fin)) {
            fclose(fin);
            fclose(fout);
            remove(stringbaseaddress(bsdest));
            log_verb_error(LOG_COMP_DB, "filemenu_saveas: read error");
            langerrormessage(BIGSTRING("\x1b" "Can't save: file read error"));
            return false;
        }

        fclose(fin);
        fclose(fout);
    }

    log_debug(LOG_COMP_DB, "filemenu_saveas: successfully copied to %s", stringbaseaddress(bsdest));

    return setbooleanvalue(true, vreturned);
}


/*
 * filemenu_new - Create a new empty ODB database and open it
 *
 * This is the headless equivalent of File > New in the GUI. It:
 *   1. Validates the file does not already exist (won't overwrite)
 *   2. Creates a new file with opennewfile
 *   3. Initializes ODB structure with odbNewFile
 *   4. Closes the file
 *   5. Reopens and mounts via filemenu_open
 *
 * Parameters:
 *   hparam1 - Tree node: param 1 = file path (required), param 2 = hidden (optional, ignored)
 *   vreturned - Return value (boolean)
 *
 * Returns: true on success, false on failure
 */
static boolean filemenu_new(hdltreenode hparam1, tyvaluerecord *vreturned) {
    tyfilespec fs;
    hdlfilenum fnum;
    bigstring bspath;
    boolean flhidden = false;
    short ctconsumed = 0;
    short ctpositional;
    tyvaluerecord vhidden;

    setbooleanvalue(false, vreturned);

    /* Get the file path (param 1) */
    if (!getfilespecvalue(hparam1, ++ctconsumed, &fs)) {
        log_verb_error(LOG_COMP_DB, "filemenu_new: getfilespecvalue failed");
        return false;
    }

    /* Consume optional 'hidden' param — supports both positional and named styles:
     *   filemenu.new(f, true)         — positional
     *   filemenu.new(f, hidden:true)  — named
     */
    flnextparamislast = true;
    ctpositional = ctconsumed;
    setbooleanvalue(false, &vhidden);

    if (!getoptionalparamvalue(hparam1, &ctconsumed, &ctpositional, BIGSTRING("\x06" "hidden"), &vhidden))
        return false;

    flhidden = vhidden.data.flvalue;

    filespectopath(&fs, bspath);
    safenullterminate(bspath);
    log_debug(LOG_COMP_DB, "filemenu_new: creating new database at %s", stringbaseaddress(bspath));

    /* Check if file already exists - don't overwrite.
     * fileexists() returns true if the file exists, false otherwise.
     * The second parameter receives the is-folder flag, not existence. */
    {
        boolean flfolder = false;
        if (fileexists(&fs, &flfolder)) {
            log_verb_error(LOG_COMP_DB, "filemenu_new: file already exists at %s", stringbaseaddress(bspath));
            langerrormessage(BIGSTRING("\x27" "Can't create: file already exists at path"));
            return false;
        }
    }

    /* Create the new file */
    if (!opennewfile(&fs, 'LAND', 'ROOT', &fnum)) {
        log_verb_error(LOG_COMP_DB, "filemenu_new: opennewfile failed for %s", stringbaseaddress(bspath));
        langerrormessage(BIGSTRING("\x24" "Can't create: failed to create new file"));
        return false;
    }

    /* Initialize the ODB structure — guard globals since odbNewFile touches database state */
    {
        odb_context_guard guard;
        boolean fl;

        odb_guard_enter(&guard);
        fl = odbNewFile(fnum);
        odb_guard_exit(&guard);

        if (!fl) {
            log_verb_error(LOG_COMP_DB, "filemenu_new: odbNewFile failed");
            closefile(fnum);
            langerrormessage(BIGSTRING("\x29" "Can't create: failed to initialize database"));
            return false;
        }
    }

    /* Close the OS file — odbNewFile closed the DB internals but not the file handle */
    closefile(fnum);

    log_debug(LOG_COMP_DB, "filemenu_new: created and initialized, now opening via filemenu_open");

    /* Reopen and mount via filemenu_open. We use a create-close-reopen pattern because
     * odbNewFile() closes the database internally (it's designed for minimal creation),
     * so we must reopen it through the normal open path which handles hodblist insertion
     * and system.compiler.files mounting. */
    if (!filemenu_open(hparam1, vreturned)) {
        log_warn(LOG_COMP_DB, "filemenu_new: filemenu_open failed after creation, cleaning up orphaned file");
        deletefile(&fs);
        return false;
    }

    return true;
}


static boolean filemenu_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;
    switch(token) {
        case filv_new:
            return filemenu_new(hparam1, vreturned);

        case filv_open:
            return filemenu_open(hparam1, vreturned);

        case filv_close:
            return filemenu_close(vreturned);

        case filv_closeall:
            return filemenu_closeall(vreturned);

        case filv_save:
            /*
             * fileMenu.save([f])
             *
             * If called with no params: saves the system root database
             * If called with a path: saves the guest database at that path
             *
             * Returns: true on success
             */
            {
                boolean fl;
                short ctparams = langgetparamcount(hparam1);

                if (ctparams > 1) {
                    langerrormessage(BIGSTRING("\x2c" "fileMenu.save requires 0 or 1 parameters (path)"));
                    return false;
                }

                /* Check if we have parameters */
                if (ctparams == 0) {
                    /* No params - save system root */
                    fl = filemenu_save_systemroot();
                } else {
                    /* Path param - save guest database */
                    fl = filemenu_save_guestdb(hparam1);
                }

                if (!fl) {
                    return false;
                }

                return setbooleanvalue(true, vreturned);
            }

        case filv_savecopy:
            return filemenu_saveas(hparam1, vreturned);
        case filv_revert:
            /* Verb #6: filemenu.revert - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_print:
            /* Verb #7: filemenu.print - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_quit:
            /* Verb #8: filemenu.quit - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_saveas:
            return filemenu_saveas(hparam1, vreturned);
        default:
            return false;
    }
}

boolean filemenuinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\010filemenu"), bsname);

    if (!newfunctionprocessor(bsname, &filemenu_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\003new"), filv_new);
    ADD_VERB(BIGSTRING("\004open"), filv_open);
    ADD_VERB(BIGSTRING("\005close"), filv_close);
    ADD_VERB(BIGSTRING("\010closeall"), filv_closeall);
    ADD_VERB(BIGSTRING("\004save"), filv_save);
    ADD_VERB(BIGSTRING("\010savecopy"), filv_savecopy);
    ADD_VERB(BIGSTRING("\006revert"), filv_revert);
    ADD_VERB(BIGSTRING("\005print"), filv_print);
    ADD_VERB(BIGSTRING("\004quit"), filv_quit);
    ADD_VERB(BIGSTRING("\006saveas"), filv_saveas);

    #undef ADD_VERB

    pophashtable();
    return true;
}
