/*
 * headless_math_verbs.c - Math processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"
#include <stdlib.h>

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the math processor */
enum {
    matv_min = 0,
    matv_max = 1,
    matv_sqrt = 2,
    matv_random = 3
};

static boolean math_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case matv_min:
            /* Verb #0: math.min - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case matv_max:
            /* Verb #1: math.max - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case matv_sqrt:
            /* Verb #2: math.sqrt - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case matv_random: {
            long lower, upper;

            if (!getlongvalue(hparam1, 1, &lower))
                return false;

            flnextparamislast = true;
            if (!getlongvalue(hparam1, 2, &upper))
                return false;

            if (lower > upper) {
                if (bserror)
                    copystring(PSTRING("\014", "bounds error"), bserror);
                return false;
            }

            long n = rand();
            n = lower + (labs(n) % (upper - lower + 1));
            return setlongvalue(n, vreturned);
        }
        default:
            return false;
    }
}

boolean mathinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\004", "math"), bsname);

    if (!newfunctionprocessor(bsname, &math_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\003", "min"), matv_min);
    ADD_VERB(PSTRING("\003", "max"), matv_max);
    ADD_VERB(PSTRING("\004", "sqrt"), matv_sqrt);
    ADD_VERB(PSTRING("\006", "random"), matv_random);

    #undef ADD_VERB

    pophashtable();
    return true;
}
