/*
 * headless_inetd_verbs.c - Inetd processor verbs
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now wires up to the real kernel implementation for headless mode.
 *
 * The inetd.supervisor verb is the entry point for the kernelized webserver.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "langhtml.h"

/* Token enum for all verbs in the inetd processor */
enum {
    inev_supervisor = 0
};

static boolean inetd_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
#pragma unused(bserror)
    switch(token) {
        case inev_supervisor: {
            /*
             * Verb #0: inetd.supervisor - Entry point for kernelized webserver.
             * Parameters: stream (long), refcon (long)
             * Calls the real kernel implementation from langhtml.c.
             */
            long stream, refcon;

            if (!getlongvalue(hparam1, 1, &stream))
                return false;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 2, &refcon))
                return false;

            return inetdsupervisor(stream, refcon, vreturned);
        }
        default:
            return false;
    }
}

boolean inetdinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pinetd"), bsname);

    if (!newfunctionprocessor(bsname, &inetd_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\psupervisor"), inev_supervisor);

    #undef ADD_VERB

    pophashtable();
    return true;
}
