/*
 * headless_frontier_verbs.c - Frontier processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "process.h"  /* for hdlprocessthread */

#include <unistd.h>  /* for getcwd */
#include <string.h>  /* for strlen */

#ifdef __APPLE__
#include <mach-o/dyld.h>  /* for _NSGetExecutablePath */
#endif

/* Token enum for all verbs in the frontier processor */
enum {
    frov_getprogrampath = 0,
    frov_getfilepath = 1,
    frov_enableagents = 2,
    frov_requesttofront = 3,
    frov_isruntime = 4,
    frov_countthreads = 5,
    frov_ispowerpc = 6,
    frov_reclaimmemory = 7,
    frov_version = 8,
    frov_hashstats = 9,
    frov_gethashloopcount = 10,
    frov_hideapplication = 11,
    frov_isvalidserialnumber = 12,
    frov_showapplication = 13
};

static boolean frontier_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void) hparam1;
    (void) vreturned;

    switch(token) {
        case frov_getprogrampath: {
            /* Verb #0: frontier.getprogrampath - returns path to CLI executable */
            char path[1024];
            bigstring bspath;

            if (!langcheckparamcount(hparam1, 0))
                return false;

#ifdef __APPLE__
            uint32_t size = sizeof(path);
            if (_NSGetExecutablePath(path, &size) != 0) {
                if (bserror) copystring(BIGSTRING("\pcould not get program path"), bserror);
                return false;
            }
#else
            /* Linux: read /proc/self/exe symlink */
            ssize_t len = readlink("/proc/self/exe", path, sizeof(path) - 1);
            if (len == -1) {
                if (bserror) copystring(BIGSTRING("\pcould not get program path"), bserror);
                return false;
            }
            path[len] = '\0';
#endif

            copyctopstring(path, bspath);
            return setstringvalue(bspath, vreturned);
        }
        case frov_getfilepath: {
            /* Verb #1: frontier.getfilepath - returns path to current database file */
            /* In headless mode, return the system root path if loaded */
            /* IMPORTANT: Return an absolute path so startup scripts work correctly */
            extern boolean cli_is_system_root_loaded(void);
            extern const char* cli_get_system_root_path(void);
            const char *root_path;
            bigstring bspath;
            char fullpath[4096];
            int len;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            root_path = cli_get_system_root_path();
            if (!cli_is_system_root_loaded() || root_path[0] == '\0') {
                if (bserror) copystring(BIGSTRING("\pno database file loaded"), bserror);
                return false;
            }

            /* Convert relative path to absolute if needed */
            if (root_path[0] != '/') {
                char cwd[4096];
                if (getcwd(cwd, sizeof(cwd)) == NULL) {
                    if (bserror) copystring(BIGSTRING("\pcould not get current directory"), bserror);
                    return false;
                }
                len = snprintf(fullpath, sizeof(fullpath), "%s/%s", cwd, root_path);
                if (len < 0 || len >= (int)sizeof(fullpath)) {
                    if (bserror) copystring(BIGSTRING("\ppath too long"), bserror);
                    return false;
                }
            } else {
                len = snprintf(fullpath, sizeof(fullpath), "%s", root_path);
                if (len < 0 || len >= (int)sizeof(fullpath)) {
                    if (bserror) copystring(BIGSTRING("\ppath too long"), bserror);
                    return false;
                }
            }

            copyctopstring(fullpath, bspath);
            return setstringvalue(bspath, vreturned);
        }
        case frov_enableagents:
            /* frontier.enableAgents - no-op in headless mode (agents not supported) */
            /* Startup script calls this, so we return true to not fail the script */
            setbooleanvalue(true, vreturned);
            return true;
        case frov_requesttofront:
            /* Verb #3: frontier.requesttofront - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_isruntime:
            /* Verb #4: frontier.isruntime - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_countthreads:
            /* Verb #5: frontier.countthreads - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_ispowerpc:
            /* Verb #6: frontier.ispowerpc - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_reclaimmemory:
            /* Verb #7: frontier.reclaimmemory - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_version:
            /* Verb #8: frontier.version - Return version string */
            /* In headless mode, return a version that satisfies version checks */
            /* Using 10.0 to be greater than any historical Frontier version */
            if (!langcheckparamcount(hparam1, 0))
                return false;
            return setstringvalue(BIGSTRING("\x04" "10.0"), vreturned);
        case frov_hashstats:
            /* Verb #9: frontier.hashstats - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_gethashloopcount:
            /* Verb #10: frontier.gethashloopcount - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_hideapplication:
            /* Verb #11: frontier.hideapplication - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case frov_isvalidserialnumber: {
            /* frontier.isvalidSerialNumber - in headless mode, always return true.
             * Trial/licensing is not meaningful for CLI usage. */
            bigstring bsserial;

            flnextparamislast = true;

            /* Consume the serial number parameter */
            if (!getstringvalue(hparam1, 1, bsserial))
                return false;

            /* Always valid in headless mode */
            setbooleanvalue(true, vreturned);
            return true;
        }
        case frov_showapplication:
            /* Verb #13: frontier.showapplication - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        default:
            return false;
    }
}

/*
 * frontierversion - Direct C function called by langhtml.c for webserver headers
 * Returns the Frontier version as a string value.
 * This is NOT a verb - it's called directly from webservergetserverstring().
 */
boolean frontierversion(tyvaluerecord *v) {
    return setstringvalue(BIGSTRING("\x04" "10.0"), v);
}

/*
 * sysos - Direct C function called by langhtml.c for webserver headers
 * Returns the OS name as a string value.
 * Must match sys.os() verb which returns "MacOS" on Mac.
 */
boolean sysos(tyvaluerecord *v) {
    #ifdef __APPLE__
    return setstringvalue(BIGSTRING("\x05" "MacOS"), v);
    #else
    return setstringvalue(BIGSTRING("\x05" "Linux"), v);
    #endif
}

boolean frontierinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pfrontier"), bsname);

    if (!newfunctionprocessor(bsname, &frontier_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pgetprogrampath"), frov_getprogrampath);
    ADD_VERB(BIGSTRING("\pgetfilepath"), frov_getfilepath);
    ADD_VERB(BIGSTRING("\penableagents"), frov_enableagents);
    ADD_VERB(BIGSTRING("\prequesttofront"), frov_requesttofront);
    ADD_VERB(BIGSTRING("\pisruntime"), frov_isruntime);
    ADD_VERB(BIGSTRING("\pcountthreads"), frov_countthreads);
    ADD_VERB(BIGSTRING("\pispowerpc"), frov_ispowerpc);
    ADD_VERB(BIGSTRING("\preclaimmemory"), frov_reclaimmemory);
    ADD_VERB(BIGSTRING("\pversion"), frov_version);
    ADD_VERB(BIGSTRING("\phashstats"), frov_hashstats);
    ADD_VERB(BIGSTRING("\pgethashloopcount"), frov_gethashloopcount);
    ADD_VERB(BIGSTRING("\phideapplication"), frov_hideapplication);
    ADD_VERB(BIGSTRING("\pisvalidserialnumber"), frov_isvalidserialnumber);
    ADD_VERB(BIGSTRING("\pshowapplication"), frov_showapplication);

    #undef ADD_VERB

    pophashtable();
    return true;
}

/* Exported callback used by headless kernel verb bootstrap */
boolean headless_frontier_verbs_callback(short token, hdltreenode hparam1,
                                         tyvaluerecord *vreturned, bigstring bserror) {
    return frontier_valueproc(token, hparam1, vreturned, bserror);
}

/*
 * ingoodthread - Direct C function called by langhtml.c and other code
 * Checks if the current thread is still valid (not killed).
 * In headless mode, we always return true since we don't have
 * the full cooperative threading infrastructure.
 */
boolean ingoodthread(void) {
    return true;
}

/*
 * processisoneshot - Check if current process is a one-shot (vs agent)
 * Called during script execution to determine process type.
 * In headless mode, we return true (one-shot) - scripts run once and exit.
 */
boolean processisoneshot(boolean flnilok) {
    (void)flnilok;
    return true;  /* headless scripts are one-shot */
}

/*
 * processissleeping - Check if a process thread is sleeping
 * In headless mode, threads don't sleep in the cooperative sense.
 */
boolean processissleeping(hdlprocessthread hthread) {
    (void)hthread;
    return false;  /* not sleeping */
}

/*
 * processthreadcount - Return number of process threads
 * In headless mode, we have a single main thread.
 */
short processthreadcount(void) {
    return 1;
}

/*
 * langdialogrunning - Check if a dialog is running
 * In headless mode, no dialogs can run.
 */
boolean langdialogrunning(void) {
    return false;
}
