/*
 * headless_sys_verbs.c - Sys processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains production implementations for all 17 sys verbs.
 *
 * DO NOT regenerate - this file contains hand-written production code.
 *
 * Implementation status:
 * - System info verbs (4): sys.osversion, sys.machine, sys.os, sys.memavail - COMPLETE
 * - Process mgmt verbs (4): sys.systemtask, sys.countapps, sys.appisrunning, sys.getapppath - COMPLETE
 * - Environment verbs (2): sys.getenvironmentvariable, sys.setenvironmentvariable - COMPLETE
 * - Shell verbs (2): sys.unixshellcommand, sys.winshellcommand - COMPLETE
 * - URL verbs (1): sys.openUrl - COMPLETE
 * - GUI-only verbs (3): sys.frontmostapp, sys.bringapptofront, sys.browsenetwork - COMPLETE (stubs)
 * - Low priority (1): sys.getnthapp - COMPLETE (stub)
 */

#include "frontier.h"
#include "standard.h"

#include <stdlib.h>  /* for getenv, setenv */
#include <unistd.h>  /* for fork, execlp, _exit */
#include <sys/wait.h> /* for waitpid */
#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "sysshellcall.h"
#include "logging.h"
#include "langexternal.h"

/* External: Frontier verbs init (headless_frontier_verbs.c) */
extern boolean frontierinitverbs(void);
extern boolean inetdinitverbs(void);
extern boolean webserverinitverbs(void);

/* Token enum for all verbs in the sys processor */
enum {
    sysv_osversion = 0,
    sysv_systemtask = 1,
    sysv_browsenetwork = 2,
    sysv_appisrunning = 3,
    sysv_frontmostapp = 4,
    sysv_bringapptofront = 5,
    sysv_countapps = 6,
    sysv_getnthapp = 7,
    sysv_getapppath = 8,
    sysv_memavail = 9,
    sysv_machine = 10,
    sysv_os = 11,
    sysv_getenvironmentvariable = 12,
    sysv_setenvironmentvariable = 13,
    sysv_unixshellcommand = 14,
    sysv_winshellcommand = 15,
    sysv_openurl = 16
};

/* Helper function to trim trailing whitespace (newlines, carriage returns) from a handle
 * Modifies the handle in place by shrinking it
 */
static void trimtrailingwhitespace(Handle h) {
    if (gethandlesize(h) > 0) {
        long size = gethandlesize(h);
        lockhandle(h);
        while (size > 0 && ((*h)[size-1] == '\n' || (*h)[size-1] == '\r')) {
            size--;
        }
        unlockhandle(h);
        sethandlesize(h, size);
    }
}

/* Helper function to safely escape shell arguments for single-quote wrapping
 * Converts: foo'bar -> 'foo'\''bar'
 * This prevents command injection by escaping all single quotes and wrapping in quotes
 */
static boolean shellescapestring(bigstring input, Handle *hescaped) {
    Handle h;
    short i;

    if (!newtexthandle(PSTRING("\001", "'"), &h))
        return false;

    /* Escape each single quote as '\'' and copy other chars verbatim */
    for (i = 1; i <= stringlength(input); i++) {
        if (input[i] == '\'') {
            /* Close quote, add escaped quote, reopen quote: '\'' */
            if (!pushtexthandle(PSTRING("\004", "'\\''"), h)) {
                disposehandle(h);
                return false;
            }
        } else {
            /* Copy single character */
            bigstring singlechar;
            setstringlength(singlechar, 1);
            singlechar[1] = input[i];
            if (!pushtexthandle(singlechar, h)) {
                disposehandle(h);
                return false;
            }
        }
    }

    /* Close final quote */
    if (!pushtexthandle(PSTRING("\001", "'"), h)) {
        disposehandle(h);
        return false;
    }

    *hescaped = h;
    return true;
}

static boolean sys_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case sysv_osversion: {
            /* @IMPLEMENTED sys.osversion - Return OS version string */
            Handle hcommand, hversion;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            #ifdef __APPLE__
            /* macOS: Use sw_vers -productVersion */
            if (!newtexthandle(PSTRING("\027", "sw_vers -productVersion"), &hcommand))
                return false;
            #else
            /* Linux: Try to get distribution name and version, fall back to uname -r */
            if (!newtexthandle(BIGSTRING("\p(grep PRETTY_NAME /etc/os-release 2>/dev/null | cut -d= -f2 | tr -d '\"') || uname -r"), &hcommand))
                return false;
            #endif

            newemptyhandle(&hversion);

            if (!unixshellcall(hcommand, hversion)) {
                disposehandle(hversion);
                disposehandle(hcommand);
                return false;
            }

            disposehandle(hcommand);

            /* Trim trailing newline if present */
            trimtrailingwhitespace(hversion);

            return setheapvalue(hversion, stringvaluetype, vreturned);
            }
        case sysv_systemtask:
            /* @IMPLEMENTED sys.systemtask - no-op verb that yields to other processes
             * In GUI mode, this yields time to other applications.
             * In headless mode, this is a no-op that always returns true.
             */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            return setbooleanvalue(true, vreturned);
        case sysv_browsenetwork:
            /* @IMPLEMENTED sys.browsenetwork - GUI-only feature not available in headless */
            /* This verb displays GUI network browser dialog - cannot work without window manager */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            return setbooleanvalue(false, vreturned);
        case sysv_appisrunning: {
            /* @DEFERRED sys.appisrunning(name) - returns true if process is running
             * Current implementation uses pgrep -x which has reliability issues on macOS.
             * Needs more robust process matching strategy.
             * Issue #319: P2 - Implement robust sys.appisrunning() with cross-platform process detection
             * SECURITY: Shell-escapes process name to prevent command injection
             */
            bigstring appname;
            Handle hcommand, houtput, hescaped;
            int exit_status;
            boolean fl;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 1, appname))
                return false;

            /* Empty process name returns false */
            if (stringlength(appname) == 0)
                return setbooleanvalue(false, vreturned);

            /* Escape the process name to prevent command injection */
            if (!shellescapestring(appname, &hescaped))
                return false;

            /* Build pgrep command: pgrep -x 'escaped_name' > /dev/null 2>&1
             * Single quotes prevent all shell interpretation
             * Exit code 0 = process found, non-zero = not found
             */
            if (!newtexthandle(PSTRING("\011", "pgrep -x "), &hcommand)) {
                disposehandle(hescaped);
                return false;
            }

            if (!pushhandle(hescaped, hcommand)) {
                disposehandle(hescaped);
                disposehandle(hcommand);
                return false;
            }
            disposehandle(hescaped);

            if (!pushtexthandle(PSTRING("\021", " > /dev/null 2>&1"), hcommand)) {
                disposehandle(hcommand);
                return false;
            }

            newemptyhandle(&houtput);

            /* Use unixshellcall_separatestderr to get exit status */
            fl = unixshellcall_separatestderr(hcommand, houtput, NULL, &exit_status);
            disposehandle(hcommand);
            disposehandle(houtput);

            if (!fl)
                return setbooleanvalue(false, vreturned);

            /* pgrep returns 0 if process found, non-zero otherwise */
            return setbooleanvalue(exit_status == 0, vreturned);
            }
        case sysv_frontmostapp:
            /* @IMPLEMENTED sys.frontmostapp - no parameters, returns frontmost application name */
            /* Headless mode has no GUI concept of "frontmost app" - return empty string */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            return setstringvalue(BIGSTRING("\p"), vreturned);
        case sysv_bringapptofront: {
            /* @IMPLEMENTED sys.bringapptofront(name) - brings application to front */
            /* Headless mode cannot interact with window manager - always return false */
            bigstring appname;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 1, appname))
                return false;

            /* Cannot bring apps to front without window manager */
            return setbooleanvalue(false, vreturned);
            }
        case sysv_countapps: {
            /* @IMPLEMENTED sys.countapps - returns count of running processes
             * Uses ps aux | tail -n +2 | wc -l to count all running processes (excluding header)
             */
            Handle hcommand, houtput;
            long count;
            bigstring countstr;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Build command: ps aux | tail -n +2 | wc -l (skip header line) */
            if (!newtexthandle(PSTRING("\033", "ps aux | tail -n +2 | wc -l"), &hcommand))
                return false;

            newemptyhandle(&houtput);

            if (!unixshellcall(hcommand, houtput)) {
                disposehandle(hcommand);
                disposehandle(houtput);
                return false;
            }

            disposehandle(hcommand);

            /* Convert output handle to bigstring and parse as long */
            texthandletostring(houtput, countstr);
            disposehandle(houtput);

            /* Parse the count from the string using sscanf */
            /* Convert bigstring to C string for sscanf */
            char cstr[32];  /* Sufficient for process counts */

            /* Validate string length before copying */
            if (stringlength(countstr) >= sizeof(cstr)) {
                count = 0;  /* Sanity check failed */
            } else {
                copyptocstring(countstr, cstr);
                if (sscanf(cstr, "%ld", &count) != 1) {
                    /* If parsing fails, return 0 */
                    count = 0;
                }
            }

            return setlongvalue(count, vreturned);
            }
        case sysv_getnthapp: {
            /* @IMPLEMENTED sys.getnthapp(n) - returns name of nth running application */
            /* Not implemented in headless mode (Windows never had this either) - return empty string */
            long n;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 1, &n))
                return false;

            /* No application enumeration in headless mode */
            return setstringvalue(BIGSTRING("\p"), vreturned);
            }
        case sysv_getapppath: {
            /* @STUB sys.getapppath(name) - not implemented on this platform
             * The Carbon Process Manager APIs used by the GUI build don't work for
             * headless CLI processes. A future implementation could use proc_pidpath()
             * on macOS or /proc/self/exe on Linux.
             * Issue #320: P2 - Implement robust sys.getapppath()
             */
            bigstring appname;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 1, appname))
                return false;

            copystring(PSTRING("\062", "sys.getAppPath is not implemented on this platform"), bserror);

            return false;
            }
        case sysv_memavail:
            /* @IMPLEMENTED sys.memavail - Return available GUI memory pool */
            /* Headless mode has no GUI memory pool - always return 0 */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            return setlongvalue(0, vreturned);
        case sysv_machine: {
            /* @IMPLEMENTED sys.machine - Return machine architecture string */
            Handle hcommand, hmachine;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Use uname -m to get machine architecture */
            if (!newtexthandle(PSTRING("\010", "uname -m"), &hcommand))
                return false;

            newemptyhandle(&hmachine);

            if (!unixshellcall(hcommand, hmachine)) {
                disposehandle(hmachine);
                disposehandle(hcommand);
                return false;
            }

            disposehandle(hcommand);

            /* Trim trailing newline if present */
            trimtrailingwhitespace(hmachine);

            return setheapvalue(hmachine, stringvaluetype, vreturned);
            }
        case sysv_os:
            /* @IMPLEMENTED sys.os - Return OS name (platform-dependent) */
            /* Returns "MacOS" on macOS (capital S for backward compatibility), "Linux" on Linux, "Windows" on Windows */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            #ifdef __APPLE__
            return setstringvalue(PSTRING("\005", "MacOS"), vreturned);
            #elif defined(_WIN32)
            return setstringvalue(PSTRING("\007", "Windows"), vreturned);
            #elif defined(__linux__)
            return setstringvalue(PSTRING("\005", "Linux"), vreturned);
            #else
            return setstringvalue(PSTRING("\007", "Unknown"), vreturned);
            #endif
        case sysv_getenvironmentvariable: {
            /* @IMPLEMENTED sys.getenvironmentvariable(name) - Get environment variable value
             * Returns empty string if variable not found
             * Uses heap-allocated string to support values > 255 characters
             */
            bigstring varname;
            char cvarname[256];  /* C string buffer for environment variable name */
            char *value;
            Handle hvalue;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 1, varname))
                return false;

            /* Convert Pascal string to C string using safe copyptocstring()
             * This avoids potential buffer overflow with nullterminate() on 255-char strings
             */
            copyptocstring(varname, cvarname);

            /* Get environment variable value using C string */
            value = getenv(cvarname);

            if (value == NULL) {
                /* Variable not found - return empty string */
                if (!newtexthandle(BIGSTRING("\p"), &hvalue))
                    return false;
                return setheapvalue(hvalue, stringvaluetype, vreturned);
            }

            /* Convert C string to heap-allocated string handle */
            {
                size_t len = strlen(value);

                if (!newfilledhandle((void *)value, len, &hvalue))
                    return false;

                return setheapvalue(hvalue, stringvaluetype, vreturned);
            }
            }
        case sysv_setenvironmentvariable: {
            /* @IMPLEMENTED sys.setenvironmentvariable(name, value) - Set environment variable
             * Returns true on success, false on failure
             * Overwrites existing values
             *
             * SECURITY WARNING: Scripts can manipulate critical environment variables including:
             * - PATH: Can redirect executable searches to malicious binaries
             * - LD_PRELOAD/DYLD_INSERT_LIBRARIES: Can inject malicious shared libraries
             * - LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: Can redirect library loading
             * - Other security-sensitive variables
             *
             * RECOMMENDATION: Run Frontier in a restricted environment (container, sandboxed
             * process, or dedicated user account) when executing untrusted UserTalk scripts.
             * Consider future enhancement to whitelist/blacklist environment variable names.
             */
            bigstring varname, varvalue;
            char cvarname[256];  /* C string buffer for variable name */
            char cvarvalue[256]; /* C string buffer for variable value */

            if (!getstringvalue(hparam1, 1, varname))
                return false;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 2, varvalue))
                return false;

            /* Convert Pascal strings to C strings using safe copyptocstring()
             * This avoids potential buffer overflow with nullterminate() on 255-char strings
             */
            copyptocstring(varname, cvarname);
            copyptocstring(varvalue, cvarvalue);

            /* Set environment variable using C strings
             * POSIX setenv() third parameter (overwrite=1) replaces existing value if present
             * Windows _putenv_s() always overwrites, no flag needed
             */
            #ifdef WIN95VERSION
            if (_putenv_s(cvarname, cvarvalue) != 0) {
            #else
            if (setenv(cvarname, cvarvalue, 1) != 0) {
            #endif
                langerrormessage(PSTRING("\071", "Can't set environment variable because system call failed"));
                return false;
            }

            return setbooleanvalue(true, vreturned);
            }
        case sysv_unixshellcommand: {
            /* Verb: sys.unixshellcommand - 2025-12-27: implemented with optional stderr capture */
            Handle hcommand, hstdout, hstderr;
            short paramcount;

            if (!getexempttextvalue (hparam1, 1, &hcommand))
                return (false);

            paramcount = langgetparamcount (hparam1);

            if (paramcount == 1) {
                /* Original behavior: return stdout as string (backward compatible) */
                flnextparamislast = true;
                newemptyhandle (&hstdout);

                if (!unixshellcall (hcommand, hstdout)) {
                    disposehandle (hstdout);
                    disposehandle (hcommand);
                    return (false);
                }

                disposehandle (hcommand);
                return (setheapvalue (hstdout, stringvaluetype, vreturned));
            }
            else if (paramcount == 2) {
                /* Two params: capture stdout to address, return boolean */
                hdlhashtable htable;
                bigstring varname;
                boolean fl;

                flnextparamislast = true;

                if (!getvarparam (hparam1, 2, &htable, varname))
                    return (false);

                newemptyhandle (&hstdout);

                fl = unixshellcall (hcommand, hstdout);
                disposehandle (hcommand);

                if (!fl) {
                    disposehandle (hstdout);
                    return (false);
                }

                /* Use langassigntextvalue - efficient, no tmpstack overhead */
                if (!langassigntextvalue (htable, varname, hstdout)) {
                    disposehandle (hstdout);
                    return (false);
                }

                return (setbooleanvalue (true, vreturned));
            }
            else if (paramcount == 3) {
                /* Three params: capture both stdout and stderr to addresses, return boolean */
                hdlhashtable htable, htable2;
                bigstring varname, varname2;
                boolean fl;

                if (!getvarparam (hparam1, 2, &htable, varname))
                    return (false);

                flnextparamislast = true;

                if (!getvarparam (hparam1, 3, &htable2, varname2))
                    return (false);

                newemptyhandle (&hstdout);
                newemptyhandle (&hstderr);

                fl = unixshellcall_separatestderr (hcommand, hstdout, hstderr, NULL);
                disposehandle (hcommand);

                if (!fl) {
                    disposehandle (hstdout);
                    disposehandle (hstderr);
                    return (false);
                }

                /* Use langassigntextvalue - efficient, no tmpstack overhead */
                if (!langassigntextvalue (htable, varname, hstdout)) {
                    disposehandle (hstdout);
                    disposehandle (hstderr);
                    return (false);
                }

                if (!langassigntextvalue (htable2, varname2, hstderr)) {
                    disposehandle (hstderr);
                    return (false);
                }

                return (setbooleanvalue (true, vreturned));
            }
            else if (paramcount == 4) {
                /* Four params: capture stdout, stderr, and exit status to addresses, return boolean */

                hdlhashtable htable, htable2, htable3;
                bigstring varname, varname2, varname3;
                boolean fl;
                int exit_status;
                tyvaluerecord val_exitstatus;

                if (!getvarparam (hparam1, 2, &htable, varname))
                    return (false);

                if (!getvarparam (hparam1, 3, &htable2, varname2))
                    return (false);


                flnextparamislast = true;

                if (!getvarparam (hparam1, 4, &htable3, varname3))
                    return (false);


                newemptyhandle (&hstdout);
                newemptyhandle (&hstderr);

                fl = unixshellcall_separatestderr (hcommand, hstdout, hstderr, &exit_status);
                disposehandle (hcommand);

                if (!fl) {
                    disposehandle (hstdout);
                    disposehandle (hstderr);
                    return (false);
                }

                /* Use langassigntextvalue - efficient, no tmpstack overhead */
                if (!langassigntextvalue (htable, varname, hstdout)) {
                    disposehandle (hstdout);
                    disposehandle (hstderr);
                    return (false);
                }

                if (!langassigntextvalue (htable2, varname2, hstderr)) {
                    disposehandle (hstderr);
                    return (false);
                }

                /* For exit status (integer), use setlongvalue + hashtableassign pattern */
                setlongvalue (exit_status, &val_exitstatus);

                if (!hashtableassign (htable3, varname3, val_exitstatus)) {
                    return (false);
                }

                return (setbooleanvalue (true, vreturned));
            }
            else {
                langparamerror (unimplementedverberror, PSTRING("\023", "too many parameters"));
                return (false);
            }
            }
        case sysv_winshellcommand: {
            /* sys.winshellcommand - Windows-only verb, not available on macOS/Linux */
            Handle hcommand;

            if (!getexempttextvalue(hparam1, 1, &hcommand))
                return false;

            /* Don't dispose hcommand — exempted handles are managed by heap/hashtable */

            copystring(PSTRING("\067", "sys.winShellCommand is not implemented on this platform"), bserror);

            return false;
            }
        case sysv_openurl: {
            /*
             * sys.openUrl(url) - Open a URL in the default browser.
             * Uses fork/execlp to avoid shell injection.
             * Respects --browser CLI arg via system.environment.args.browser:
             *   "agent-browser" → execlp("agent-browser", "agent-browser", "open", url)
             *   "default" or absent → execlp("open", "open", url) on macOS
             * See shellsysverbs.c openurlfunc for the equivalent classic implementation.
             */

            Handle hurl;

            flnextparamislast = true;

            if (!getexempttextvalue (hparam1, 1, &hurl))
                return (false);

            if (!enlargehandle (hurl, 1, "\0")) {
                disposehandle (hurl);
                return (false);
            }

            lockhandle (hurl);

            {
                const char *url = (const char *) *hurl;

                if (url[0] == '\0') {
                    unlockhandle (hurl);
                    disposehandle (hurl);
                    langerrormessage (PSTRING ("\x31", "Can't open the URL because it is an empty string."));
                    return (false);
                }

                /* Check --browser arg from system.environment.args */
                boolean use_agent_browser = false;

                {
                    hdlhashnode hnode;
                    tyvaluerecord vargs;
                    bigstring bsargs;
                    bigstring bsbrowser;
                    copystring (PSTRING ("\x04", "args"), bsargs);
                    copystring (PSTRING ("\x07", "browser"), bsbrowser);

                    if (environmenttable != nil &&
                        hashtablelookup (environmenttable, bsargs, &vargs, &hnode)) {

                        if (vargs.valuetype == externalvaluetype) {
                            hdlhashtable htargs;
                            hdlexternalvariable hv = (hdlexternalvariable) vargs.data.externalvalue;

                            if (hv != nil && langexternalvaltotable (vargs, &htargs, hnode)) {

                                tyvaluerecord vbrowser;
                                hdlhashnode hbnode;

                                if (hashtablelookup (htargs, bsbrowser, &vbrowser, &hbnode)) {
                                    if (vbrowser.valuetype == stringvaluetype && vbrowser.data.stringvalue != nil) {
                                        long len = gethandlesize (vbrowser.data.stringvalue);
                                        if (len == (long)(sizeof ("agent-browser") - 1) && memcmp (*vbrowser.data.stringvalue, "agent-browser", sizeof ("agent-browser") - 1) == 0) {
                                            use_agent_browser = true;
                                        }
                                        else if (len != (long)(sizeof ("default") - 1) || memcmp (*vbrowser.data.stringvalue, "default", sizeof ("default") - 1) != 0) {
                                            unlockhandle (hurl);
                                            disposehandle (hurl);
                                            langerrormessage (PSTRING ("\x3f", "Can't open URL: --browser must be \"default\" or \"agent-browser\"."));
                                            return (false);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

#if defined(__APPLE__) || defined(__linux__)
                /* Double-fork to avoid zombie processes. */
                pid_t pid = fork ();

                if (pid == 0) {
                    pid_t pid2 = fork ();

                    if (pid2 == 0) {
                        /* All execlp calls rely on a trusted PATH. */
                        if (use_agent_browser) {
                            execlp ("agent-browser", "agent-browser", "open", url, NULL);
                        }
                        else {
#ifdef __APPLE__
                            execlp ("open", "open", url, NULL);
#else
                            execlp ("xdg-open", "xdg-open", url, NULL);
#endif
                        }
                        _exit (1);
                    }

                    _exit (pid2 < 0 ? 1 : 0);
                }

                unlockhandle (hurl);
                disposehandle (hurl);

                if (pid < 0)
                    return (setbooleanvalue (false, vreturned));

                int status = 0;
                waitpid (pid, &status, 0);

                boolean launched = WIFEXITED (status) && WEXITSTATUS (status) == 0;

                return (setbooleanvalue (launched, vreturned));
#else
                unlockhandle (hurl);
                disposehandle (hurl);
                langerrormessage (PSTRING ("\x2d", "sys.openUrl is not supported on this platform"));
                return (false);
#endif
            }
            }

        default:
            return false;
    }
}

boolean sysinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\003", "sys"), bsname);

    if (!newfunctionprocessor(bsname, &sys_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\011", "osversion"), sysv_osversion);
    ADD_VERB(PSTRING("\012", "systemtask"), sysv_systemtask);
    ADD_VERB(PSTRING("\015", "browsenetwork"), sysv_browsenetwork);
    ADD_VERB(PSTRING("\014", "appisrunning"), sysv_appisrunning);
    ADD_VERB(PSTRING("\014", "frontmostapp"), sysv_frontmostapp);
    ADD_VERB(PSTRING("\017", "bringapptofront"), sysv_bringapptofront);
    ADD_VERB(PSTRING("\011", "countapps"), sysv_countapps);
    ADD_VERB(PSTRING("\011", "getnthapp"), sysv_getnthapp);
    ADD_VERB(PSTRING("\012", "getapppath"), sysv_getapppath);
    ADD_VERB(PSTRING("\010", "memavail"), sysv_memavail);
    ADD_VERB(PSTRING("\007", "machine"), sysv_machine);
    ADD_VERB(PSTRING("\002", "os"), sysv_os);
    ADD_VERB(PSTRING("\026", "getenvironmentvariable"), sysv_getenvironmentvariable);
    ADD_VERB(PSTRING("\026", "setenvironmentvariable"), sysv_setenvironmentvariable);
    ADD_VERB(PSTRING("\020", "unixshellcommand"), sysv_unixshellcommand);
    ADD_VERB(PSTRING("\017", "winshellcommand"), sysv_winshellcommand);
    ADD_VERB(PSTRING("\007", "openUrl"), sysv_openurl);

    #undef ADD_VERB

    pophashtable();

    /* Initialize Frontier verbs (frontier.version, etc.) */
    /* In main build, this is done via loadfunctionprocessor in sysinitverbs */
    if (!frontierinitverbs())
        return false;

    /* Initialize inetd verbs (inetd.supervisor for kernelized webserver) */
    if (!inetdinitverbs())
        return false;

    /* Initialize webserver verbs (webserver.server, webserver.dispatch, etc.) */
    if (!webserverinitverbs())
        return false;

    return true;
}
