/*
 * headless_op_verbs.c - Op processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains hand-written implementations for Phase 1-4 op verbs.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status:
 * - Phase 1 (10 verbs): COMPLETE - insert, getLineText, level, go, firstSummit,
 *                                   countSubs, countSummits, expand, collapse
 * - Phase 2 (8 verbs):  PENDING   - setLineText, promote, demote, deleteLine, etc.
 * - Phase 3 (10 verbs): PENDING   - State management verbs
 * - Phase 4 (17 verbs): PENDING   - Advanced operations
 *
 * See planning/phase3/op_verb_implementation_plan.md for complete roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "langexternal.h"
#include "opverbs.h"
#include "opinternal.h"

/*
 * Helper function: Set error message from C string
 *
 * Converts a C string to Pascal string format and copies to bserror.
 * This ensures consistency - the length prefix is automatically calculated
 * from the string length, preventing manual octal prefix errors.
 */
static void seterrorstring(const char *msg, bigstring bserror) {
    copyctopstring(msg, bserror);
}

/*
 * Helper function: Get outline from target system (headless mode)
 *
 * In GUI mode, op verbs get the outline from the frontmost window.
 * In headless mode, we get it from the target.get() system.
 *
 * Returns: true if outline was successfully retrieved, false otherwise
 * On error, bserror contains a Pascal string with the error message
 */
static boolean getoutlinefromtarget(hdloutlinerecord *ho, bigstring bserror) {
    hdlhashtable htable;
    bigstring bsname;
    tyvaluerecord val;
    hdlhashnode hnode;
    hdlexternalvariable hv;

    /* Get target from lang.target.get() */
    if (!langgettarget(&htable, bsname)) {
        seterrorstring("no outline target set", bserror);
        return false;
    }

    /* Look up the variable */
    if (!hashtablelookup(htable, bsname, &val, &hnode)) {
        seterrorstring("target variable not found", bserror);
        return false;
    }

    /* Check if it's a table (not an outline) */
    if (langexternalvaltotable(val, &htable, hnode)) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Verify it's an external variable type */
    if (val.valuetype != externalvaluetype) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Get the external variable handle */
    hv = (hdlexternalvariable)val.data.externalvalue;

    /* Verify handle is valid */
    if (hv == NULL) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Verify it's an outline processor type */
    if ((**hv).id != idoutlineprocessor) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Ensure outline is in memory */
    if (!opverbinmemory(NULL, hv)) {
        seterrorstring("could not load outline", bserror);
        return false;
    }

    /* Get the outline record */
    if ((**hv).variabledata == NULL) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    *ho = (hdloutlinerecord)(**hv).variabledata;
    return true;
}

/* Token enum for all verbs in the op processor */
enum {
    opv_getlinetext = 0,
    opv_level = 1,
    opv_countsubs = 2,
    opv_countsummits = 3,
    opv_go = 4,
    opv_firstsummit = 5,
    opv_expand = 6,
    opv_collapse = 7,
    opv_subsexpanded = 8,
    opv_insert = 9,
    opv_find = 10,
    opv_sort = 11,
    opv_setlinetext = 12,
    opv_reorg = 13,
    opv_promote = 14,
    opv_demote = 15,
    opv_hoist = 16,
    opv_dehoist = 17,
    opv_deletesubs = 18,
    opv_deleteline = 19,
    opv_tabkeyreorg = 20,
    opv_flatcursorkeys = 21,
    opv_getdisplay = 22,
    opv_setdisplay = 23,
    opv_getcursor = 24,
    opv_setcursor = 25,
    opv_getrefcon = 26,
    opv_setrefcon = 27,
    opv_getexpansionstate = 28,
    opv_setexpansionstate = 29,
    opv_getscrollstate = 30,
    opv_setscrollstate = 31,
    opv_getsuboutline = 32,
    opv_insertoutline = 33,
    opv_setmodified = 34,
    opv_getselection = 35,
    opv_getheadnumber = 36,
    opv_visitall = 37,
    opv_getselectedsuboutlines = 38,
    opv_xmltooutline = 39,
    opv_outlinetoxml = 40,
    opv_sethtmlformatting = 41,
    opv_gethtmlformatting = 42,
    opv_setdynamic = 43,
    opv_getdynamic = 44
};

static boolean op_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case opv_getlinetext: {
            /* op.getLineText() - Get text of current headline */
            Handle htext;
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);

            /* If headline is being edited, update text handle */
            opwriteeditbuffer();

            hbarcursor = (**ho).hbarcursor;

            if (!copyhandle((**hbarcursor).headstring, &htext)) {
                oppopoutline();
                return false;
            }

            oppopoutline();

            return setheapvalue(htext, stringvaluetype, vreturned);
        }
        case opv_level: {
            /* op.level() - Get nesting level of current headline */
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            short level;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            level = (**hbarcursor).headlevel + 1;  /* Convert 0-based to 1-based */
            oppopoutline();

            return setlongvalue(level, vreturned);
        }
        case opv_countsubs: {
            /* op.countSubs(levels) -> long - Count sub-headlines */
            short level;
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            long ct;

            flnextparamislast = true;

            if (!getintvalue(hparam1, 1, &level))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            ct = opcountsubheads(hbarcursor, level);
            oppopoutline();

            return setlongvalue(ct, vreturned);
        }
        case opv_countsummits: {
            /* op.countSummits() - Count top-level headlines */
            hdloutlinerecord ho;
            long ct;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);
            ct = opcountatlevel((**ho).hsummit);
            oppopoutline();

            return setlongvalue(ct, vreturned);
        }
        case opv_go: {
            /* Verb #4: op.go(direction, count) -> boolean */
            tydirection dir;
            long units;
            hdloutlinerecord ho;
            boolean fl;

            if (!getdirectionvalue(hparam1, 1, &dir))
                return false;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 2, &units))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);
            fl = opmotionkey(dir, units, false);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_firstsummit: {
            /* Verb #5: op.firstsummit - go to first summit */
            hdloutlinerecord ho;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);
            fl = opmotionkey(flatup, longinfinity, false);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_expand: {
            /* op.expand(levels) -> boolean - expands subheads */
            short level;
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            boolean fl;

            flnextparamislast = true;

            if (!getintvalue(hparam1, 1, &level))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            fl = opexpand(hbarcursor, level, true);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_collapse: {
            /* op.collapse() - Collapse subheads */
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            fl = opcollapse(hbarcursor);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_subsexpanded:
            /* Verb #8: op.subsexpanded - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_insert: {
            /* Verb #9: op.insert(text, direction) -> boolean */
            Handle htext;
            tydirection dir;
            hdloutlinerecord ho;
            boolean fl;

            /* Parse parameters */
            if (!getexempttextvalue(hparam1, 1, &htext))
                return false;

            flnextparamislast = true;

            if (!getdirectionvalue(hparam1, 2, &dir)) {
                disposehandle(htext);
                return false;
            }

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                disposehandle(htext);
                return false;
            }

            /* Push outline, insert, pop */
            oppushoutline(ho);
            fl = opinserthandle(htext, dir);
            oppopoutline();

            disposehandle(htext);

            return setbooleanvalue(fl, vreturned);
        }
        case opv_find:
            /* Verb #10: op.find - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_sort:
            /* Verb #11: op.sort - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setlinetext:
            /* Verb #12: op.setlinetext - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_reorg:
            /* Verb #13: op.reorg - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_promote:
            /* Verb #14: op.promote - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_demote:
            /* Verb #15: op.demote - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_hoist:
            /* Verb #16: op.hoist - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_dehoist:
            /* Verb #17: op.dehoist - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_deletesubs:
            /* Verb #18: op.deletesubs - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_deleteline:
            /* Verb #19: op.deleteline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_tabkeyreorg:
            /* Verb #20: op.tabkeyreorg - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_flatcursorkeys:
            /* Verb #21: op.flatcursorkeys - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getdisplay:
            /* Verb #22: op.getdisplay - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setdisplay:
            /* Verb #23: op.setdisplay - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getcursor:
            /* Verb #24: op.getcursor - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setcursor:
            /* Verb #25: op.setcursor - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getrefcon:
            /* Verb #26: op.getrefcon - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setrefcon:
            /* Verb #27: op.setrefcon - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getexpansionstate:
            /* Verb #28: op.getexpansionstate - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setexpansionstate:
            /* Verb #29: op.setexpansionstate - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getscrollstate:
            /* Verb #30: op.getscrollstate - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setscrollstate:
            /* Verb #31: op.setscrollstate - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getsuboutline:
            /* Verb #32: op.getsuboutline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_insertoutline:
            /* Verb #33: op.insertoutline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setmodified:
            /* Verb #34: op.setmodified - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getselection:
            /* Verb #35: op.getselection - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getheadnumber:
            /* Verb #36: op.getheadnumber - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_visitall:
            /* Verb #37: op.visitall - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getselectedsuboutlines:
            /* Verb #38: op.getselectedsuboutlines - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_xmltooutline:
            /* Verb #39: op.xmltooutline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_outlinetoxml:
            /* Verb #40: op.outlinetoxml - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_sethtmlformatting:
            /* Verb #41: op.sethtmlformatting - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_gethtmlformatting:
            /* Verb #42: op.gethtmlformatting - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setdynamic:
            /* Verb #43: op.setdynamic - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getdynamic:
            /* Verb #44: op.getdynamic - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        default:
            return false;
    }
}

boolean opinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pop"), bsname);

    if (!newfunctionprocessor(bsname, &op_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pgetlinetext"), opv_getlinetext);
    ADD_VERB(BIGSTRING("\plevel"), opv_level);
    ADD_VERB(BIGSTRING("\pcountsubs"), opv_countsubs);
    ADD_VERB(BIGSTRING("\pcountsummits"), opv_countsummits);
    ADD_VERB(BIGSTRING("\pgo"), opv_go);
    ADD_VERB(BIGSTRING("\pfirstsummit"), opv_firstsummit);
    ADD_VERB(BIGSTRING("\pexpand"), opv_expand);
    ADD_VERB(BIGSTRING("\pcollapse"), opv_collapse);
    ADD_VERB(BIGSTRING("\psubsexpanded"), opv_subsexpanded);
    ADD_VERB(BIGSTRING("\pinsert"), opv_insert);
    ADD_VERB(BIGSTRING("\pfind"), opv_find);
    ADD_VERB(BIGSTRING("\psort"), opv_sort);
    ADD_VERB(BIGSTRING("\psetlinetext"), opv_setlinetext);
    ADD_VERB(BIGSTRING("\preorg"), opv_reorg);
    ADD_VERB(BIGSTRING("\ppromote"), opv_promote);
    ADD_VERB(BIGSTRING("\pdemote"), opv_demote);
    ADD_VERB(BIGSTRING("\phoist"), opv_hoist);
    ADD_VERB(BIGSTRING("\pdehoist"), opv_dehoist);
    ADD_VERB(BIGSTRING("\pdeletesubs"), opv_deletesubs);
    ADD_VERB(BIGSTRING("\pdeleteline"), opv_deleteline);
    ADD_VERB(BIGSTRING("\ptabkeyreorg"), opv_tabkeyreorg);
    ADD_VERB(BIGSTRING("\pflatcursorkeys"), opv_flatcursorkeys);
    ADD_VERB(BIGSTRING("\pgetdisplay"), opv_getdisplay);
    ADD_VERB(BIGSTRING("\psetdisplay"), opv_setdisplay);
    ADD_VERB(BIGSTRING("\pgetcursor"), opv_getcursor);
    ADD_VERB(BIGSTRING("\psetcursor"), opv_setcursor);
    ADD_VERB(BIGSTRING("\pgetrefcon"), opv_getrefcon);
    ADD_VERB(BIGSTRING("\psetrefcon"), opv_setrefcon);
    ADD_VERB(BIGSTRING("\pgetexpansionstate"), opv_getexpansionstate);
    ADD_VERB(BIGSTRING("\psetexpansionstate"), opv_setexpansionstate);
    ADD_VERB(BIGSTRING("\pgetscrollstate"), opv_getscrollstate);
    ADD_VERB(BIGSTRING("\psetscrollstate"), opv_setscrollstate);
    ADD_VERB(BIGSTRING("\pgetsuboutline"), opv_getsuboutline);
    ADD_VERB(BIGSTRING("\pinsertoutline"), opv_insertoutline);
    ADD_VERB(BIGSTRING("\psetmodified"), opv_setmodified);
    ADD_VERB(BIGSTRING("\pgetselection"), opv_getselection);
    ADD_VERB(BIGSTRING("\pgetheadnumber"), opv_getheadnumber);
    ADD_VERB(BIGSTRING("\pvisitall"), opv_visitall);
    ADD_VERB(BIGSTRING("\pgetselectedsuboutlines"), opv_getselectedsuboutlines);
    ADD_VERB(BIGSTRING("\pxmltooutline"), opv_xmltooutline);
    ADD_VERB(BIGSTRING("\poutlinetoxml"), opv_outlinetoxml);
    ADD_VERB(BIGSTRING("\psethtmlformatting"), opv_sethtmlformatting);
    ADD_VERB(BIGSTRING("\pgethtmlformatting"), opv_gethtmlformatting);
    ADD_VERB(BIGSTRING("\psetdynamic"), opv_setdynamic);
    ADD_VERB(BIGSTRING("\pgetdynamic"), opv_getdynamic);

    #undef ADD_VERB

    pophashtable();
    return true;
}
