/*
 * headless_sys_verbs.c - Sys processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the sys processor */
enum {
    sysv_osversion = 0,
    sysv_systemtask = 1,
    sysv_browsenetwork = 2,
    sysv_appisrunning = 3,
    sysv_frontmostapp = 4,
    sysv_bringapptofront = 5,
    sysv_countapps = 6,
    sysv_getnthapp = 7,
    sysv_getapppath = 8,
    sysv_memavail = 9,
    sysv_machine = 10,
    sysv_os = 11,
    sysv_getenvironmentvariable = 12,
    sysv_setenvironmentvariable = 13,
    sysv_unixshellcommand = 14,
    sysv_winshellcommand = 15
};

static boolean sys_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case sysv_osversion:
            /* Verb: sys.osversion - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_systemtask:
            /* Verb: sys.systemtask - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_browsenetwork:
            /* Verb: sys.browsenetwork - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_appisrunning:
            /* Verb: sys.appisrunning - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_frontmostapp:
            /* Verb: sys.frontmostapp - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_bringapptofront:
            /* Verb: sys.bringapptofront - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_countapps:
            /* Verb: sys.countapps - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_getnthapp:
            /* Verb: sys.getnthapp - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_getapppath:
            /* Verb: sys.getapppath - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_memavail:
            /* Verb: sys.memavail - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_machine:
            /* Verb: sys.machine - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_os:
            /* Verb: sys.os - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_getenvironmentvariable:
            /* Verb: sys.getenvironmentvariable - implemented in shellsysverbs.c */
            /* This stub should never be reached */
            break;
        case sysv_setenvironmentvariable:
            /* Verb: sys.setenvironmentvariable - implemented in shellsysverbs.c */
            /* This stub should never be reached */
            break;
        case sysv_unixshellcommand:
            /* Verb: sys.unixshellcommand - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case sysv_winshellcommand:
            /* sys.winshellcommand - error stub */
            if (bserror)
                copystring(BIGSTRING("\pCan't run Windows shell commands because they are not available on this platform"), bserror);
            return false;
        default:
            return false;
    }
}

boolean sysinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\psys"), bsname);

    if (!newfunctionprocessor(bsname, &sys_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\posversion"), sysv_osversion);
    ADD_VERB(BIGSTRING("\psystemtask"), sysv_systemtask);
    ADD_VERB(BIGSTRING("\pbrowsenetwork"), sysv_browsenetwork);
    ADD_VERB(BIGSTRING("\pappisrunning"), sysv_appisrunning);
    ADD_VERB(BIGSTRING("\pfrontmostapp"), sysv_frontmostapp);
    ADD_VERB(BIGSTRING("\pbringapptofront"), sysv_bringapptofront);
    ADD_VERB(BIGSTRING("\pcountapps"), sysv_countapps);
    ADD_VERB(BIGSTRING("\pgetnthapp"), sysv_getnthapp);
    ADD_VERB(BIGSTRING("\pgetapppath"), sysv_getapppath);
    ADD_VERB(BIGSTRING("\pmemavail"), sysv_memavail);
    ADD_VERB(BIGSTRING("\pmachine"), sysv_machine);
    ADD_VERB(BIGSTRING("\pos"), sysv_os);
    ADD_VERB(BIGSTRING("\pgetenvironmentvariable"), sysv_getenvironmentvariable);
    ADD_VERB(BIGSTRING("\psetenvironmentvariable"), sysv_setenvironmentvariable);
    ADD_VERB(BIGSTRING("\punixshellcommand"), sysv_unixshellcommand);
    ADD_VERB(BIGSTRING("\pwinshellcommand"), sysv_winshellcommand);

    #undef ADD_VERB

    pophashtable();
    return true;
}
