/*
 * headless_clipboard_verbs.c - Clipboard processor verbs (GENERATED FILE)
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py.
 * Now contains headless-compatible no-op implementations.
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the clipboard processor */
enum {
    cliv_get = 0,
    cliv_put = 1
};

static boolean clipboard_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)hparam1;
    switch(token) {
        case cliv_get:
            /* Headless: no clipboard, return empty string */
            return setstringvalue(emptystring, vreturned);
        case cliv_put:
            /* Headless: no clipboard, silently discard */
            return setbooleanvalue(true, vreturned);
        default:
            return false;
    }
}

boolean clipboardinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\011", "clipboard"), bsname);

    if (!newfunctionprocessor(bsname, &clipboard_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\003", "get"), cliv_get);
    ADD_VERB(PSTRING("\003", "put"), cliv_put);

    #undef ADD_VERB

    pophashtable();
    return true;
}
