/*
 * headless_date_verbs.c - Date processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains complete hand-written implementations of all date verbs.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation (2025-12-15 by Codex):
 * - Uses 64-bit Mac epoch (1904) as per planning/phase3/date_time_format_standard.md
 * - All date manipulation functions use existing timedate.c helpers
 * - Component extraction (day, month, year, hour, minute, seconds) implemented
 * - Date arithmetic (tomorrow, yesterday, next/prev month/week/year) implemented
 * - Date formatting (shortstring, longstring, abbrevstring) implemented
 * - All date verbs fully functional for headless CLI
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "timedate.h"

/* External functions from langdate.c */
extern boolean datenetstandardstring (int64_t localdate, tyvaluerecord *vreturn);
extern boolean datemonthtostring (long ix, tyvaluerecord *vreturn);
extern boolean datedayofweektostring (long ix, tyvaluerecord *vreturn);
extern boolean dateversionlessthan (bigstring bsv1, bigstring bsv2, tyvaluerecord *v);

/* Token enum for all verbs in the date processor */
enum {
    datv_get = 0,
    datv_set = 1,
    datv_abbrevstring = 2,
    datv_dayofweek = 3,
    datv_daysinmonth = 4,
    datv_daystring = 5,
    datv_firstofmonth = 6,
    datv_lastofmonth = 7,
    datv_longstring = 8,
    datv_nextmonth = 9,
    datv_nextweek = 10,
    datv_nextyear = 11,
    datv_prevmonth = 12,
    datv_prevweek = 13,
    datv_prevyear = 14,
    datv_shortstring = 15,
    datv_tomorrow = 16,
    datv_weeksinmonth = 17,
    datv_yesterday = 18,
    datv_getcurrenttimezone = 19,
    datv_netstandardstring = 20,
    datv_monthtostring = 21,
    datv_dayofweektostring = 22,
    datv_versionlessthan = 23,
    datv_day = 24,
    datv_month = 25,
    datv_year = 26,
    datv_hour = 27,
    datv_minute = 28,
    datv_seconds = 29
};

static boolean date_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;  /* Suppress unused parameter warning for implemented verbs */

    switch(token) {
        case datv_get: {
            /* Verb: date.get(date, @day, @month, @year, @hour, @minute, @second) - Extract all components */
            int64_t date;
            short day, month, year, hour, minute, second;
            tyvaluerecord v;
            hdlhashtable ht;
            bigstring bs;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);

            /* Set output parameters via variable addresses */
            if (!getvarparam(hparam1, 2, &ht, bs))
                return false;
            if (!setintvalue(day, &v))
                return false;
            if (!hashtableassign(ht, bs, v))
                return false;

            if (!getvarparam(hparam1, 3, &ht, bs))
                return false;
            if (!setintvalue(month, &v))
                return false;
            if (!hashtableassign(ht, bs, v))
                return false;

            if (!getvarparam(hparam1, 4, &ht, bs))
                return false;
            if (!setintvalue(year, &v))
                return false;
            if (!hashtableassign(ht, bs, v))
                return false;

            if (!getvarparam(hparam1, 5, &ht, bs))
                return false;
            if (!setintvalue(hour, &v))
                return false;
            if (!hashtableassign(ht, bs, v))
                return false;

            if (!getvarparam(hparam1, 6, &ht, bs))
                return false;
            if (!setintvalue(minute, &v))
                return false;
            if (!hashtableassign(ht, bs, v))
                return false;

            flnextparamislast = true;

            if (!getvarparam(hparam1, 7, &ht, bs))
                return false;
            if (!setintvalue(second, &v))
                return false;
            if (!hashtableassign(ht, bs, v))
                return false;

            (*vreturned).data.flvalue = true;
            return true;
        }

        case datv_set: {
            /* Verb: date.set(day, month, year, hour, minute, second) - Construct date from components */
            short day, month, year, hour, minute, second;
            int64_t date;

            if (!getintvalue(hparam1, 1, &day))
                return false;

            if (!getintvalue(hparam1, 2, &month))
                return false;

            if (!getintvalue(hparam1, 3, &year))
                return false;

            if (!getintvalue(hparam1, 4, &hour))
                return false;

            if (!getintvalue(hparam1, 5, &minute))
                return false;

            flnextparamislast = true;

            if (!getintvalue(hparam1, 6, &second))
                return false;

            date = datetimetoseconds(day, month, year, hour, minute, second);
            return setdatevalue(date, vreturned);
        }
        case datv_abbrevstring: {
            /* Verb: date.abbrevstring(date) - Return abbreviated date string */
            int64_t date;
            bigstring bs;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            abbrevdatestring((unsigned long)date, bs);
            return setstringvalue(bs, vreturned);
        }

        case datv_dayofweek: {
            /* Verb: date.dayofweek(date) - Return day of week (1=Sunday, 7=Saturday) */
            int64_t date;
            short dayofweek;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodayofweek(date, &dayofweek);
            return setlongvalue(dayofweek, vreturned);
        }

        case datv_daysinmonth: {
            /* Verb: date.daysinmonth(date) - Return number of days in month */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(daysInMonth(month, year), vreturned);
        }

        case datv_daystring: {
            /* Verb: date.daystring(date) - Return day of week as string */
            int64_t date;
            short dayofweek;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodayofweek(date, &dayofweek);
            return datedayofweektostring(dayofweek, vreturned);
        }

        case datv_firstofmonth: {
            /* Verb: date.firstofmonth(date) - Return first day of month */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(firstofmonth((unsigned long)date), vreturned);
        }

        case datv_lastofmonth: {
            /* Verb: date.lastofmonth(date) - Return last day of month */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(lastofmonth((unsigned long)date), vreturned);
        }

        case datv_longstring: {
            /* Verb: date.longstring(date) - Return long date string */
            int64_t date;
            bigstring bs;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            longdatestring((unsigned long)date, bs);
            return setstringvalue(bs, vreturned);
        }

        case datv_nextmonth: {
            /* Verb: date.nextmonth(date) - Return date one month in future */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(nextmonth((unsigned long)date), vreturned);
        }

        case datv_nextweek: {
            /* Verb: date.nextweek(date) - Return date one week in future */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(date + (7L * 24L * 60L * 60L), vreturned);
        }

        case datv_nextyear: {
            /* Verb: date.nextyear(date) - Return date one year in future */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(nextyear((unsigned long)date), vreturned);
        }

        case datv_prevmonth: {
            /* Verb: date.prevmonth(date) - Return date one month in past */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(prevmonth((unsigned long)date), vreturned);
        }

        case datv_prevweek: {
            /* Verb: date.prevweek(date) - Return date one week in past */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(date - (7L * 24L * 60L * 60L), vreturned);
        }

        case datv_prevyear: {
            /* Verb: date.prevyear(date) - Return date one year in past */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(prevyear((unsigned long)date), vreturned);
        }

        case datv_shortstring: {
            /* Verb: date.shortstring(date) - Return short date string */
            int64_t date;
            bigstring bs;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            shortdatestring((unsigned long)date, bs);
            return setstringvalue(bs, vreturned);
        }

        case datv_tomorrow: {
            /* Verb: date.tomorrow(date) - Return tomorrow's date */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(date + (24L * 60L * 60L), vreturned);
        }

        case datv_weeksinmonth: {
            /* Verb: date.weeksinmonth(date) - Return number of weeks in month */
            int64_t date;
            short day, month, year, hour, minute, second;
            short days;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            days = daysInMonth(month, year);
            /* Calculate weeks: (days + 6) / 7 rounds up */
            return setlongvalue((days + 6) / 7, vreturned);
        }

        case datv_yesterday: {
            /* Verb: date.yesterday(date) - Return yesterday's date */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return setlongvalue(date - (24L * 60L * 60L), vreturned);
        }

        case datv_getcurrenttimezone: {
            /* Verb: date.getcurrenttimezone() - Return timezone bias in seconds */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            return setlongvalue(getcurrenttimezonebias(), vreturned);
        }

        case datv_netstandardstring: {
            /* Verb: date.netstandardstring(date) - Return RFC 822 date string */
            int64_t date;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            return datenetstandardstring(date, vreturned);
        }

        case datv_monthtostring: {
            /* Verb: date.monthtostring(monthnum) - Return month name (1-12) */
            long monthnum;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 1, &monthnum))
                return false;

            return datemonthtostring(monthnum, vreturned);
        }

        case datv_dayofweektostring: {
            /* Verb: date.dayofweektostring(daynum) - Return day name (1-7) */
            long daynum;

            flnextparamislast = true;

            if (!getlongvalue(hparam1, 1, &daynum))
                return false;

            return datedayofweektostring(daynum, vreturned);
        }

        case datv_versionlessthan: {
            /* Verb: date.versionlessthan(v1, v2) - Compare version strings */
            bigstring bsv1, bsv2;

            if (!getstringvalue(hparam1, 1, bsv1))
                return false;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 2, bsv2))
                return false;

            return dateversionlessthan(bsv1, bsv2, vreturned);
        }

        case datv_day: {
            /* Verb: date.day(date) - Extract day component */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(day, vreturned);
        }

        case datv_month: {
            /* Verb: date.month(date) - Extract month component
             * @IMPLEMENTED - Fully functional, delegates to UserTalk script in system.verbs.builtins.date.month */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(month, vreturned);
        }

        case datv_year: {
            /* Verb: date.year(date) - Extract year component
             * @IMPLEMENTED - Fully functional, delegates to UserTalk script in system.verbs.builtins.date.year */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(year, vreturned);
        }

        case datv_hour: {
            /* Verb: date.hour(date) - Extract hour component
             * @IMPLEMENTED - Fully functional, delegates to UserTalk script in system.verbs.builtins.date.hour */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(hour, vreturned);
        }

        case datv_minute: {
            /* Verb: date.minute(date) - Extract minute component
             * @IMPLEMENTED - Fully functional, delegates to UserTalk script in system.verbs.builtins.date.minute */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(minute, vreturned);
        }

        case datv_seconds: {
            /* Verb: date.seconds(date) - Extract seconds component */
            int64_t date;
            short day, month, year, hour, minute, second;

            flnextparamislast = true;

            if (!getdatevalue(hparam1, 1, &date))
                return false;

            secondstodatetime(date, &day, &month, &year, &hour, &minute, &second);
            return setlongvalue(second, vreturned);
        }
        default:
            return false;
    }
}

boolean dateinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\004date"), bsname);

    if (!newfunctionprocessor(bsname, &date_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\003get"), datv_get);
    ADD_VERB(BIGSTRING("\003set"), datv_set);
    ADD_VERB(BIGSTRING("\014abbrevstring"), datv_abbrevstring);
    ADD_VERB(BIGSTRING("\011dayofweek"), datv_dayofweek);
    ADD_VERB(BIGSTRING("\013daysinmonth"), datv_daysinmonth);
    ADD_VERB(BIGSTRING("\011daystring"), datv_daystring);
    ADD_VERB(BIGSTRING("\014firstofmonth"), datv_firstofmonth);
    ADD_VERB(BIGSTRING("\013lastofmonth"), datv_lastofmonth);
    ADD_VERB(BIGSTRING("\012longstring"), datv_longstring);
    ADD_VERB(BIGSTRING("\011nextmonth"), datv_nextmonth);
    ADD_VERB(BIGSTRING("\010nextweek"), datv_nextweek);
    ADD_VERB(BIGSTRING("\010nextyear"), datv_nextyear);
    ADD_VERB(BIGSTRING("\011prevmonth"), datv_prevmonth);
    ADD_VERB(BIGSTRING("\010prevweek"), datv_prevweek);
    ADD_VERB(BIGSTRING("\010prevyear"), datv_prevyear);
    ADD_VERB(BIGSTRING("\013shortstring"), datv_shortstring);
    ADD_VERB(BIGSTRING("\010tomorrow"), datv_tomorrow);
    ADD_VERB(BIGSTRING("\014weeksinmonth"), datv_weeksinmonth);
    ADD_VERB(BIGSTRING("\011yesterday"), datv_yesterday);
    ADD_VERB(BIGSTRING("\022getcurrenttimezone"), datv_getcurrenttimezone);
    ADD_VERB(BIGSTRING("\021netstandardstring"), datv_netstandardstring);
    ADD_VERB(BIGSTRING("\015monthtostring"), datv_monthtostring);
    ADD_VERB(BIGSTRING("\021dayofweektostring"), datv_dayofweektostring);
    ADD_VERB(BIGSTRING("\017versionlessthan"), datv_versionlessthan);
    ADD_VERB(BIGSTRING("\003day"), datv_day);
    ADD_VERB(BIGSTRING("\005month"), datv_month);
    ADD_VERB(BIGSTRING("\004year"), datv_year);
    ADD_VERB(BIGSTRING("\004hour"), datv_hour);
    ADD_VERB(BIGSTRING("\006minute"), datv_minute);
    ADD_VERB(BIGSTRING("\007seconds"), datv_seconds);

    #undef ADD_VERB

    pophashtable();
    return true;
}
