/*
 * headless_point_verbs.c - Point processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the point processor */
enum {
    poiv_get = 0,
    poiv_set = 1
};

static boolean point_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case poiv_get:
            /* Verb #0: point.get - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case poiv_set:
            /* Verb #1: point.set - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean pointinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\ppoint"), bsname);

    if (!newfunctionprocessor(bsname, &point_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pget"), poiv_get);
    ADD_VERB(BIGSTRING("\pset"), poiv_set);

    #undef ADD_VERB

    pophashtable();
    return true;
}
