/*
 * headless_dialog_verbs.c - Dialog processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains Phase 2A interactive dialog prompt implementations.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status (Phase 2A):
 * - dialog.ask(prompt, @adr): COMPLETE - Text input, stores string in @adr
 * - dialog.getInt(prompt, @adr): COMPLETE - Integer input, stores int in @adr
 * - dialog.getString() (via getuserinfo): COMPLETE - String input with default
 * - dialog.getPassword(prompt, @adr): COMPLETE - Password input, stores string in @adr
 *
 * See planning/phase3/HEADLESS_INTERACTIVE_MODE.md for complete roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Include interactive dialog prompt functions */
#include "../frontier-cli/dialog_prompts.h"
#include "../frontier-cli/cli_utils.h"

/* Token enum for all verbs in the dialog processor */
enum {
    diav_alert = 0,
    diav_run = 1,
    diav_runmodeless = 2,
    diav_runcard = 3,
    diav_runmodalcard = 4,
    diav_ismodalcard = 5,
    diav_setmodalcardtimeout = 6,
    diav_getvalue = 7,
    diav_setvalue = 8,
    diav_setitemenable = 9,
    diav_showitem = 10,
    diav_hideitem = 11,
    diav_twoway = 12,
    diav_threeway = 13,
    diav_ask = 14,
    diav_getint = 15,
    diav_notify = 16,
    diav_getuserinfo = 17,
    diav_getpassword = 18
};

static boolean dialog_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case diav_alert: {
            /* dialog.alert(message) - Display message with beep and OK button */
            bigstring bsmessage;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            flnextparamislast = true;
            if (!getstringvalue(hparam1, 1, bsmessage))
                return false;

            /* Convert Pascal string to C string */
            char message[256];
            copyptocstring(bsmessage, message);

            /* Call interactive alert */
            boolean result = dialog_alert(message);

            return setbooleanvalue(result, vreturned);
        }
        case diav_notify: {
            /* dialog.notify(message) - Display message with OK button (no beep) */
            bigstring bsmessage;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            flnextparamislast = true;
            if (!getstringvalue(hparam1, 1, bsmessage))
                return false;

            /* Convert Pascal string to C string */
            char message[256];
            copyptocstring(bsmessage, message);

            /* Call interactive notify */
            boolean result = dialog_notify(message);

            return setbooleanvalue(result, vreturned);
        }
        case diav_twoway: {
            /* dialog.twoway(prompt, button1, button2) - Two-button choice */
            bigstring bsprompt, bsbutton1, bsbutton2;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            /* Get all three parameters */
            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;
            if (!getstringvalue(hparam1, 2, bsbutton1))
                return false;
            flnextparamislast = true;
            if (!getstringvalue(hparam1, 3, bsbutton2))
                return false;

            /* Convert Pascal strings to C strings */
            char prompt[256], button1[256], button2[256];
            copyptocstring(bsprompt, prompt);
            copyptocstring(bsbutton1, button1);
            copyptocstring(bsbutton2, button2);

            /* Call interactive twoway */
            boolean result = dialog_twoway(prompt, button1, button2);

            return setbooleanvalue(result, vreturned);
        }
        case diav_threeway: {
            /* dialog.threeway(prompt, button1, button2, button3) - Three-button choice */
            bigstring bsprompt, bsbutton1, bsbutton2, bsbutton3;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            /* Get all four parameters */
            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;
            if (!getstringvalue(hparam1, 2, bsbutton1))
                return false;
            if (!getstringvalue(hparam1, 3, bsbutton2))
                return false;
            flnextparamislast = true;
            if (!getstringvalue(hparam1, 4, bsbutton3))
                return false;

            /* Convert Pascal strings to C strings */
            char prompt[256], button1[256], button2[256], button3[256];
            copyptocstring(bsprompt, prompt);
            copyptocstring(bsbutton1, button1);
            copyptocstring(bsbutton2, button2);
            copyptocstring(bsbutton3, button3);

            /* Call interactive threeway */
            int result = dialog_threeway(prompt, button1, button2, button3);

            return setlongvalue(result, vreturned);
        }

        /* @PLATFORM_SPECIFIC - Resource-based dialog verbs (Mac OS Classic/Windows only) */
        case diav_run:
            /* dialog.run - @PLATFORM_SPECIFIC (requires DLOG resources from Mac/Windows resource fork) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.run requires GUI resources (Mac/Windows only)"), bserror);
            return false;
        case diav_runmodeless:
            /* dialog.runModeless - @PLATFORM_SPECIFIC (requires DLOG resources) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.runModeless requires GUI resources (Mac/Windows only)"), bserror);
            return false;
        case diav_getvalue:
            /* dialog.getValue - @PLATFORM_SPECIFIC (only works within dialog.run itemhit callback) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.getValue only works in GUI dialog callbacks (Mac/Windows only)"), bserror);
            return false;
        case diav_setvalue:
            /* dialog.setValue - @PLATFORM_SPECIFIC (only works within dialog.run itemhit callback) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.setValue only works in GUI dialog callbacks (Mac/Windows only)"), bserror);
            return false;
        case diav_setitemenable:
            /* dialog.setItemEnable - @PLATFORM_SPECIFIC (only works within dialog.run itemhit callback) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.setItemEnable only works in GUI dialog callbacks (Mac/Windows only)"), bserror);
            return false;
        case diav_showitem:
            /* dialog.showItem - @PLATFORM_SPECIFIC (only works within dialog.run itemhit callback) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.showItem only works in GUI dialog callbacks (Mac/Windows only)"), bserror);
            return false;
        case diav_hideitem:
            /* dialog.hideItem - @PLATFORM_SPECIFIC (only works within dialog.run itemhit callback) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.hideItem only works in GUI dialog callbacks (Mac/Windows only)"), bserror);
            return false;

        /* @IMPLEMENTED - Ghost cruft (card-based dialogs never had UserTalk glue) */
        case diav_runcard:
            /* dialog.runcard - @IMPLEMENTED (ghost cruft, no glue ever existed) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.runcard was never implemented"), bserror);
            return false;
        case diav_runmodalcard:
            /* dialog.runmodalcard - @IMPLEMENTED (ghost cruft, no glue ever existed) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.runmodalcard was never implemented"), bserror);
            return false;
        case diav_ismodalcard:
            /* dialog.ismodalcard - @IMPLEMENTED (ghost cruft, no glue ever existed) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.ismodalcard was never implemented"), bserror);
            return false;
        case diav_setmodalcardtimeout:
            /* dialog.setmodalcardtimeout - @IMPLEMENTED (ghost cruft, no glue ever existed) */
            if (bserror)
                copystring(BIGSTRING("\pdialog.setmodalcardtimeout was never implemented"), bserror);
            return false;
        case diav_ask: {
            /* dialog.ask(prompt, @adr) - Text input dialog with OK/Cancel.
               Pre-populates from adr^ if defined. Stores string in adr^, returns true.
               On cancel, returns false without modifying adr^. */
            bigstring bsprompt;
            hdlhashtable htable;
            bigstring bsvarname;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            flnextparamislast = true;
            if (!getvarparam(hparam1, 2, &htable, bsvarname))
                return false;

            /* Get current value as default (if variable exists) */
            char default_value[256] = {0};
            tyvaluerecord existingval;
            hdlhashnode hnode;
            if (hashtablelookup(htable, bsvarname, &existingval, &hnode)) {
                tyvaluerecord valcopy;
                if (copyvaluerecord(existingval, &valcopy)) {
                    disablelangerror();
                    if (coercetostring(&valcopy)) {
                        Handle h = valcopy.data.stringvalue;
                        long len = gethandlesize(h);
                        if (len > 255) len = 255;
                        memcpy(default_value, *h, len);
                        default_value[len] = '\0';
                    }
                    enablelangerror();
                    disposevaluerecord(valcopy, false);
                }
            }

            /* Convert prompt to C string */
            char prompt[256];
            copyptocstring(bsprompt, prompt);

            /* Call interactive string prompt */
            char *result = dialog_get_string(prompt, default_value);
            if (!result) {
                /* User cancelled */
                setbooleanvalue(false, vreturned);
                return true;
            }

            /* Store result string in variable */
            tyvaluerecord val;
            bigstring bsresult;
            copyctopstring(result, bsresult);
            free(result);

            if (!setstringvalue(bsresult, &val))
                return false;

            pushhashtable(htable);
            boolean fl = langsetsymbolval(bsvarname, val);
            pophashtable();

            if (!fl)
                return false;

            exemptfromtmpstack(&val);

            setbooleanvalue(true, vreturned);
            return true;
        }
        case diav_getint: {
            /* dialog.getInt(prompt, @adr) - Integer input dialog.
               Pre-populates from adr^ if it contains an integer. Stores int in adr^, returns true.
               On cancel, returns false without modifying adr^. */
            bigstring bsprompt;
            hdlhashtable htable;
            bigstring bsvarname;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            flnextparamislast = true;
            if (!getvarparam(hparam1, 2, &htable, bsvarname))
                return false;

            /* Get current value as default (if variable exists and is numeric) */
            long default_value = 0;
            tyvaluerecord existingval;
            hdlhashnode hnode;
            if (hashtablelookup(htable, bsvarname, &existingval, &hnode)) {
                tyvaluerecord valcopy;
                if (copyvaluerecord(existingval, &valcopy)) {
                    disablelangerror();
                    if (coercetolong(&valcopy))
                        default_value = valcopy.data.longvalue;
                    enablelangerror();
                }
            }

            /* Convert prompt to C string */
            char prompt[256];
            copyptocstring(bsprompt, prompt);

            /* Call interactive integer prompt */
            long result = dialog_get_int(prompt, default_value);

            /* Store result in variable */
            tyvaluerecord val;
            if (!setlongvalue(result, &val))
                return false;

            pushhashtable(htable);
            boolean fl = langsetsymbolval(bsvarname, val);
            pophashtable();

            if (!fl)
                return false;

            setbooleanvalue(true, vreturned);
            return true;
        }
        case diav_getuserinfo: {
            /* dialog.getuserinfo(prompt, [default]) - String input (legacy name for getString) */
            bigstring bsprompt, bsdefault;
            boolean has_default = false;

            (void)has_default;  /* Reserved for future default handling */

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            /* Check if second parameter (default) is provided */
            if (langgetparamcount(hparam1) >= 2) {
                if (!getstringvalue(hparam1, 1, bsprompt))
                    return false;
                flnextparamislast = true;
                if (!getstringvalue(hparam1, 2, bsdefault))
                    return false;
                has_default = true;
            } else {
                /* Only one parameter - mark it as last */
                flnextparamislast = true;
                if (!getstringvalue(hparam1, 1, bsprompt))
                    return false;
                /* No default - use empty string */
                setemptystring(bsdefault);
            }

            /* Convert Pascal strings to C strings */
            char prompt[256];
            char default_value[256];
            copyptocstring(bsprompt, prompt);
            copyptocstring(bsdefault, default_value);

            /* Call interactive prompt */
            char *result = dialog_get_string(prompt, default_value);
            if (!result) {
                if (bserror) copystring(BIGSTRING("\pUser cancelled string entry"), bserror);
                return false;
            }

            /* Convert to Frontier string and return */
            bigstring bsresult;
            copyctopstring(result, bsresult);
            free(result);

            return setstringvalue(bsresult, vreturned);
        }
        case diav_getpassword: {
            /* dialog.getPassword(prompt, @adr) - Password input with asterisk masking.
               Stores password string in adr^, returns true.
               On cancel, returns false without modifying adr^. */
            bigstring bsprompt;
            hdlhashtable htable;
            bigstring bsvarname;

            if (!isInteractiveMode()) {
                if (bserror) copystring(BIGSTRING("\pCan't use dialog verbs in batch mode"), bserror);
                return false;
            }

            if (!getstringvalue(hparam1, 1, bsprompt))
                return false;

            flnextparamislast = true;
            if (!getvarparam(hparam1, 2, &htable, bsvarname))
                return false;

            /* Convert prompt to C string */
            char prompt[256];
            copyptocstring(bsprompt, prompt);

            /* Call interactive password prompt */
            char *password = dialog_get_password(prompt);
            if (!password) {
                /* User cancelled */
                setbooleanvalue(false, vreturned);
                return true;
            }

            /* Store result string in variable */
            tyvaluerecord val;
            bigstring bspassword;
            copyctopstring(password, bspassword);
            free(password);

            if (!setstringvalue(bspassword, &val))
                return false;

            pushhashtable(htable);
            boolean fl = langsetsymbolval(bsvarname, val);
            pophashtable();

            if (!fl)
                return false;

            exemptfromtmpstack(&val);

            setbooleanvalue(true, vreturned);
            return true;
        }
        default:
            return false;
    }
}

boolean dialoginitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pdialog"), bsname);

    if (!newfunctionprocessor(bsname, &dialog_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\palert"), diav_alert);
    ADD_VERB(BIGSTRING("\prun"), diav_run);
    ADD_VERB(BIGSTRING("\prunmodeless"), diav_runmodeless);
    ADD_VERB(BIGSTRING("\pruncard"), diav_runcard);
    ADD_VERB(BIGSTRING("\prunmodalcard"), diav_runmodalcard);
    ADD_VERB(BIGSTRING("\pismodalcard"), diav_ismodalcard);
    ADD_VERB(BIGSTRING("\psetmodalcardtimeout"), diav_setmodalcardtimeout);
    ADD_VERB(BIGSTRING("\pgetvalue"), diav_getvalue);
    ADD_VERB(BIGSTRING("\psetvalue"), diav_setvalue);
    ADD_VERB(BIGSTRING("\psetitemenable"), diav_setitemenable);
    ADD_VERB(BIGSTRING("\pshowitem"), diav_showitem);
    ADD_VERB(BIGSTRING("\phideitem"), diav_hideitem);
    ADD_VERB(BIGSTRING("\ptwoway"), diav_twoway);
    ADD_VERB(BIGSTRING("\pthreeway"), diav_threeway);
    ADD_VERB(BIGSTRING("\pask"), diav_ask);
    ADD_VERB(BIGSTRING("\pgetint"), diav_getint);
    ADD_VERB(BIGSTRING("\pnotify"), diav_notify);
    ADD_VERB(BIGSTRING("\pgetuserinfo"), diav_getuserinfo);
    ADD_VERB(BIGSTRING("\pgetpassword"), diav_getpassword);

    #undef ADD_VERB

    pophashtable();
    return true;
}
