/*
 * headless_searchengine_verbs.c - Searchengine processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains forwarding implementations for Phase 2 searchengine verbs.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status:
 * - Phase 2 (1 verb): COMPLETE - stripmarkup
 * - Phase 3+ (4 verbs): PENDING - deindexpage, indexpage, cleanindex, mergeresults
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "langhtml.h"

/* Token enum for all verbs in the searchengine processor */
enum {
    seav_stripmarkup = 0,
    seav_deindexpage = 1,
    seav_indexpage = 2,
    seav_cleanindex = 3,
    seav_mergeresults = 4
};

static boolean searchengine_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case seav_stripmarkup:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return stripmarkupverb(hparam1, vreturned);
        case seav_deindexpage:
            /* Verb #1: searchengine.deindexpage - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case seav_indexpage:
            /* Verb #2: searchengine.indexpage - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case seav_cleanindex:
            /* Verb #3: searchengine.cleanindex - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case seav_mergeresults:
            /* Verb #4: searchengine.mergeresults - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean searchengineinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\014", "searchengine"), bsname);

    if (!newfunctionprocessor(bsname, &searchengine_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\013", "stripmarkup"), seav_stripmarkup);
    ADD_VERB(PSTRING("\013", "deindexpage"), seav_deindexpage);
    ADD_VERB(PSTRING("\011", "indexpage"), seav_indexpage);
    ADD_VERB(PSTRING("\012", "cleanindex"), seav_cleanindex);
    ADD_VERB(PSTRING("\014", "mergeresults"), seav_mergeresults);

    #undef ADD_VERB

    pophashtable();
    return true;
}
