/*
 * headless_base64_verbs.c - Base64 processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains hand-written implementations.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status:
 * - base64.encode: COMPLETE - Encodes binary data to base64 string
 * - base64.decode: COMPLETE - Decodes base64 string to binary data
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "BASE64.H"

/* Token enum for all verbs in the base64 processor */
enum {
    basv_encode = 0,
    basv_decode = 1
};

/* @IMPLEMENTED base64.encode - Encode binary data to base64 string
 * Parameters:
 *   1. data (string/binary) - Data to encode
 *   2. linelength (int) - Line length for wrapping (0 = no wrapping)
 * Returns: base64-encoded string
 *
 * @IMPLEMENTED base64.decode - Decode base64 string to binary data
 * Parameters:
 *   1. encoded (string) - Base64-encoded string to decode
 * Returns: Decoded binary data as string
 */
static boolean base64_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    boolean result;

    switch(token) {
        case basv_encode:
            /* @IMPLEMENTED base64.encode - delegates to base64encodeverb in base64.c */
            result = base64encodeverb(hparam1, vreturned);
            if (!result && bserror) {
                copystring(PSTRING("\024", "base64.encode failed"), bserror);
            }
            return result;

        case basv_decode:
            /* @IMPLEMENTED base64.decode - delegates to base64decodeverb in base64.c */
            result = base64decodeverb(hparam1, vreturned);
            if (!result && bserror) {
                copystring(PSTRING("\024", "base64.decode failed"), bserror);
            }
            return result;

        default:
            if (bserror) copystring(PSTRING("\023", "unknown base64 verb"), bserror);
            return false;
    }
}

boolean base64initverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\006", "base64"), bsname);

    if (!newfunctionprocessor(bsname, &base64_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\006", "encode"), basv_encode);
    ADD_VERB(PSTRING("\006", "decode"), basv_decode);

    #undef ADD_VERB

    pophashtable();
    return true;
}
