/*
 * headless_filemenu_verbs.c - Filemenu processor verbs for headless mode
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * but now contains real implementations for critical verbs.
 *
 * Implemented:
 *   - fileMenu.open(path, hidden=false) - Opens guest database, mounts into system.compiler.files
 *   - fileMenu.close() - Closes current target guest database
 *   - fileMenu.closeall() - Closes all guest databases
 *   - fileMenu.save([f]) - Saves system root or guest database
 *
 * Stub implementations (return "not implemented"):
 *   - fileMenu.new, savecopy, revert, print, quit, saveas
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "db.h"
#include "file.h"
#include "logging.h"
#include "odbinternal.h"
#include "db_format.h"
#include "cancoon.h"
#include "ops.h"

/* ODB list structure and global from dbverbs.c - for guest database lookup.
 * MUST use #pragma pack(2) to match dbverbs.c layout, otherwise odb field
 * offset differs and db.setvalue/getvalue dereferences a corrupted handle. */
#pragma pack(2)
typedef struct tyodblistrecord {
    struct tyodblistrecord **hnext;
    tyfilespec fs;
    hdlfilenum fref;
    boolean flreadonly;
    odbref odb;
} tyodbrecord_local, *ptrodbrecord_local, **hdlodbrecord_local;
#pragma options align=reset

extern hdlodbrecord_local hodblist;

/* From tablestructure.c - the system.compiler.files table */
extern hdlhashtable filewindowtable;

/* Token enum for all verbs in the filemenu processor */
enum {
    filv_new = 0,
    filv_open = 1,
    filv_close = 2,
    filv_closeall = 3,
    filv_save = 4,
    filv_savecopy = 5,
    filv_revert = 6,
    filv_print = 7,
    filv_quit = 8,
    filv_saveas = 9
};

/*
 * filemenu_save_systemroot - Save the system root database to disk
 *
 * Saves all dirty (modified) objects in the system root database (Frontier.root)
 * to disk. This is the headless equivalent of File > Save in the GUI.
 *
 * Thread Safety: Not thread-safe. Should only be called from the main thread
 * or with appropriate synchronization.
 *
 * Prerequisites:
 *   - Database must be open (databasedata != nil)
 *   - Root variable must exist (rootvariable != nil) for non-empty saves
 *
 * Side Effects:
 *   - Calls dbclose() to flush buffers to disk
 *   - Updates views[0] with new root table address
 *   - Database remains open and usable after save
 *
 * Note: Safe to call during normal operation. Do NOT call during v6->v7 migration
 * as the database state may be incomplete.
 *
 * Returns: true on success, false on failure (with error logged)
 */
static boolean filemenu_save_systemroot(void) {
    dbaddress root_adr;
    db_context ctx;

    log_debug(LOG_COMP_DB, "filemenu_save_systemroot: saving system root database");

    /* Check if we have a database open */
    if (databasedata == nil) {
        log_error(LOG_COMP_DB, "filemenu_save_systemroot: no database open");
        return false;
    }

    /* Check if we have a root variable to save */
    if (rootvariable == nil) {
        log_debug(LOG_COMP_DB, "filemenu_save_systemroot: database is empty, nothing to save");
        return true;  /* Empty database is technically saved */
    }

    /* Save the root table using v7 format */
    {
        boolean repack_scope = false;
        db_format_mode mode = {true, false, false};  /* 64-bit, no adapter_repack, no drop_cancoon */
        db_format_mode_push(&mode);
        repack_scope = true;

        if (!tablesavesystemtable(rootvariable, &root_adr)) {
            if (repack_scope) {
                db_format_mode_pop();
            }
            log_error(LOG_COMP_DB, "filemenu_save_systemroot: tablesavesystemtable failed");
            return false;
        }

        if (repack_scope) {
            db_format_mode_pop();
        }
    }

    /* Flush release stack */
    db_context_init(&ctx);
    dbflushreleasestack_context(&ctx);

    /* Update views[0] to point to the saved root table */
    dbsetview(cancoonview, root_adr);

    /* Flush to disk - required for changes to persist */
    if (!dbclose()) {
        log_error(LOG_COMP_DB, "filemenu_save_systemroot: dbclose failed");
        langerrormessage(BIGSTRING("\x1b" "Can't save: disk flush failed"));
        return false;
    }

    log_debug(LOG_COMP_DB, "filemenu_save_systemroot: saved and flushed, views[0] = 0x%llx",
              (unsigned long long)root_adr);

    return true;
}

/*
 * filemenu_save_guestdb - Save a guest database by file path
 *
 * Looks up a guest database in the global hodblist by its file path and saves
 * all dirty objects to disk. Guest databases are any databases opened via
 * fileMenu.open() other than the system root.
 *
 * Thread Safety: Not thread-safe. Should only be called from the main thread.
 *
 * Parameters:
 *   hparam1 - Tree node containing the file path parameter (bigstring)
 *
 * Algorithm:
 *   1. Extract file path from parameter
 *   2. Search hodblist for matching database (O(n) linear search)
 *   3. If found, call odbSaveFile() to save
 *   4. If not found, return error
 *
 * Note: The linear search is acceptable since guest database lists are typically
 * small (< 10 databases in normal use).
 *
 * Returns: true on success, false on failure (with error message set)
 */
static boolean filemenu_save_guestdb(hdltreenode hparam1) {
    tyfilespec fs;
    hdlodbrecord_local hodb;
    bigstring bspath;

    /* Get the file path parameter */
    flnextparamislast = true;
    if (!getfilespecvalue(hparam1, 1, &fs)) {
        log_error(LOG_COMP_DB, "filemenu_save_guestdb: failed to get file path parameter");
        return false;
    }

    filespectopath(&fs, bspath);
    log_debug(LOG_COMP_DB, "filemenu_save_guestdb: looking for database at path=%s",
              stringbaseaddress(bspath));

    /* Search hodblist for the database (skip sentinel at hodblist itself) */
    if (hodblist == nil) {
        log_error(LOG_COMP_DB, "filemenu_save_guestdb: hodblist not initialized");
        langerrormessage(BIGSTRING("\pdb: no databases are open"));
        return false;
    }

    for (hodb = (**hodblist).hnext; hodb != nil && hodb != hodblist; hodb = (**hodb).hnext) {
        /* Defensive: skip nil or corrupted entries in the list */
        if (*hodb == nil) {
            log_warn(LOG_COMP_DB, "filemenu_save_guestdb: found nil entry in hodblist");
            continue;
        }
        if (equalfilespecs(&(**hodb).fs, &fs)) {
            /* Found it - check if read-only */
            if ((**hodb).flreadonly) {
                log_error(LOG_COMP_DB, "filemenu_save_guestdb: database is read-only");
                langerrormessage(BIGSTRING("\pCan't save: database is read-only"));
                return false;
            }

            /* Save the database — guard globals since odbSaveFile calls
             * setcancoonglobals which overwrites currenthashtable et al. */
            {
                odb_context_guard guard;
                boolean fl;

                log_debug(LOG_COMP_DB, "filemenu_save_guestdb: saving database");
                odb_guard_enter(&guard);
                fl = odbSaveFile((**hodb).odb);
                odb_guard_exit(&guard);

                if (!fl) {
                    log_error(LOG_COMP_DB, "filemenu_save_guestdb: odbSaveFile failed");
                    return false;
                }
            }

            log_debug(LOG_COMP_DB, "filemenu_save_guestdb: saved successfully");
            return true;
        }
    }

    /* Database not found in open list */
    log_error(LOG_COMP_DB, "filemenu_save_guestdb: database not found in open list");
    lang2paramerror(dbnotopenederror, BIGSTRING("\x0dfileMenu.save"), bspath);
    return false;
}

/*
 * filemenu_open - Open a guest database and mount into system.compiler.files
 *
 * This is the headless equivalent of File > Open in the GUI. It:
 *   1. Opens the ODB file (openfile + odbopenfile)
 *   2. Adds to hodblist (for db.* verb access)
 *   3. Mounts the root table into system.compiler.files (for bracket syntax access)
 *
 * Parameters:
 *   hparam1 - Tree node: param 1 = file path, param 2 = hidden (optional, ignored)
 *
 * Returns: true on success, false on failure
 */
static boolean filemenu_open(hdltreenode hparam1, tyvaluerecord *vreturned) {
    tyodbrecord_local odbrec;
    hdlodbrecord_local hodb;
    bigstring bspath;
    short ctparams;
    boolean flhidden = false;

    setbooleanvalue(false, vreturned);

    odbrec.fref = 0;
    odbrec.flreadonly = false;

    ctparams = langgetparamcount(hparam1);

    /* Get the file path (param 1) */
    if (ctparams == 1)
        flnextparamislast = true;

    if (!getfilespecvalue(hparam1, 1, &odbrec.fs)) {
        log_error(LOG_COMP_DB, "filemenu_open: getfilespecvalue failed");
        return false;
    }

    /* Consume optional 'hidden' param (ignored in headless mode) */
    if (ctparams > 1) {
        flnextparamislast = true;

        if (!getbooleanvalue(hparam1, 2, &flhidden))
            return false;
    }

    filespectopath(&odbrec.fs, bspath);
    log_debug(LOG_COMP_DB, "filemenu_open: opening %s", stringbaseaddress(bspath));

    /* Check if already open in hodblist */
    if (hodblist != nil) {
        hdlodbrecord_local h;
        for (h = (**hodblist).hnext; h != nil; h = (**h).hnext) {
            if (equalfilespecs(&(**h).fs, &odbrec.fs)) {
                log_debug(LOG_COMP_DB, "filemenu_open: database already open");
                return setbooleanvalue(true, vreturned);
            }
        }
    }

    /* Open the OS file */
    if (!openfile(&odbrec.fs, &odbrec.fref, odbrec.flreadonly)) {
        log_error(LOG_COMP_DB, "filemenu_open: openfile failed for %s", stringbaseaddress(bspath));
        langerrormessage(BIGSTRING("\x1e" "Can't open: file does not exist"));
        return false;
    }

    /* Open the ODB — use context guard to save/restore system root globals */
    {
        odb_context_guard guard;

        odb_guard_enter(&guard);

        if (!odbOpenFile(odbrec.fref, &odbrec.odb, odbrec.flreadonly)) {
            odb_guard_exit(&guard);
            log_error(LOG_COMP_DB, "filemenu_open: odbOpenFile failed");
            closefile(odbrec.fref);
            langerrormessage(BIGSTRING("\x22" "Can't open: invalid database file"));
            return false;
        }

        cancoonglobals = nil;
        odb_guard_exit(&guard);
    }

    log_debug(LOG_COMP_DB, "filemenu_open: odbOpenFile succeeded, odb=%p", odbrec.odb);

    /* Create handle for the odb record and add to hodblist */
    if (!newfilledhandle(&odbrec, sizeof(odbrec), (Handle *) &hodb)) {
        odb_context_guard guard;
        log_error(LOG_COMP_DB, "filemenu_open: newfilledhandle failed");
        odb_guard_enter(&guard);
        odbCloseFile(odbrec.odb);
        cancoonglobals = nil;
        odb_guard_exit(&guard);
        closefile(odbrec.fref);
        return false;
    }

    /* Add to hodblist after sentinel */
    if ((**hodblist).hnext == nil) {
        (**hodblist).hnext = hodb;
        (**hodb).hnext = nil;
    }
    else {
        listlink((hdllinkedlist) (**hodblist).hnext, (hdllinkedlist) hodb);
    }

    /* Mount into system.compiler.files for bracket syntax access */
    if (filewindowtable != nil) {
        hdlcancoonrecord hc = (hdlcancoonrecord) odbrec.odb;
        Handle hrootvar = (**hc).hrootvariable;

        if (hrootvar != nil) {
            tyvaluerecord val;

            setexternalvalue(hrootvar, &val);

            if (!hashtableassign(filewindowtable, bspath, val)) {
                log_warn(LOG_COMP_DB, "filemenu_open: failed to mount in system.compiler.files");
                /* Non-fatal: database is still open in hodblist */
            }
            else {
                log_debug(LOG_COMP_DB, "filemenu_open: mounted in system.compiler.files as '%s'",
                          stringbaseaddress(bspath));
            }
        }
    }

    return setbooleanvalue(true, vreturned);
}


/*
 * filemenu_close_guestdb - Close a specific guest database by its hodblist handle
 *
 * Closes the ODB file, removes from hodblist, and unmounts from system.compiler.files.
 *
 * Parameters:
 *   hodb - Handle to the odb record in hodblist
 *
 * Returns: true on success
 */
static boolean filemenu_close_guestdb(hdlodbrecord_local hodb) {
    bigstring bspath;

    filespectopath(&(**hodb).fs, bspath);
    log_debug(LOG_COMP_DB, "filemenu_close_guestdb: closing %s", stringbaseaddress(bspath));

    /* Remove from system.compiler.files first (before handle is disposed) */
    if (filewindowtable != nil) {
        pushhashtable(filewindowtable);
        hashdelete(bspath, false, false);
        pophashtable();
    }

    /* Close the ODB file — use context guard to protect system root globals */
    {
        odb_context_guard guard;

        odb_guard_enter(&guard);

        if (!odbCloseFile((**hodb).odb)) {
            cancoonglobals = nil;
            odb_guard_exit(&guard);
            log_error(LOG_COMP_DB, "filemenu_close_guestdb: odbCloseFile failed");
            return false;
        }

        cancoonglobals = nil;
        odb_guard_exit(&guard);
    }

    /* Close the OS file */
    closefile((**hodb).fref);

    /* Unlink from hodblist and dispose */
    listunlink((hdllinkedlist) hodblist, (hdllinkedlist) hodb);
    disposehandle((Handle) hodb);

    return true;
}


/*
 * filemenu_close - Close the current target guest database
 *
 * In headless mode, operates on the current target (set via target.set).
 * If no target is set, or target is not a guest database root table, no-op.
 *
 * Returns: true on success (including no-op cases)
 */
static boolean filemenu_close(tyvaluerecord *vreturned) {
    hdlhashtable htargettable;
    bigstring bstargetname;
    hdlodbrecord_local hodb;

    setbooleanvalue(true, vreturned);

    /* Get current target */
    if (!langgettarget(&htargettable, bstargetname)) {
        log_debug(LOG_COMP_DB, "filemenu_close: no target set, no-op");
        return true;  /* No target set - nothing to close */
    }

    log_debug(LOG_COMP_DB, "filemenu_close: target='%s'", stringbaseaddress(bstargetname));

    /* Check if target is in system.compiler.files (i.e., it's a guest database) */
    if (filewindowtable == nil || htargettable != filewindowtable) {
        log_debug(LOG_COMP_DB, "filemenu_close: target is not a guest database, no-op");
        return true;
    }

    /* Target name is the file path - find it in hodblist */
    if (hodblist == nil)
        return true;

    for (hodb = (**hodblist).hnext; hodb != nil; hodb = (**hodb).hnext) {
        bigstring bsodbpath;
        filespectopath(&(**hodb).fs, bsodbpath);

        if (equalstrings(bstargetname, bsodbpath)) {
            return filemenu_close_guestdb(hodb) ? true : false;
        }
    }

    log_debug(LOG_COMP_DB, "filemenu_close: target not found in hodblist, no-op");
    return true;
}


/*
 * filemenu_closeall - Close all guest databases
 *
 * Walks hodblist and closes each guest database, removing them from
 * system.compiler.files as well.
 *
 * Returns: true on success
 */
static boolean filemenu_closeall(tyvaluerecord *vreturned) {
    hdlodbrecord_local hodb, hnext;

    setbooleanvalue(true, vreturned);

    if (hodblist == nil)
        return true;

    log_debug(LOG_COMP_DB, "filemenu_closeall: closing all guest databases");

    /* Walk the list, closing each database */
    hodb = (**hodblist).hnext;

    while (hodb != nil) {
        hnext = (**hodb).hnext;  /* Save next before we dispose current */

        if (!filemenu_close_guestdb(hodb)) {
            log_error(LOG_COMP_DB, "filemenu_closeall: failed to close a database");
            /* Continue closing others */
        }

        hodb = hnext;
    }

    log_debug(LOG_COMP_DB, "filemenu_closeall: done");
    return true;
}


static boolean filemenu_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;
    switch(token) {
        case filv_new:
            /* Verb #0: filemenu.new - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;

        case filv_open:
            return filemenu_open(hparam1, vreturned);

        case filv_close:
            return filemenu_close(vreturned);

        case filv_closeall:
            return filemenu_closeall(vreturned);

        case filv_save:
            /*
             * fileMenu.save([f])
             *
             * If called with no params: saves the system root database
             * If called with a path: saves the guest database at that path
             *
             * Returns: true on success
             */
            {
                boolean fl;

                /* Check if we have parameters */
                if (langgetparamcount(hparam1) == 0) {
                    /* No params - save system root */
                    fl = filemenu_save_systemroot();
                } else {
                    /* Path param - save guest database */
                    fl = filemenu_save_guestdb(hparam1);
                }

                if (!fl) {
                    return false;
                }

                return setbooleanvalue(true, vreturned);
            }

        case filv_savecopy:
            /* Verb #5: filemenu.savecopy - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_revert:
            /* Verb #6: filemenu.revert - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_print:
            /* Verb #7: filemenu.print - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_quit:
            /* Verb #8: filemenu.quit - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        case filv_saveas:
            /* Verb #9: filemenu.saveas - not yet implemented */
            langerrormessage(BIGSTRING("\x0fnot implemented"));
            return false;
        default:
            return false;
    }
}

boolean filemenuinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pfilemenu"), bsname);

    if (!newfunctionprocessor(bsname, &filemenu_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pnew"), filv_new);
    ADD_VERB(BIGSTRING("\popen"), filv_open);
    ADD_VERB(BIGSTRING("\pclose"), filv_close);
    ADD_VERB(BIGSTRING("\pcloseall"), filv_closeall);
    ADD_VERB(BIGSTRING("\psave"), filv_save);
    ADD_VERB(BIGSTRING("\psavecopy"), filv_savecopy);
    ADD_VERB(BIGSTRING("\prevert"), filv_revert);
    ADD_VERB(BIGSTRING("\pprint"), filv_print);
    ADD_VERB(BIGSTRING("\pquit"), filv_quit);
    ADD_VERB(BIGSTRING("\psaveas"), filv_saveas);

    #undef ADD_VERB

    pophashtable();
    return true;
}
