/*
 * headless_statusbar_verbs.c - Statusbar processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the statusbar processor */
enum {
    stav_msg = 0,
    stav_setsections = 1,
    stav_getsections = 2,
    stav_getsectionone = 3,
    stav_getmessage = 4
};

static boolean statusbar_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)hparam1;
    (void)vreturned;
    switch(token) {
        case stav_msg:
            /* statusbar.msg - error stub */
            if (bserror)
                copystring(PSTRING("\110", "Can't use status bar verbs because GUI is not available in headless mode"), bserror);
            return false;
        case stav_setsections:
            /* statusbar.setsections - error stub */
            if (bserror)
                copystring(PSTRING("\110", "Can't use status bar verbs because GUI is not available in headless mode"), bserror);
            return false;
        case stav_getsections:
            /* statusbar.getsections - error stub */
            if (bserror)
                copystring(PSTRING("\110", "Can't use status bar verbs because GUI is not available in headless mode"), bserror);
            return false;
        case stav_getsectionone:
            /* statusbar.getsectionone - error stub */
            if (bserror)
                copystring(PSTRING("\110", "Can't use status bar verbs because GUI is not available in headless mode"), bserror);
            return false;
        case stav_getmessage:
            /* statusbar.getmessage - error stub */
            if (bserror)
                copystring(PSTRING("\110", "Can't use status bar verbs because GUI is not available in headless mode"), bserror);
            return false;
        default:
            return false;
    }
}

boolean statusbarinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\011", "statusbar"), bsname);

    if (!newfunctionprocessor(bsname, &statusbar_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\003", "msg"), stav_msg);
    ADD_VERB(PSTRING("\013", "setsections"), stav_setsections);
    ADD_VERB(PSTRING("\013", "getsections"), stav_getsections);
    ADD_VERB(PSTRING("\015", "getsectionone"), stav_getsectionone);
    ADD_VERB(PSTRING("\012", "getmessage"), stav_getmessage);

    #undef ADD_VERB

    pophashtable();
    return true;
}
