/*
 * headless_menu_verbs.c - Menu processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the menu processor */
enum {
    menv_zoomscript = 0,
    menv_buildmenubar = 1,
    menv_clearmenubar = 2,
    menv_isinstalled = 3,
    menv_install = 4,
    menv_remove = 5,
    menv_getscript = 6,
    menv_setscript = 7,
    menv_addmenucommand = 8,
    menv_deletemenucommand = 9,
    menv_addsubmenu = 10,
    menv_deletesubmenu = 11,
    menv_getcommandkey = 12,
    menv_setcommandkey = 13
};

static boolean menu_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)hparam1;
    (void)vreturned;
    switch(token) {
        case menv_zoomscript:
            /* Verb #0: menu.zoomscript - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_buildmenubar:
            /* menu.buildmenubar - no-op in headless mode (no GUI menubar) */
            setbooleanvalue(true, vreturned);
            return true;
        case menv_clearmenubar:
            /* menu.clearMenuBar - no-op in headless mode (no GUI menubar) */
            setbooleanvalue(true, vreturned);
            return true;
        case menv_isinstalled: {
            /* menu.isInstalled - in headless mode, no menus are installed.
             * Return false to indicate the menu is not installed. */
            hdlhashtable htable;
            bigstring bs;

            flnextparamislast = true;

            /* Consume the address parameter */
            if (!getvarparam(hparam1, 1, &htable, bs))
                return false;

            /* Nothing is installed in headless mode */
            setbooleanvalue(false, vreturned);
            return true;
        }
        case menv_install:
            /* menu.install - no-op in headless mode (no menu bar to install to) */
            return setbooleanvalue(true, vreturned);
        case menv_remove:
            /* Verb #5: menu.remove - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_getscript:
            /* Verb #6: menu.getscript - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_setscript:
            /* Verb #7: menu.setscript - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_addmenucommand:
            /* Verb #8: menu.addmenucommand - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_deletemenucommand:
            /* Verb #9: menu.deletemenucommand - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_addsubmenu:
            /* Verb #10: menu.addsubmenu - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_deletesubmenu:
            /* Verb #11: menu.deletesubmenu - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_getcommandkey:
            /* Verb #12: menu.getcommandkey - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case menv_setcommandkey:
            /* Verb #13: menu.setcommandkey - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean menuinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pmenu"), bsname);

    if (!newfunctionprocessor(bsname, &menu_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pzoomscript"), menv_zoomscript);
    ADD_VERB(BIGSTRING("\pbuildmenubar"), menv_buildmenubar);
    ADD_VERB(BIGSTRING("\pclearmenubar"), menv_clearmenubar);
    ADD_VERB(BIGSTRING("\pisinstalled"), menv_isinstalled);
    ADD_VERB(BIGSTRING("\pinstall"), menv_install);
    ADD_VERB(BIGSTRING("\premove"), menv_remove);
    ADD_VERB(BIGSTRING("\pgetscript"), menv_getscript);
    ADD_VERB(BIGSTRING("\psetscript"), menv_setscript);
    ADD_VERB(BIGSTRING("\paddmenucommand"), menv_addmenucommand);
    ADD_VERB(BIGSTRING("\pdeletemenucommand"), menv_deletemenucommand);
    ADD_VERB(BIGSTRING("\paddsubmenu"), menv_addsubmenu);
    ADD_VERB(BIGSTRING("\pdeletesubmenu"), menv_deletesubmenu);
    ADD_VERB(BIGSTRING("\pgetcommandkey"), menv_getcommandkey);
    ADD_VERB(BIGSTRING("\psetcommandkey"), menv_setcommandkey);

    #undef ADD_VERB

    pophashtable();
    return true;
}
