/*
 * headless_rectangle_verbs.c - Rectangle processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains hand-written implementations.
 *
 * Implementation status:
 * - rectangle.get: COMPLETE - Extracts coordinates from rectangle value
 * - rectangle.set: COMPLETE - Creates rectangle value from coordinates
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the rectangle processor */
enum {
    recv_get = 0,
    recv_set = 1
};

static boolean rectangle_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case recv_get: {
            /* @IMPLEMENTED rectangle.get (rect, @top, @left, @bottom, @right)
             * Extracts the four coordinate values from a rectangle into variables
             */
            Rect r;

            if (!langcheckparamcount(hparam1, 5))
                return false;

            if (!getrectvalue(hparam1, 1, &r))
                return false;

            if (!setintvarparam(hparam1, 2, (short)r.top))
                return false;

            if (!setintvarparam(hparam1, 3, (short)r.left))
                return false;

            if (!setintvarparam(hparam1, 4, (short)r.bottom))
                return false;

            flnextparamislast = true;

            if (!setintvarparam(hparam1, 5, (short)r.right))
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case recv_set: {
            /* @IMPLEMENTED rectangle.set (top, left, bottom, right)
             * Creates a rectangle from four coordinate values
             */
            Rect r;
            diskrect dr;

            if (!getintvalue(hparam1, 1, &dr.top))
                return false;

            if (!getintvalue(hparam1, 2, &dr.left))
                return false;

            if (!getintvalue(hparam1, 3, &dr.bottom))
                return false;

            flnextparamislast = true;

            if (!getintvalue(hparam1, 4, &dr.right))
                return false;

            /* Convert diskrect to Rect (no byte swapping needed) */
            r.top = dr.top;
            r.bottom = dr.bottom;
            r.left = dr.left;
            r.right = dr.right;

            return newheapvalue(&r, sizeof(r), rectvaluetype, vreturned);
        }

        default:
            return false;
    }
}

boolean rectangleinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\prectangle"), bsname);

    if (!newfunctionprocessor(bsname, &rectangle_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pget"), recv_get);
    ADD_VERB(BIGSTRING("\pset"), recv_set);

    #undef ADD_VERB

    pophashtable();
    return true;
}
