/*
 * headless_op_verbs.c - Op processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains hand-written implementations for Phase 1-4 op verbs.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status:
 * - Phase 1 (10 verbs): COMPLETE - insert, getLineText, level, go, firstSummit,
 *                                   countSubs, countSummits, expand, collapse
 * - Phase 2 (8 verbs):  COMPLETE - setLineText, promote, demote, deleteLine, etc.
 * - Phase 3 (10 verbs): COMPLETE - getDisplay, setDisplay, getCursor, setCursor,
 *                                   getRefcon, setRefcon, getExpansionState,
 *                                   setExpansionState, getScrollState, setScrollState
 * - Phase 4 (8 verbs):  COMPLETE - All verbs implemented for headless mode
 *
 * Phase 4 Headless Adaptations:
 * - op.hoist/dehoist:     GUI-only operations, return error in headless mode
 * - op.subsexpanded:      Implemented using opsubheadsexpanded()
 * - op.find:              Headless search - moves cursor to matching headline
 * - op.sort:              Implemented using opsortlevel()
 * - op.visitall:          Headless iteration with callback script support
 * - op.flatcursorkeys:    Noop (keyboard preference, N/A in headless)
 * - op.tabkeyreorg:       Noop (keyboard preference, N/A in headless)
 *
 * See planning/phase3/op_verb_implementation_plan.md for complete roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "langsystem7.h"
#include "tablestructure.h"
#include "langexternal.h"
#include "op.h"
#include "opverbs.h"
#include "opinternal.h"
#include "search.h"
#include "logging.h"

/*
 * Helper function: Set error message from C string
 *
 * Converts a C string to Pascal string format and copies to bserror.
 * This ensures consistency - the length prefix is automatically calculated
 * from the string length, preventing manual octal prefix errors.
 *
 * Handles NULL bserror gracefully (some callers may not want error messages).
 */
static void seterrorstring(const char *msg, bigstring bserror) {
    if (bserror == NULL)
        return;
    copyctopstring(msg, bserror);
}

/*
 * Helper function: Get outline from target system (headless mode)
 *
 * In GUI mode, op verbs get the outline from the frontmost window.
 * In headless mode, we get it from the target.get() system.
 *
 * Returns: true if outline was successfully retrieved, false otherwise
 * On error, bserror contains a Pascal string with the error message
 */
static boolean getoutlinefromtarget(hdloutlinerecord *ho, bigstring bserror) {
    hdlhashtable htable;
    bigstring bsname;
    tyvaluerecord val;
    hdlhashnode hnode;
    hdlexternalvariable hv;

    /* Get target from lang.target.get() */
    if (!langgettarget(&htable, bsname)) {
        seterrorstring("no outline target set", bserror);
        return false;
    }

    /* Look up the variable */
    if (!hashtablelookup(htable, bsname, &val, &hnode)) {
        seterrorstring("target variable not found", bserror);
        return false;
    }

    /* Check if it's a table (not an outline) */
    if (langexternalvaltotable(val, &htable, hnode)) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Verify it's an external variable type */
    if (val.valuetype != externalvaluetype) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Get the external variable handle */
    hv = (hdlexternalvariable)val.data.externalvalue;

    /* Verify handle is valid */
    if (hv == NULL) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Verify it's an outline processor type */
    if ((**hv).id != idoutlineprocessor) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    /* Ensure outline is in memory */
    if (!opverbinmemory(NULL, hv)) {
        seterrorstring("could not load outline", bserror);
        return false;
    }

    /* Get the outline record */
    if ((**hv).variabledata == NULL) {
        seterrorstring("target is not an outline", bserror);
        return false;
    }

    *ho = (hdloutlinerecord)(**hv).variabledata;
    return true;
}

/*
 * Callback for op.visitall() - invoked for each node in outline
 *
 * This is called by opvisiteverything() for each headline in the outline.
 * It runs the callback script with the cursor positioned at the current node.
 *
 * Pattern: Based on opvisitallvisit() from Common/source/opverbs.c
 */
typedef struct {
    bigstring scriptname;
    hdloutlinerecord houtline;
} opvisitall_context;

static boolean opvisitall_callback(hdlheadrecord hnode, ptrvoid refcon) {
    opvisitall_context *ctx = (opvisitall_context *)refcon;
    tyvaluerecord vreturned;

    /* Push outline context for this callback */
    oppushoutline(ctx->houtline);

    /* Set cursor to current node */
    (**ctx->houtline).hbarcursor = hnode;

    /* Call the callback script */
    if (!langrunscript(ctx->scriptname, NULL, NULL, &vreturned)) {
        /* Log callback failure to help with debugging */
        log_warn(LOG_COMP_OP, "op.visitall callback script failed: %s", stringbaseaddress(ctx->scriptname));
        oppopoutline();
        return false;
    }

    oppopoutline();
    return true;
}

/* Token enum for all verbs in the op processor */
enum {
    opv_getlinetext = 0,
    opv_level = 1,
    opv_countsubs = 2,
    opv_countsummits = 3,
    opv_go = 4,
    opv_firstsummit = 5,
    opv_expand = 6,
    opv_collapse = 7,
    opv_subsexpanded = 8,
    opv_insert = 9,
    opv_find = 10,
    opv_sort = 11,
    opv_setlinetext = 12,
    opv_reorg = 13,
    opv_promote = 14,
    opv_demote = 15,
    opv_hoist = 16,
    opv_dehoist = 17,
    opv_deletesubs = 18,
    opv_deleteline = 19,
    opv_tabkeyreorg = 20,
    opv_flatcursorkeys = 21,
    opv_getdisplay = 22,
    opv_setdisplay = 23,
    opv_getcursor = 24,
    opv_setcursor = 25,
    opv_getrefcon = 26,
    opv_setrefcon = 27,
    opv_getexpansionstate = 28,
    opv_setexpansionstate = 29,
    opv_getscrollstate = 30,
    opv_setscrollstate = 31,
    opv_getsuboutline = 32,
    opv_insertoutline = 33,
    opv_setmodified = 34,
    opv_getselection = 35,
    opv_getheadnumber = 36,
    opv_visitall = 37,
    opv_getselectedsuboutlines = 38,
    opv_xmltooutline = 39,
    opv_outlinetoxml = 40,
    opv_sethtmlformatting = 41,
    opv_gethtmlformatting = 42,
    opv_setdynamic = 43,
    opv_getdynamic = 44
};

static boolean op_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case opv_getlinetext: {
            /* op.getLineText() - Get text of current headline */
            Handle htext;
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);

            /* If headline is being edited, update text handle */
            opwriteeditbuffer();

            hbarcursor = (**ho).hbarcursor;

            if (!copyhandle((**hbarcursor).headstring, &htext)) {
                oppopoutline();
                return false;
            }

            oppopoutline();

            return setheapvalue(htext, stringvaluetype, vreturned);
        }
        case opv_level: {
            /* op.level() - Get nesting level of current headline */
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            short level;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            level = (**hbarcursor).headlevel + 1;  /* Convert 0-based to 1-based */
            oppopoutline();

            return setlongvalue(level, vreturned);
        }
        case opv_countsubs: {
            /* op.countSubs(levels) -> long - Count sub-headlines */
            long levellong;
            short level;
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            long ct;

            flnextparamislast = true;  /* Single parameter - mark as last */
            if (!getlongvalue(hparam1, 1, &levellong))
                return false;

            /* Clamp to short range (opcountsubheads expects short) */
            if (levellong > 32767)
                level = 32767;  /* Max short value - effectively infinity */
            else if (levellong < -32768)
                level = -32768;
            else
                level = (short)levellong;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            ct = opcountsubheads(hbarcursor, level);
            oppopoutline();

            return setlongvalue(ct, vreturned);
        }
        case opv_countsummits: {
            /* op.countSummits() - Count top-level headlines */
            hdloutlinerecord ho;
            long ct;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);
            ct = opcountatlevel((**ho).hsummit);
            oppopoutline();

            return setlongvalue(ct, vreturned);
        }
        case opv_go: {
            /* Verb #4: op.go(direction, count) -> boolean */
            tydirection dir;
            long units;
            hdloutlinerecord ho;
            boolean fl;

            if (!getdirectionvalue(hparam1, 1, &dir))
                return false;

            flnextparamislast = true;  /* Mark next parameter as last */
            if (!getlongvalue(hparam1, 2, &units))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);
            fl = opmotionkey(dir, units, false);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_firstsummit: {
            /* Verb #5: op.firstsummit - go to first summit
             *
             * Navigates to the first top-level node (summit), which is always hsummit.
             * All outlines start with an empty summit (documented in docs/OUTLINE_STRUCTURE.md).
             * We explicitly move to hsummit using opmoveto() instead of motion keys.
             */
            hdloutlinerecord ho;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);

            /* Move directly to the summit node (may be empty) */
            opmoveto((**ho).hsummit);

            oppopoutline();

            /* Always return true - we successfully positioned at the summit */
            return setbooleanvalue(true, vreturned);
        }
        case opv_expand: {
            /* op.expand(levels) -> boolean - expands subheads */
            long levellong;
            short level;
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            boolean fl;

            flnextparamislast = true;  /* Single parameter - mark as last */
            if (!getlongvalue(hparam1, 1, &levellong))
                return false;

            /* Clamp to short range (opexpand expects short) */
            if (levellong > 32767)
                level = 32767;  /* Max short value - effectively infinity */
            else if (levellong < -32768)
                level = -32768;
            else
                level = (short)levellong;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            fl = opexpand(hbarcursor, level, true);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_collapse: {
            /* op.collapse() - Collapse subheads */
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror)) {
                return false;
            }

            oppushoutline(ho);
            hbarcursor = (**ho).hbarcursor;
            fl = opcollapse(hbarcursor);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_subsexpanded: {
            /* Verb #8: op.subsexpanded - Returns true if subheads are expanded */
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);

            /* opsubheadsexpanded() requires explicit cursor parameter (query function)
             * Unlike modification functions like opreorgcursor(), it doesn't use global outlinedata */
            hbarcursor = (**ho).hbarcursor;
            fl = opsubheadsexpanded(hbarcursor);

            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_insert: {
            /* Verb #9: op.insert(text, direction) -> boolean
             *
             * Inserts a new node with the given text in the specified direction.
             * Cursor moves to the newly inserted node.
             */
            Handle htext;
            tydirection dir;
            hdloutlinerecord ho;
            boolean fl;

            /* Parse parameters */
            if (!getexempttextvalue(hparam1, 1, &htext))
                return false;

            flnextparamislast = true;  /* Mark next parameter as last */
            if (!getdirectionvalue(hparam1, 2, &dir)) {
                disposehandle(htext);
                return false;
            }

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                disposehandle(htext);
                return false;
            }

            oppushoutline(ho);

            /* Insert new node */
            fl = opinserthandle(htext, dir);

            oppopoutline();

            disposehandle(htext);

            return setbooleanvalue(fl, vreturned);
        }
        case opv_find: {
            /* Verb #10: op.find(searchText [, wholewords] [, casesensitive]) -> boolean
             *
             * Searches through outline headlines for text matching searchText.
             * Moves the bar cursor to the first matching headline.
             *
             * HEADLESS ADAPTATION:
             * Unlike the GUI version (opflatfind), we don't highlight text or enter edit mode.
             * We simply search headlines and move the bar cursor to the matching node.
             * NOTE: The wholewords parameter is accepted for API compatibility but not
             * implemented in this headless version - all searches are substring matches.
             *
             * Parameters:
             *   searchText (required) - text to search for
             *   wholewords (optional) - whole word matching (accepted but not implemented), default false
             *   casesensitive (optional) - case sensitive search, default false
             *
             * Returns true if found and cursor moved, false if not found.
             *
             * Algorithm:
             * - Start searching from current cursor position (or next node)
             * - Use textpatternmatch() for Boyer-Moore search
             * - Search flatdown through outline (depth-first traversal)
             * - Stop when match found or back to original position
             */
            hdloutlinerecord ho;
            bigstring bs;
            boolean flwholewords = false;  /* Default: substring match (not implemented) */
            boolean flcase = false;  /* Default: case insensitive */
            hdlheadrecord nomad, orignomad;
            Handle htext;
            boolean found = false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            /* Get required searchText parameter */
            if (!getstringvalue(hparam1, 1, bs))
                return false;

            /* Get optional wholewords parameter (param 2) if provided */
            if (langgetparamcount(hparam1) >= 2) {
                if (!getbooleanvalue(hparam1, 2, &flwholewords))
                    return false;
                /* NOTE: wholewords not implemented - accepted for API compatibility */
            }

            /* Get optional casesensitive parameter (param 3) if provided */
            if (langgetparamcount(hparam1) >= 3) {
                flnextparamislast = true;
                if (!getbooleanvalue(hparam1, 3, &flcase))
                    return false;
            }

            /* Start search from current cursor */
            nomad = (**ho).hbarcursor;
            orignomad = nomad;

            /* Search loop - pattern from opflatfind */
            while (true) {
                /* Check for nil before dereferencing (opbumpflatdown can return nil) */
                if (nomad == nil)
                    break;

                /* Get headline text and search it */
                htext = (**nomad).headstring;
                if (htext != nil) {
                    long len = gethandlesize(htext);
                    /* Use textpatternmatch for Boyer-Moore search */
                    if (textpatternmatch(*htext, len, bs, !flcase) >= 0) {
                        /* Found match - move cursor to this node */
                        (**ho).hbarcursor = nomad;
                        found = true;
                        break;
                    }
                }

                /* Move to next node in flat order */
                nomad = opbumpflatdown(nomad, true);

                /* Check if we've returned to original position - search complete */
                if (nomad == orignomad) {
                    break;
                }
            }

            return setbooleanvalue(found, vreturned);
        }
        case opv_sort: {
            /* Verb #11: op.sort() -> boolean
             *
             * Sorts the current headline and all its siblings alphabetically by headline text.
             * Does NOT sort subheads - only siblings at the same level as the cursor.
             *
             * Algorithm:
             * - Uses opsortlevel() which implements selection sort
             * - Finds all siblings at same level as bar cursor
             * - Sorts them alphabetically (case-insensitive by default)
             * - Preserves subhead hierarchy (each node's children stay with their parent)
             *
             * Example:
             *   Before:         After:
             *   - Charlie       - Alice
             *     - Sub1          - Sub2
             *   - Alice         - Bob
             *     - Sub2        - Charlie
             *   - Bob             - Sub1
             *
             * Returns true if sort succeeded, false otherwise.
             */
            hdloutlinerecord ho;
            hdlheadrecord hbarcursor;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);  /* Ensure outline mode */
            hbarcursor = (**ho).hbarcursor;
            fl = opsortlevel(hbarcursor);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_setlinetext: {
            /* Verb #12: op.setlinetext - Modify headline text at cursor
             * Note: opsetheadtext() consumes htext handle, so don't dispose it */
            Handle htext;
            hdloutlinerecord ho;
            hdlheadrecord hcursor;
            boolean fl;

            flnextparamislast = true;
            if (!getexempttextvalue(hparam1, 1, &htext))
                return false;

            if (!getoutlinefromtarget(&ho, bserror)) {
                disposehandle(htext);
                return false;
            }

            oppushoutline(ho);
            opsettextmode(false);  /* Ensure outline mode (consistent with promote/demote) */
            hcursor = (**ho).hbarcursor;
            fl = opsetheadtext(hcursor, htext);  /* Consumes htext */
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_reorg: {
            /* Verb #13: op.reorg(direction, count) - Reorganize outline hierarchy
             *
             * General version of op.promote/op.demote that takes direction and count.
             * - direction: left=promote/outdent, right=demote/indent, up/down=move node
             * - count: number of times to repeat the operation
             *
             * Examples:
             *   op.reorg(left, 1)   -> same as op.promote()
             *   op.reorg(right, 1)  -> same as op.demote()
             *   op.reorg(up, 2)     -> move node up 2 positions
             *   op.reorg(right, 2)  -> demote 2 levels (increase nesting by 2)
             *
             * Headless implementation: For left/right with count > 1, we implement a simple
             * loop calling opreorgcursor(dir, 1) repeatedly. opreorgcursor() expects marked
             * nodes for multi-level moves, which we don't have in headless mode.
             */
            tydirection dir;
            long ct;
            hdloutlinerecord ho;
            boolean fl = true;
            long i;

            if (!getdirectionvalue(hparam1, 1, &dir))
                return false;

            flnextparamislast = true;
            if (!getlongvalue(hparam1, 2, &ct))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);  /* Ensure we're in outline mode, not text editing */

            /* For left/right with count > 1, loop to move multiple levels
             * Go as far as possible - return true if moved at least once, false if zero movement */
            if ((dir == left || dir == right) && ct > 1) {
                long successful_moves = 0;
                for (i = 0; i < ct; i++) {
                    if (!opreorgcursor(dir, 1))
                        break;  /* Can't move further, stop trying */
                    successful_moves++;
                }
                fl = (successful_moves > 0);  /* True if moved at least once */
            } else {
                /* For up/down or single-level moves, call directly */
                fl = opreorgcursor(dir, ct);
            }

            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_promote: {
            /* Verb #14: op.promote - Promote children up one level
             * Moves all children of cursor node out one level.
             * Delegates to oppromote() which handles multiple nodes correctly.
             */
            hdloutlinerecord ho;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);
            fl = oppromote();
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_demote: {
            /* Verb #15: op.demote - Demote following siblings
             * Moves all nodes down from cursor to become children of cursor.
             * Delegates to opdemote() which handles multiple nodes correctly.
             */
            hdloutlinerecord ho;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opsettextmode(false);
            fl = opdemote();
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_hoist: {
            /* Verb #16: op.hoist() -> boolean
             *
             * GUI DISPLAY OPERATION: "Hoist" collapses the outline view to show only
             * the current node's subheads as if they were top-level nodes.
             *
             * HEADLESS MODE: This is a visual display transformation that doesn't apply
             * without a GUI window. In headless mode, there's no concept of "hoisted view"
             * since we're working with the underlying data structure directly.
             *
             * Returns false with error message indicating this is GUI-only.
             */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            seterrorstring("Can't hoist in headless mode (GUI-only operation)", bserror);
            return setbooleanvalue(false, vreturned);
        }
        case opv_dehoist: {
            /* Verb #17: op.dehoist() -> boolean
             *
             * GUI DISPLAY OPERATION: Reverses a "hoist" operation, restoring the full
             * outline view after having collapsed to show only subheads.
             *
             * HEADLESS MODE: Since hoisting doesn't apply in headless mode (no GUI display),
             * dehoisting is also not applicable. Returns false with error.
             *
             * Returns false with error message indicating this is GUI-only.
             */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            seterrorstring("Can't dehoist in headless mode (GUI-only operation)", bserror);
            return setbooleanvalue(false, vreturned);
        }
        case opv_deletesubs: {
            /* Verb #18: op.deletesubs - Delete children without deleting parent */
            hdloutlinerecord ho;
            hdlheadrecord hcursor;
            boolean fl;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hcursor = (**ho).hbarcursor;
            fl = opdeletesubs(hcursor);
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_deleteline: {
            /* Verb #19: op.deleteline - delete the bar cursor line and all children
             *
             * Outline Minimal State Behavior:
             * Every outline maintains at least one blank node (minimal state).
             * When deleting the only node, a new empty node is created in its place.
             *
             * Cursor Movement Rules:
             * - When deleting last node under sub-heading with sibling above → cursor moves to sibling
             * - When deleting last node under sub-heading without sibling → cursor moves to parent
             * - When deleting last top-level node → cursor moves to node above (even if it has children)
             * - When deleting only node at top level → single new blank node created
             */
            hdloutlinerecord ho;
            hdlheadrecord hcursor;

            if (!langcheckparamcount(hparam1, 0))
                return false;

            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            opdeleteline();

            /* Post-delete cursor handling for headless mode:
             * opdeleteline() may leave cursor on empty root summit node (minimal state).
             * In GUI mode, display refresh handles this. In headless mode,
             * we must explicitly move to next valid node. */

            /* Verify cursor is still valid after deletion */
            hcursor = (**ho).hbarcursor;
            if (hcursor == NULL) {
                oppopoutline();
                return setbooleanvalue(true, vreturned);
            }

            /* Check if headline text is valid and non-empty */
            Handle htext = (**hcursor).headstring;
            if (htext == NULL) {
                oppopoutline();
                return setbooleanvalue(true, vreturned);
            }

            long textsize = gethandlesize(htext);
            log_debug(LOG_COMP_OP, "deleteLine: after delete, cursor text size=%ld", textsize);

            if (textsize == 0) {
                /* Empty node - try to move down to next node */
                hdlheadrecord hnext = (**hcursor).headlinkdown;
                log_debug(LOG_COMP_OP, "deleteLine: headlinkdown=%p, hcursor=%p, same=%d", hnext, hcursor, hnext==hcursor);
                if (hnext != hcursor) {
                    (**ho).hbarcursor = hnext;
                    log_debug(LOG_COMP_OP, "deleteLine: moved to next node");
                }
            }

            oppopoutline();

            return setbooleanvalue(true, vreturned);
        }
        case opv_tabkeyreorg: {
            /* Verb #20: op.tabkeyreorg(setting) -> boolean
             *
             * PREFERENCE TOGGLE: In GUI Frontier, this controls whether Tab key indents/outdents
             * nodes or just inserts a tab character.
             *
             * HEADLESS MODE: Preferences for keyboard behavior don't apply without an interactive
             * GUI environment. This is a noop that always returns true for API compatibility.
             *
             * Parameters:
             *   setting (boolean) - enable/disable tab key reorganization (ignored in headless)
             *
             * Returns true (success) without performing any action.
             */
            boolean setting;

            /* Accept setting parameter for API compatibility */
            flnextparamislast = true;
            if (!getbooleanvalue(hparam1, 1, &setting))
                return false;

            /* Noop in headless mode - return success */
            return setbooleanvalue(true, vreturned);
        }
        case opv_flatcursorkeys: {
            /* Verb #21: op.flatcursorkeys(setting) -> boolean
             *
             * PREFERENCE TOGGLE: In GUI Frontier, this controls whether cursor keys navigate
             * the outline structure (structured mode) or move through text character-by-character
             * (flat mode).
             *
             * HEADLESS MODE: Keyboard navigation preferences don't apply without an interactive
             * GUI environment. This is a noop that always returns true for API compatibility.
             *
             * Parameters:
             *   setting (boolean) - enable/disable flat cursor keys (ignored in headless)
             *
             * Returns true (success) without performing any action.
             */
            boolean setting;

            /* Accept setting parameter for API compatibility */
            flnextparamislast = true;
            if (!getbooleanvalue(hparam1, 1, &setting))
                return false;

            /* Noop in headless mode - return success */
            return setbooleanvalue(true, vreturned);
        }
        case opv_getdisplay: {
            /* Verb #22: op.getDisplay() -> boolean
             * Returns true if display updates are enabled (outline redraws on changes).
             * Note: flinhibitdisplay is inverted - true means display is OFF.
             */
            hdloutlinerecord ho;
            boolean fldisplay;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            fldisplay = !(**ho).flinhibitdisplay;  /* Invert flag */
            oppopoutline();

            return setbooleanvalue(fldisplay, vreturned);
        }
        case opv_setdisplay: {
            /* Verb #23: op.setDisplay(boolean) -> boolean
             * Enable/disable display updates (outline redraws on changes).
             * Note: flinhibitdisplay is inverted - true means display is OFF.
             */
            hdloutlinerecord ho;
            boolean fldisplay;

            flnextparamislast = true;
            if (!getbooleanvalue(hparam1, 1, &fldisplay))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            (**ho).flinhibitdisplay = !fldisplay;  /* Invert flag when setting */
            oppopoutline();

            return setbooleanvalue(true, vreturned);
        }
        case opv_getcursor: {
            /* Verb #24: op.getCursor() -> long
             * Returns opaque identifier for cursor position.
             * Returns handle cast to long (legacy behavior).
             * Identifier remains stable even when outline reorganizes.
             */
            hdloutlinerecord ho;
            hdlheadrecord hcursor;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hcursor = (**ho).hbarcursor;
            oppopoutline();

            /* Return handle as opaque identifier */
            return setlongvalue((long)hcursor, vreturned);
        }
        case opv_setcursor: {
            /* Verb #25: op.setCursor(id) -> boolean
             * Set cursor to node identified by opaque identifier.
             * Takes identifier from getCursor() and casts back to handle.
             * Returns false if identifier is invalid (node deleted, etc).
             */
            hdloutlinerecord ho;
            hdlheadrecord hnode;
            long nodeid;
            boolean fl;

            flnextparamislast = true;
            if (!getlongvalue(hparam1, 1, &nodeid))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);

            /* Cast identifier back to handle - validate it's non-zero first */
            if (nodeid == 0) {
                oppopoutline();
                return setbooleanvalue(false, vreturned);
            }
            hnode = (hdlheadrecord)nodeid;

            /* Verify node is in outline (not deleted) */
            if (!opnodeinoutline(hnode)) {
                oppopoutline();
                return setbooleanvalue(false, vreturned);
            }

            /* Expand parents to make cursor visible */
            opexpandto(hnode);

            /* Set cursor to this node using proper movement function */
            fl = opmoveto(hnode);

            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_getrefcon: {
            /* Verb #26: op.getRefcon() -> value
             * Get application-specific data stored with current node.
             * Returns 0 if no refcon, otherwise unpacks stored value.
             */
            hdloutlinerecord ho;
            hdlheadrecord hcursor;
            Handle hrefcon;
            tyvaluerecord linkedval;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hcursor = (**ho).hbarcursor;
            hrefcon = (**hcursor).hrefcon;

            if (hrefcon == nil) {
                setlongvalue(0, &linkedval);
            } else {
                if (!langunpackvalue(hrefcon, &linkedval)) {
                    oppopoutline();
                    return false;
                }
                pushvalueontmpstack(&linkedval);
            }
            oppopoutline();

            *vreturned = linkedval;
            return true;
        }
        case opv_setrefcon: {
            /* Verb #27: op.setRefcon(value) -> boolean
             * Store application-specific data with current node.
             * Pass 0 to clear refcon. Otherwise packs value into handle.
             */
            hdloutlinerecord ho;
            hdlheadrecord hcursor;
            tyvaluerecord val;
            Handle hbinary;
            boolean fl;

            flnextparamislast = true;
            if (!getparamvalue(hparam1, 1, &val))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            hcursor = (**ho).hbarcursor;

            /* Clear refcon if value is 0 */
            if ((val.valuetype == longvaluetype) && (val.data.longvalue == 0)) {
                disposehandle((**hcursor).hrefcon);
                (**hcursor).hrefcon = nil;
                fl = true;
            } else {
                /* Pack value into binary handle */
                if (!langpackvalue(val, &hbinary, HNoNode)) {
                    oppopoutline();
                    return false;
                }
                disposehandle((**hcursor).hrefcon);
                (**hcursor).hrefcon = hbinary;
                fl = true;
            }
            oppopoutline();

            return setbooleanvalue(fl, vreturned);
        }
        case opv_getexpansionstate: {
            /* Verb #28: op.getExpansionState() -> list
             * Returns list of 1-based line numbers that are expanded.
             * Delegates to existing opgetexpansionstateverb().
             */
            hdloutlinerecord ho;
            boolean fl;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);
            fl = opgetexpansionstateverb(vreturned);
            oppopoutline();

            return fl;
        }
        case opv_setexpansionstate: {
            /* Verb #29: op.setExpansionState(list) -> boolean
             * Restore expansion state from a list of 1-based line numbers.
             *
             * Algorithm (from original Frontier implementation):
             * 1. Iterate through CURRENTLY expanded nodes using opbumpflatdown(..., true)
             * 2. For nodes in the expansion list: expand if flexpanded flag set and not currently showing subheads
             * 3. For nodes NOT in the expansion list: collapse if currently expanded
             * 4. The flexpanded flag indicates persistent expansion state (stored in ODB)
             *    while opsubheadsexpanded() tells current visible state
             */
            hdloutlinerecord ho;
            tyvaluerecord vlist;
            hdlheadrecord hnode, nomad;
            tyvaluerecord vitem;
            long ct;
            long ix = 1;
            long ixlist = 0;
            long ixoutline = 0;
            boolean fl = true;

            flnextparamislast = true;
            if (!getparamvalue(hparam1, 1, &vlist))
                return false;

            /* Get list size */
            if (!langgetlistsize(&vlist, &ct))
                return false;

            /* Get first expansion line number if list not empty */
            if (ct > 0) {
                if (!langgetlistitem(&vlist, ix++, nil, &vitem))
                    return false;
                if (!coercevalue(&vitem, longvaluetype))
                    return false;
                ixlist = vitem.data.longvalue;
            }

            /* Get outline from target */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            oppushoutline(ho);

            /* Disable display during expansion state changes */
            (**ho).flinhibitdisplay = true;
            opsettextmode(false);

            /* Iterate through currently expanded nodes */
            hnode = (**ho).hsummit;

            while (true) {
                ++ixoutline;
                nomad = hnode;

                if (ixoutline == ixlist) {
                    /* This line IS in the expansion list - expand if not currently showing subheads */
                    if (!opsubheadsexpanded(nomad)) {
                        /* Set flexpanded flag first, then expand */
                        (**nomad).flexpanded = true;
                        opexpand(nomad, 1, true);
                    }

                    /* Get next item from expansion list */
                    if (ix <= ct) {
                        if (!langgetlistitem(&vlist, ix++, nil, &vitem)) {
                            fl = false;
                            goto cleanup;
                        }
                        if (!coercevalue(&vitem, longvaluetype)) {
                            fl = false;
                            goto cleanup;
                        }
                        ixlist = vitem.data.longvalue;
                    }
                } else {
                    /* This line is NOT in the expansion list - collapse if expanded */
                    if (opsubheadsexpanded(nomad)) {
                        opcollapse(nomad);
                    }
                }

                /* Move to next node - iterate only currently expanded/visible nodes */
                hnode = opbumpflatdown(nomad, true);

                if (hnode == nomad)
                    break;
            }

            /* Move cursor to an expanded node */
            hnode = (**ho).hbarcursor;
            while (!(**hnode).flexpanded) {
                /* Check if we've reached the summit (node points to itself) */
                hdlheadrecord hparent = (**hnode).headlinkleft;
                if (hnode == hparent || hparent == (**ho).hsummit)
                    break;
                hnode = hparent;
            }
            opmoveto(hnode);

        cleanup:
            /* Re-enable display */
            (**ho).flinhibitdisplay = false;
            oppopoutline();
            return setbooleanvalue(fl, vreturned);
        }
        case opv_getscrollstate: {
            /* Verb #30: op.getScrollState() -> long
             * Returns the line number (1-based) of the first headline displayed in the outline.
             *
             * HEADLESS MODE BEHAVIOR: Scroll state is meaningless without a visual display.
             * Always returns 1 (first line) since there's no concept of "scrolled position"
             * in a non-visual, headless environment.
             */
            hdloutlinerecord ho;

            /* No parameters */
            if (!langcheckparamcount(hparam1, 0))
                return false;

            /* Get outline from target (validate it exists) */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            /* In headless mode, scroll state doesn't apply - always return 1 (first line) */
            return setlongvalue(1, vreturned);
        }
        case opv_setscrollstate: {
            /* Verb #31: op.setScrollState(linenum) -> boolean
             * Scrolls the outline so that linenum is the first line displayed.
             *
             * HEADLESS MODE BEHAVIOR: Scroll state is meaningless without a visual display.
             * This is a noop operation - accepts the parameter for API compatibility but
             * does nothing, since there's no visual window to scroll in headless mode.
             * Always returns true (success).
             */
            hdloutlinerecord ho;
            long line1;

            /* Accept parameter for API compatibility */
            flnextparamislast = true;
            if (!getlongvalue(hparam1, 1, &line1))
                return false;

            /* Get outline from target (validate it exists) */
            if (!getoutlinefromtarget(&ho, bserror))
                return false;

            /* In headless mode, scroll state doesn't apply - noop operation */
            return setbooleanvalue(true, vreturned);
        }
        case opv_getsuboutline:
            /* Verb #32: op.getsuboutline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_insertoutline:
            /* Verb #33: op.insertoutline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setmodified:
            /* Verb #34: op.setmodified - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getselection:
            /* Verb #35: op.getselection - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getheadnumber:
            /* Verb #36: op.getheadnumber - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_visitall: {
            /* Verb #37: op.visitall(adrOutline, adrCallback) -> boolean
             *
             * Visits every headline in the outline, calling the specified callback script
             * for each node. Unlike op.visit() which only visits subheads of the current node,
             * visitall() traverses the ENTIRE outline structure.
             *
             * HEADLESS ADAPTATION:
             * The GUI version (opvisitallverb in opverbs.c) does complex window management:
             * - Opens outline window in hidden mode
             * - Sets outline as target
             * - Iterates through nodes calling callback
             * - Restores previous target
             *
             * In headless mode:
             * - Get outline from address parameter
             * - Set outline as target (save previous target)
             * - Iterate using opvisiteverything() to call the callback
             * - Restore previous target and cursor after visiting
             *
             * Parameters:
             *   adrOutline - address of outline table to visit
             *   adrCallback - address of callback script to run for each headline
             *
             * The callback script is called with the cursor positioned at each node.
             * The outline target is set before each callback, so the script can use
             * op.getLineText(), op.level(), etc. to inspect the current headline.
             *
             * Returns true if successful, false on error.
             */
            hdloutlinerecord ho;
            bigstring bsscriptname, bsoutline;
            hdlheadrecord horigcursor;
            tyvaluerecord voutline, vcallback, vprevtarget;
            hdlhashtable htablecallback, htableoutline;
            boolean fl;

            /* Get outline address parameter */
            if (!getaddressparam(hparam1, 1, &voutline))
                return false;

            /* Get callback address parameter */
            flnextparamislast = true;
            if (!getaddressparam(hparam1, 2, &vcallback))
                return false;

            /* Get callback script name from address */
            if (!getaddressvalue(vcallback, &htablecallback, bsscriptname)) {
                if (bserror) seterrorstring("Can't resolve callback address", bserror);
                return false;
            }

            /* Get outline table and name from address */
            if (!getaddressvalue(voutline, &htableoutline, bsoutline)) {
                if (bserror) seterrorstring("Can't resolve outline address", bserror);
                return false;
            }

            /* Save previous target and set outline as the new target */
            initvalue(&vprevtarget, novaluetype);
            if (!langsettarget(htableoutline, bsoutline, &vprevtarget)) {
                if (bserror) seterrorstring("Can't set outline as target", bserror);
                return false;
            }

            /* Now get the outline from the newly set target */
            if (!getoutlinefromtarget(&ho, bserror)) {
                /* Restore previous target before returning */
                if (vprevtarget.valuetype == addressvaluetype) {
                    hdlhashtable htprev;
                    bigstring bsprev;
                    if (getaddressvalue(vprevtarget, &htprev, bsprev))
                        langsettarget(htprev, bsprev, nil);
                }
                return false;
            }

            /* Save original cursor position */
            horigcursor = (**ho).hbarcursor;

            /* Set up context for callback - see opvisitall_callback above */
            opvisitall_context ctx;
            copystring(bsscriptname, ctx.scriptname);
            ctx.houtline = ho;

            /* Visit every node in the outline - callback handles push/pop */
            fl = opvisiteverything(&opvisitall_callback, &ctx);

            /* Restore original cursor */
            (**ho).hbarcursor = horigcursor;

            /* Restore previous target */
            if (vprevtarget.valuetype == addressvaluetype) {
                hdlhashtable htprev;
                bigstring bsprev;
                if (getaddressvalue(vprevtarget, &htprev, bsprev))
                    langsettarget(htprev, bsprev, nil);
            }

            return setbooleanvalue(fl, vreturned);
        }
        case opv_getselectedsuboutlines:
            /* Verb #38: op.getselectedsuboutlines - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_xmltooutline:
            /* Verb #39: op.xmltooutline - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_outlinetoxml:
            /* Verb #40: op.outlinetoxml - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_sethtmlformatting:
            /* Verb #41: op.sethtmlformatting - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_gethtmlformatting:
            /* Verb #42: op.gethtmlformatting - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_setdynamic:
            /* Verb #43: op.setdynamic - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        case opv_getdynamic:
            /* Verb #44: op.getdynamic - not yet implemented */
            if (bserror) seterrorstring("not implemented", bserror);
            return false;
        default:
            return false;
    }
}

boolean opinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pop"), bsname);

    if (!newfunctionprocessor(bsname, &op_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pgetlinetext"), opv_getlinetext);
    ADD_VERB(BIGSTRING("\plevel"), opv_level);
    ADD_VERB(BIGSTRING("\pcountsubs"), opv_countsubs);
    ADD_VERB(BIGSTRING("\pcountsummits"), opv_countsummits);
    ADD_VERB(BIGSTRING("\pgo"), opv_go);
    ADD_VERB(BIGSTRING("\pfirstsummit"), opv_firstsummit);
    ADD_VERB(BIGSTRING("\pexpand"), opv_expand);
    ADD_VERB(BIGSTRING("\pcollapse"), opv_collapse);
    ADD_VERB(BIGSTRING("\psubsexpanded"), opv_subsexpanded);
    ADD_VERB(BIGSTRING("\pinsert"), opv_insert);
    ADD_VERB(BIGSTRING("\pfind"), opv_find);
    ADD_VERB(BIGSTRING("\psort"), opv_sort);
    ADD_VERB(BIGSTRING("\psetlinetext"), opv_setlinetext);
    ADD_VERB(BIGSTRING("\preorg"), opv_reorg);
    ADD_VERB(BIGSTRING("\ppromote"), opv_promote);
    ADD_VERB(BIGSTRING("\pdemote"), opv_demote);
    ADD_VERB(BIGSTRING("\phoist"), opv_hoist);
    ADD_VERB(BIGSTRING("\pdehoist"), opv_dehoist);
    ADD_VERB(BIGSTRING("\pdeletesubs"), opv_deletesubs);
    ADD_VERB(BIGSTRING("\pdeleteline"), opv_deleteline);
    ADD_VERB(BIGSTRING("\ptabkeyreorg"), opv_tabkeyreorg);
    ADD_VERB(BIGSTRING("\pflatcursorkeys"), opv_flatcursorkeys);
    ADD_VERB(BIGSTRING("\pgetdisplay"), opv_getdisplay);
    ADD_VERB(BIGSTRING("\psetdisplay"), opv_setdisplay);
    ADD_VERB(BIGSTRING("\pgetcursor"), opv_getcursor);
    ADD_VERB(BIGSTRING("\psetcursor"), opv_setcursor);
    ADD_VERB(BIGSTRING("\pgetrefcon"), opv_getrefcon);
    ADD_VERB(BIGSTRING("\psetrefcon"), opv_setrefcon);
    ADD_VERB(BIGSTRING("\pgetexpansionstate"), opv_getexpansionstate);
    ADD_VERB(BIGSTRING("\psetexpansionstate"), opv_setexpansionstate);
    ADD_VERB(BIGSTRING("\pgetscrollstate"), opv_getscrollstate);
    ADD_VERB(BIGSTRING("\psetscrollstate"), opv_setscrollstate);
    ADD_VERB(BIGSTRING("\pgetsuboutline"), opv_getsuboutline);
    ADD_VERB(BIGSTRING("\pinsertoutline"), opv_insertoutline);
    ADD_VERB(BIGSTRING("\psetmodified"), opv_setmodified);
    ADD_VERB(BIGSTRING("\pgetselection"), opv_getselection);
    ADD_VERB(BIGSTRING("\pgetheadnumber"), opv_getheadnumber);
    ADD_VERB(BIGSTRING("\pvisitall"), opv_visitall);
    ADD_VERB(BIGSTRING("\pgetselectedsuboutlines"), opv_getselectedsuboutlines);
    ADD_VERB(BIGSTRING("\pxmltooutline"), opv_xmltooutline);
    ADD_VERB(BIGSTRING("\poutlinetoxml"), opv_outlinetoxml);
    ADD_VERB(BIGSTRING("\psethtmlformatting"), opv_sethtmlformatting);
    ADD_VERB(BIGSTRING("\pgethtmlformatting"), opv_gethtmlformatting);
    ADD_VERB(BIGSTRING("\psetdynamic"), opv_setdynamic);
    ADD_VERB(BIGSTRING("\pgetdynamic"), opv_getdynamic);

    #undef ADD_VERB

    pophashtable();
    return true;
}
