/*
 * headless_clock_verbs.c - Clock processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * Headless implementation for clock verbs (now/ticks/milliseconds) using the
 * portable time layer. We return 64-bit Mac-epoch seconds for clock.now().
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "time_portable.h"

/* Token enum for all verbs in the clock processor */
enum {
    clov_now = 0,
    clov_set = 1,
    clov_sleepfor = 2,
    clov_ticks = 3,
    clov_milliseconds = 4,
    clov_waitseconds = 5,
    clov_waitsixtieths = 6
};

static boolean clock_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {

    (void) hparam1;

    switch(token) {
        case clov_now:
        {
            /* Mac epoch (1904) seconds, 64-bit */
            const int64_t frontier_epoch_offset = 2082844800LL;
            uint64_t unix_ms = frontier_time_wallclock_millis();
            int64_t mac_seconds = (int64_t)(unix_ms / 1000ULL) + frontier_epoch_offset;
            return setdatevalue(mac_seconds, vreturned);
        }
        case clov_set:
            /* Verb #1: clock.set - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case clov_sleepfor:
            /* Verb #2: clock.sleepfor - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case clov_ticks:
        {
            /* Approximate classic 60Hz ticks from monotonic millis */
            uint64_t ms = frontier_time_monotonic_millis();
            int64_t ticks = (int64_t)(ms / 17ULL);
            return setlongvalue(ticks, vreturned);
        }
        case clov_milliseconds:
        {
            uint64_t ms = frontier_time_monotonic_millis();
            return setlongvalue((int64_t) ms, vreturned);
        }
        case clov_waitseconds:
            /* Verb #5: clock.waitseconds - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        case clov_waitsixtieths:
            /* Verb #6: clock.waitsixtieths - not yet implemented */
            if (bserror) copystring(BIGSTRING("\pnot implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean clockinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(BIGSTRING("\pclock"), bsname);

    if (!newfunctionprocessor(bsname, &clock_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(BIGSTRING("\pnow"), clov_now);
    ADD_VERB(BIGSTRING("\pset"), clov_set);
    ADD_VERB(BIGSTRING("\psleepfor"), clov_sleepfor);
    ADD_VERB(BIGSTRING("\pticks"), clov_ticks);
    ADD_VERB(BIGSTRING("\pmilliseconds"), clov_milliseconds);
    ADD_VERB(BIGSTRING("\pwaitseconds"), clov_waitseconds);
    ADD_VERB(BIGSTRING("\pwaitsixtieths"), clov_waitsixtieths);

    #undef ADD_VERB

    pophashtable();
    return true;
}
