/*
 * headless_html_verbs.c - Html processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains forwarding implementations for Phase 1 html verbs.
 *
 * DO NOT regenerate - this file contains production implementations.
 *
 * Implementation status:
 * - Phase 1 (7 verbs): COMPLETE - urldecode, urlencode, parsehttpargs, expandurls,
 *                                  processmacros, neutermacros, neutertags
 * - Phase 2 (12 verbs): COMPLETE - iso8859encode, getgif/jpegheightwidth, buildpagetable,
 *                                   getpref, rundirective(s), cleanforexport, glossarypatcher,
 *                                   traversalskip, getpagetableaddress, runoutlinedirectives
 * - Phase 3+: PENDING - Other HTML verbs remain stubbed
 *
 * See planning/phase3/html_verb_implementation_plan.md for complete roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "langhtml.h"

/* Token enum for all verbs in the html processor */
enum {
    htmv_processmacros = 0,
    htmv_urldecode = 1,
    htmv_urlencode = 2,
    htmv_parsehttpargs = 3,
    htmv_iso8859encode = 4,
    htmv_getgifheightwidth = 5,
    htmv_getjpegheightwidth = 6,
    htmv_buildpagetable = 7,
    htmv_refglossary = 8,
    htmv_getpref = 9,
    htmv_getonedirective = 10,
    htmv_rundirective = 11,
    htmv_rundirectives = 12,
    htmv_runoutlinedirectives = 13,
    htmv_cleanforexport = 14,
    htmv_normalizename = 15,
    htmv_glossarypatcher = 16,
    htmv_expandurls = 17,
    htmv_traversalskip = 18,
    htmv_getpagetableaddress = 19,
    htmv_neutermacros = 20,
    htmv_neutertags = 21,
    htmv_drawcalendar = 22
};

static boolean html_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    switch(token) {
        case htmv_processmacros:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return processhtmlmacrosverb(hparam1, vreturned);
        case htmv_urldecode:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return urldecodeverb(hparam1, vreturned);
        case htmv_urlencode:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return urlencodeverb(hparam1, vreturned);
        case htmv_parsehttpargs:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return parseargsverb(hparam1, vreturned);
        case htmv_iso8859encode:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return iso8859encodeverb(hparam1, vreturned);
        case htmv_getgifheightwidth:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return getgifheightwidthverb(hparam1, vreturned);
        case htmv_getjpegheightwidth:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return getjpegheightwidthverb(hparam1, vreturned);
        case htmv_buildpagetable:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return buildpagetableverb(hparam1, vreturned);
        case htmv_refglossary:
            /* Verb #8: html.refglossary - @SCRIPT_IMPLEMENTED in system.verbs.builtins.html */
            /* C helper htmlrefglossary() calls this via langrunscript() during macro processing */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case htmv_getpref:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return getprefverb(hparam1, vreturned);
        case htmv_getonedirective:
            /* Verb #10: html.getonedirective - @SCRIPT_IMPLEMENTED in system.verbs.builtins.html */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case htmv_rundirective:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return rundirectiveverb(hparam1, vreturned);
        case htmv_rundirectives:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return rundirectivesverb(hparam1, vreturned);
        case htmv_runoutlinedirectives:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return runoutlinedirectivesverb(hparam1, vreturned);
        case htmv_cleanforexport:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return cleanforexportverb(hparam1, vreturned);
        case htmv_normalizename:
            /* Verb #15: html.normalizename - @SCRIPT_IMPLEMENTED in system.verbs.builtins.html */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case htmv_glossarypatcher:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return glossarypatcherverb(hparam1, vreturned);
        case htmv_expandurls:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return expandurlsverb(hparam1, vreturned);
        case htmv_traversalskip:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return traversalskipverb(hparam1, vreturned);
        case htmv_getpagetableaddress:
            /* Phase 2: Forward to C implementation in langhtml.c */
            return getpagetableaddressverb(hparam1, vreturned);
        case htmv_neutermacros:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return htmlneutermacrosverb(hparam1, vreturned);
        case htmv_neutertags:
            /* Phase 1: Forward to C implementation in langhtml.c */
            return htmlneutertagsverb(hparam1, vreturned);
        case htmv_drawcalendar:
            /* Verb #22: html.drawcalendar - @IMPLEMENTED (ghost cruft, never actually implemented in Frontier) */
            /* Listed in kernelverbs.rc but no C implementation ever existed */
            /* defined(html.drawcalendar) returns false in legacy Windows Frontier */
            /* IOA calendar widget in cal.c was never wired up as a callable verb */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean htmlinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\004", "html"), bsname);

    if (!newfunctionprocessor(bsname, &html_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\015", "processmacros"), htmv_processmacros);
    ADD_VERB(PSTRING("\011", "urldecode"), htmv_urldecode);
    ADD_VERB(PSTRING("\011", "urlencode"), htmv_urlencode);
    ADD_VERB(PSTRING("\015", "parsehttpargs"), htmv_parsehttpargs);
    ADD_VERB(PSTRING("\015", "iso8859encode"), htmv_iso8859encode);
    ADD_VERB(PSTRING("\021", "getgifheightwidth"), htmv_getgifheightwidth);
    ADD_VERB(PSTRING("\022", "getjpegheightwidth"), htmv_getjpegheightwidth);
    ADD_VERB(PSTRING("\016", "buildpagetable"), htmv_buildpagetable);
    ADD_VERB(PSTRING("\013", "refglossary"), htmv_refglossary);
    ADD_VERB(PSTRING("\007", "getpref"), htmv_getpref);
    ADD_VERB(PSTRING("\017", "getonedirective"), htmv_getonedirective);
    ADD_VERB(PSTRING("\014", "rundirective"), htmv_rundirective);
    ADD_VERB(PSTRING("\015", "rundirectives"), htmv_rundirectives);
    ADD_VERB(PSTRING("\024", "runoutlinedirectives"), htmv_runoutlinedirectives);
    ADD_VERB(PSTRING("\016", "cleanforexport"), htmv_cleanforexport);
    ADD_VERB(PSTRING("\015", "normalizename"), htmv_normalizename);
    ADD_VERB(PSTRING("\017", "glossarypatcher"), htmv_glossarypatcher);
    ADD_VERB(PSTRING("\012", "expandurls"), htmv_expandurls);
    ADD_VERB(PSTRING("\015", "traversalskip"), htmv_traversalskip);
    ADD_VERB(PSTRING("\023", "getpagetableaddress"), htmv_getpagetableaddress);
    ADD_VERB(PSTRING("\014", "neutermacros"), htmv_neutermacros);
    ADD_VERB(PSTRING("\012", "neutertags"), htmv_neutertags);
    ADD_VERB(PSTRING("\014", "drawcalendar"), htmv_drawcalendar);

    #undef ADD_VERB

    pophashtable();
    return true;
}
