/*
 * headless_editmenu_verbs.c - Editmenu processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the editmenu processor */
enum {
    ediv_undo = 0,
    ediv_cut = 1,
    ediv_copy = 2,
    ediv_paste = 3,
    ediv_clear = 4,
    ediv_selectall = 5,
    ediv_getfont = 6,
    ediv_getfontsize = 7,
    ediv_setfont = 8,
    ediv_setfontsize = 9,
    ediv_plaintext = 10,
    ediv_setbold = 11,
    ediv_setitalic = 12,
    ediv_setunderline = 13,
    ediv_setoutline = 14,
    ediv_setshadow = 15
};

static boolean editmenu_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)hparam1;
    (void)vreturned;
    switch(token) {
        case ediv_undo:
            /* Verb #0: editmenu.undo - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_cut:
            /* Verb #1: editmenu.cut - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_copy:
            /* Verb #2: editmenu.copy - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_paste:
            /* Verb #3: editmenu.paste - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_clear:
            /* Verb #4: editmenu.clear - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_selectall:
            /* Verb #5: editmenu.selectall - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_getfont:
            /* Verb #6: editmenu.getfont - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_getfontsize:
            /* Verb #7: editmenu.getfontsize - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setfont:
            /* Verb #8: editmenu.setfont - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setfontsize:
            /* Verb #9: editmenu.setfontsize - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_plaintext:
            /* Verb #10: editmenu.plaintext - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setbold:
            /* Verb #11: editmenu.setbold - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setitalic:
            /* Verb #12: editmenu.setitalic - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setunderline:
            /* Verb #13: editmenu.setunderline - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setoutline:
            /* Verb #14: editmenu.setoutline - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case ediv_setshadow:
            /* Verb #15: editmenu.setshadow - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean editmenuinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\010", "editmenu"), bsname);

    if (!newfunctionprocessor(bsname, &editmenu_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\004", "undo"), ediv_undo);
    ADD_VERB(PSTRING("\003", "cut"), ediv_cut);
    ADD_VERB(PSTRING("\004", "copy"), ediv_copy);
    ADD_VERB(PSTRING("\005", "paste"), ediv_paste);
    ADD_VERB(PSTRING("\005", "clear"), ediv_clear);
    ADD_VERB(PSTRING("\011", "selectall"), ediv_selectall);
    ADD_VERB(PSTRING("\007", "getfont"), ediv_getfont);
    ADD_VERB(PSTRING("\013", "getfontsize"), ediv_getfontsize);
    ADD_VERB(PSTRING("\007", "setfont"), ediv_setfont);
    ADD_VERB(PSTRING("\013", "setfontsize"), ediv_setfontsize);
    ADD_VERB(PSTRING("\011", "plaintext"), ediv_plaintext);
    ADD_VERB(PSTRING("\007", "setbold"), ediv_setbold);
    ADD_VERB(PSTRING("\011", "setitalic"), ediv_setitalic);
    ADD_VERB(PSTRING("\014", "setunderline"), ediv_setunderline);
    ADD_VERB(PSTRING("\012", "setoutline"), ediv_setoutline);
    ADD_VERB(PSTRING("\011", "setshadow"), ediv_setshadow);

    #undef ADD_VERB

    pophashtable();
    return true;
}
