/*
 * headless_mysql_verbs.c - Mysql processor verbs (GENERATED FILE)
 *
 * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py
 * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py
 *
 * This is a stub implementation for Phase 1 testing.
 * All verbs currently return false/"not implemented".
 * See docs/verb_implementation_status.md for implementation roadmap.
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the mysql processor */
enum {
    mysv_init = 0,
    mysv_end = 1,
    mysv_connect = 2,
    mysv_compileQuery = 3,
    mysv_clearQuery = 4,
    mysv_getRow = 5,
    mysv_getErrorNumber = 6,
    mysv_getErrorMessage = 7,
    mysv_getClientInfo = 8,
    mysv_getClientVersion = 9,
    mysv_getHostInfo = 10,
    mysv_getServerVersion = 11,
    mysv_getProtocolInfo = 12,
    mysv_getServerInfo = 13,
    mysv_getQueryInfo = 14,
    mysv_getAffectedRowCount = 15,
    mysv_getSelectedRowCount = 16,
    mysv_getColumnCount = 17,
    mysv_getServerStatus = 18,
    mysv_getQueryWarningCount = 19,
    mysv_pingServer = 20,
    mysv_seekRow = 21,
    mysv_selectDatabase = 22,
    mysv_getSQLSTATE = 23,
    mysv_escapeString = 24,
    mysv_isThreadSafe = 25,
    mysv_close = 26
};

static boolean mysql_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)hparam1;
    (void)vreturned;
    switch(token) {
        case mysv_init:
            /* Verb #0: mysql.init - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_end:
            /* Verb #1: mysql.end - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_connect:
            /* Verb #2: mysql.connect - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_compileQuery:
            /* Verb #3: mysql.compileQuery - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_clearQuery:
            /* Verb #4: mysql.clearQuery - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getRow:
            /* Verb #5: mysql.getRow - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getErrorNumber:
            /* Verb #6: mysql.getErrorNumber - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getErrorMessage:
            /* Verb #7: mysql.getErrorMessage - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getClientInfo:
            /* Verb #8: mysql.getClientInfo - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getClientVersion:
            /* Verb #9: mysql.getClientVersion - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getHostInfo:
            /* Verb #10: mysql.getHostInfo - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getServerVersion:
            /* Verb #11: mysql.getServerVersion - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getProtocolInfo:
            /* Verb #12: mysql.getProtocolInfo - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getServerInfo:
            /* Verb #13: mysql.getServerInfo - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getQueryInfo:
            /* Verb #14: mysql.getQueryInfo - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getAffectedRowCount:
            /* Verb #15: mysql.getAffectedRowCount - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getSelectedRowCount:
            /* Verb #16: mysql.getSelectedRowCount - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getColumnCount:
            /* Verb #17: mysql.getColumnCount - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getServerStatus:
            /* Verb #18: mysql.getServerStatus - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getQueryWarningCount:
            /* Verb #19: mysql.getQueryWarningCount - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_pingServer:
            /* Verb #20: mysql.pingServer - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_seekRow:
            /* Verb #21: mysql.seekRow - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_selectDatabase:
            /* Verb #22: mysql.selectDatabase - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_getSQLSTATE:
            /* Verb #23: mysql.getSQLSTATE - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_escapeString:
            /* Verb #24: mysql.escapeString - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_isThreadSafe:
            /* Verb #25: mysql.isThreadSafe - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        case mysv_close:
            /* Verb #26: mysql.close - not yet implemented */
            if (bserror) copystring(PSTRING("\017", "not implemented"), bserror);
            return false;
        default:
            return false;
    }
}

boolean mysqlinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\005", "mysql"), bsname);

    if (!newfunctionprocessor(bsname, &mysql_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\004", "init"), mysv_init);
    ADD_VERB(PSTRING("\003", "end"), mysv_end);
    ADD_VERB(PSTRING("\007", "connect"), mysv_connect);
    ADD_VERB(PSTRING("\014", "compileQuery"), mysv_compileQuery);
    ADD_VERB(PSTRING("\012", "clearQuery"), mysv_clearQuery);
    ADD_VERB(PSTRING("\006", "getRow"), mysv_getRow);
    ADD_VERB(PSTRING("\016", "getErrorNumber"), mysv_getErrorNumber);
    ADD_VERB(PSTRING("\017", "getErrorMessage"), mysv_getErrorMessage);
    ADD_VERB(PSTRING("\015", "getClientInfo"), mysv_getClientInfo);
    ADD_VERB(PSTRING("\020", "getClientVersion"), mysv_getClientVersion);
    ADD_VERB(PSTRING("\013", "getHostInfo"), mysv_getHostInfo);
    ADD_VERB(PSTRING("\020", "getServerVersion"), mysv_getServerVersion);
    ADD_VERB(PSTRING("\017", "getProtocolInfo"), mysv_getProtocolInfo);
    ADD_VERB(PSTRING("\015", "getServerInfo"), mysv_getServerInfo);
    ADD_VERB(PSTRING("\014", "getQueryInfo"), mysv_getQueryInfo);
    ADD_VERB(PSTRING("\023", "getAffectedRowCount"), mysv_getAffectedRowCount);
    ADD_VERB(PSTRING("\023", "getSelectedRowCount"), mysv_getSelectedRowCount);
    ADD_VERB(PSTRING("\016", "getColumnCount"), mysv_getColumnCount);
    ADD_VERB(PSTRING("\017", "getServerStatus"), mysv_getServerStatus);
    ADD_VERB(PSTRING("\024", "getQueryWarningCount"), mysv_getQueryWarningCount);
    ADD_VERB(PSTRING("\012", "pingServer"), mysv_pingServer);
    ADD_VERB(PSTRING("\007", "seekRow"), mysv_seekRow);
    ADD_VERB(PSTRING("\016", "selectDatabase"), mysv_selectDatabase);
    ADD_VERB(PSTRING("\013", "getSQLSTATE"), mysv_getSQLSTATE);
    ADD_VERB(PSTRING("\014", "escapeString"), mysv_escapeString);
    ADD_VERB(PSTRING("\014", "isThreadSafe"), mysv_isThreadSafe);
    ADD_VERB(PSTRING("\005", "close"), mysv_close);

    #undef ADD_VERB

    pophashtable();
    return true;
}
