/*
 * headless_kb_verbs.c - Kb processor verb implementations
 *
 * Originally generated by tools/kernelverbs_parser/generate_processor_stubs.py,
 * now contains production implementations.
 *
 * Implementation status:
 * - kb.optionkey: COMPLETE - Returns false (no keyboard in headless mode)
 * - kb.cmdkey: COMPLETE - Returns false (no keyboard in headless mode)
 * - kb.shiftkey: COMPLETE - Returns false (no keyboard in headless mode)
 * - kb.controlkey: COMPLETE - Returns false (no keyboard in headless mode)
 */

#include "frontier.h"
#include "standard.h"

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"

/* Token enum for all verbs in the kb processor */
enum {
    kbv_optionkey = 0,
    kbv_cmdkey = 1,
    kbv_shiftkey = 2,
    kbv_controlkey = 3
};

static boolean kb_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;
    switch(token) {
        case kbv_optionkey:
            /* @IMPLEMENTED kb.optionkey - Returns false (no keyboard in headless mode) */
        case kbv_cmdkey:
            /* @IMPLEMENTED kb.cmdkey - Returns false (no keyboard in headless mode) */
        case kbv_shiftkey:
            /* @IMPLEMENTED kb.shiftkey - Returns false (no keyboard in headless mode) */
        case kbv_controlkey:
            /* @IMPLEMENTED kb.controlkey - Returns false (no keyboard in headless mode) */
            if (!langcheckparamcount(hparam1, 0))
                return false;
            return setbooleanvalue(false, vreturned);
        default:
            return false;
    }
}

boolean kbinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\002", "kb"), bsname);

    if (!newfunctionprocessor(bsname, &kb_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\011", "optionkey"), kbv_optionkey);
    ADD_VERB(PSTRING("\006", "cmdkey"), kbv_cmdkey);
    ADD_VERB(PSTRING("\010", "shiftkey"), kbv_shiftkey);
    ADD_VERB(PSTRING("\012", "controlkey"), kbv_controlkey);

    #undef ADD_VERB

    pophashtable();
    return true;
}
