
test_system_verbs: /tmp/test_system_verbs.c $(LANG_RUNTIME_SOURCES) headless_shell.c
	$(CC) $(CFLAGS) -DFRONTIER_HEADLESS -I../Common/headers -I../Common/SystemHeaders -I../portable \
		/tmp/test_system_verbs.c $(LANG_RUNTIME_SOURCES) headless_shell.c -o $@ $(LINK_LIBS)
