/*
 * ut_sync_canonicalize_tests.c - Parity unit tests for the ODB<->.ut
 * canonicalizer (frontier-cli/ut_sync.c ut_canonicalize_outline_text).
 *
 * The C canonicalizer is a port of the Python reference
 * (tools/verify_virgin_root_sync.py normalize_kernel_body). These tests
 * assert the C output is BYTE-IDENTICAL to the Python reference output on a
 * battery of fixtures that exercise every transform step:
 *
 *   simple            CR -> LF, no trailing newline
 *   highbit           MacRoman high-bit chars -> UTF-8 (curly-quote string)
 *   comment_markers   0xC7 -> "//", 0xC8 dropped (outside literals)
 *   marker_in_string  0xC7/0xC8 PRESERVED inside a "..." string
 *   marker_in_char    0xC8 PRESERVED inside a '...' char literal
 *   brace_strip       all-comment subtree: structure braces stripped
 *   empty             empty input -> empty output
 *   corpus_edit       a real corpus script (suites/odbEditor/edit) reversed
 *                     to raw-kernel form; must reproduce the on-disk .ut
 *
 * The fixtures live in tests/fixtures/ut_sync/[name].in (raw kernel bytes,
 * post-JSON-unescape) and [name].expected (the Python reference output,
 * i.e. the .ut canonical bytes). They are generated by running
 * normalize_kernel_body on each input, so a passing test proves C == Python.
 *
 * License
 * -------
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Frontier contributors.
 */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "test_report.h"

#include "../frontier-cli/ut_sync.h"

/* Locate the fixtures dir relative to the tests/ working directory. The
 * suite is run from tests/, so fixtures are at fixtures/ut_sync/. */
#define FIXTURE_DIR "fixtures/ut_sync"

/* Read an entire file into a malloc'd buffer. Returns 1 on success and sets
 * the out params; the buffer is NUL-terminated (NUL not counted in len). On
 * failure returns 0. A missing file is a hard failure (fixtures must exist). */
static int read_file(const char *path, unsigned char **buf, size_t *len) {
	FILE *f = fopen(path, "rb");
	long sz;
	unsigned char *data;
	size_t got;

	*buf = NULL;
	*len = 0;
	if (f == NULL) {
		fprintf(stderr, "fixture missing: %s\n", path);
		return 0;
	}
	if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return 0; }
	sz = ftell(f);
	if (sz < 0) { fclose(f); return 0; }
	if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return 0; }

	data = (unsigned char *)malloc((size_t)sz + 1);
	if (data == NULL) { fclose(f); return 0; }
	got = fread(data, 1, (size_t)sz, f);
	fclose(f);
	if (got != (size_t)sz) { free(data); return 0; }
	data[sz] = '\0';
	*buf = data;
	*len = (size_t)sz;
	return 1;
}

/* Print a byte buffer with non-printables escaped, for failure diagnostics. */
static void dump_escaped(const char *label, const unsigned char *b, size_t n) {
	size_t i;
	fprintf(stderr, "  %s (%zu bytes): ", label, n);
	for (i = 0; i < n && i < 200; i++) {
		unsigned char c = b[i];
		if (c == '\n') fprintf(stderr, "\\n");
		else if (c == '\r') fprintf(stderr, "\\r");
		else if (c == '\t') fprintf(stderr, "\\t");
		else if (c >= 0x20 && c < 0x7f) fputc(c, stderr);
		else fprintf(stderr, "\\x%02x", c);
	}
	if (n > 200) fprintf(stderr, "...");
	fprintf(stderr, "\n");
}

/* Core assertion: canonicalize <name>.in and require byte-equality with
 * <name>.expected. */
static void check_fixture(const char *name) {
	char in_path[512];
	char exp_path[512];
	unsigned char *in = NULL, *expected = NULL, *got = NULL;
	size_t in_len = 0, exp_len = 0, got_len = 0;
	int ok;

	snprintf(in_path, sizeof(in_path), "%s/%s.in", FIXTURE_DIR, name);
	snprintf(exp_path, sizeof(exp_path), "%s/%s.expected", FIXTURE_DIR, name);

	assert(read_file(in_path, &in, &in_len));
	assert(read_file(exp_path, &expected, &exp_len));

	ok = ut_canonicalize_outline_text(in, in_len, &got, &got_len);
	assert(ok == 1);
	assert(got != NULL);

	if (got_len != exp_len || memcmp(got, expected, exp_len) != 0) {
		fprintf(stderr, "PARITY MISMATCH for fixture '%s':\n", name);
		dump_escaped("expected", expected, exp_len);
		dump_escaped("got     ", got, got_len);
	}
	assert(got_len == exp_len);
	assert(memcmp(got, expected, exp_len) == 0);

	free(in);
	free(expected);
	free(got);
}

static void test_simple(void)            { check_fixture("simple"); }
static void test_highbit(void)           { check_fixture("highbit"); }
static void test_comment_markers(void)   { check_fixture("comment_markers"); }
static void test_marker_in_string(void)  { check_fixture("marker_in_string"); }
static void test_marker_in_char(void)    { check_fixture("marker_in_char"); }
static void test_brace_strip(void)       { check_fixture("brace_strip"); }
static void test_empty(void)             { check_fixture("empty"); }
static void test_trailing_nl(void)       { check_fixture("trailing_nl"); }
static void test_corpus_edit(void)       { check_fixture("corpus_edit"); }

/* A direct (non-fixture) idempotence check: an already-canonical .ut body
 * fed back through the canonicalizer must be unchanged. This guards the
 * import->export round trip (a .ut imported then re-exported should not
 * drift). */
static void test_idempotent_on_canonical(void) {
	const char *canon = "on f () {\n\t//comment\n\treturn (1)}";
	unsigned char *got = NULL;
	size_t got_len = 0;
	size_t canon_len = strlen(canon);

	assert(ut_canonicalize_outline_text((const unsigned char *)canon,
	                                    canon_len, &got, &got_len) == 1);
	if (got_len != canon_len || memcmp(got, canon, canon_len) != 0) {
		fprintf(stderr, "idempotence failed:\n");
		dump_escaped("in ", (const unsigned char *)canon, canon_len);
		dump_escaped("out", got, got_len);
	}
	assert(got_len == canon_len);
	assert(memcmp(got, canon, canon_len) == 0);
	free(got);
}

int main(void) {
	TR_INIT("ut_sync_canonicalize_tests");
	TR_RUN(test_simple);
	TR_RUN(test_highbit);
	TR_RUN(test_comment_markers);
	TR_RUN(test_marker_in_string);
	TR_RUN(test_marker_in_char);
	TR_RUN(test_brace_strip);
	TR_RUN(test_empty);
	TR_RUN(test_trailing_nl);
	TR_RUN(test_corpus_edit);
	TR_RUN(test_idempotent_on_canonical);
	TR_SUMMARY();
	return TR_EXIT_CODE();
}
