#!/usr/bin/env python3
"""
generate_processor_stubs.py - Generate stub processor files for all unimplemented verbs

This script parses kernelverbs.rc and generates skeleton C files for all processors
that don't yet have headless implementations.

Usage:
    python3 generate_processor_stubs.py <input.rc> <output_dir> [--implemented processor1,processor2,...]

Example:
    python3 generate_processor_stubs.py \
        Common/resources/Win32/kernelverbs.rc \
        tests \
        --implemented file,frontier
"""

import sys
import re
from typing import List, Set, Tuple
from pathlib import Path

# Import from parse_kernelverbs to reuse processor discovery
sys.path.insert(0, str(Path(__file__).parent))
from parse_kernelverbs import (
    parse_kernelverbs_rc,
    EFPProcessor,
    HEADLESS_REGISTERED
)


def validate_stub_generation_paths(input_path: str, output_dir: str) -> bool:
    """
    Validate that input RC file and output directory are valid for stub generation.

    Returns True if valid, False otherwise.
    Prints detailed error messages to stderr on validation failure.
    """
    input_file = Path(input_path)
    output_path = Path(output_dir)

    # Check if input file exists
    if not input_file.exists():
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        print(f"Expected: kernelverbs.rc file", file=sys.stderr)
        return False

    # Validate it's the expected filename
    if input_file.name != 'kernelverbs.rc':
        print(f"WARNING: Input file is not named 'kernelverbs.rc': {input_file.name}", file=sys.stderr)
        print(f"This may work but is unexpected.", file=sys.stderr)

    # Check that input is under a reasonable path structure
    try:
        parts = input_file.parts
        if 'Common' not in parts or 'resources' not in parts:
            print(f"WARNING: Input file not in expected Common/resources/ path", file=sys.stderr)
            print(f"  Path: {input_path}", file=sys.stderr)
            print(f"  Expected something like: Common/resources/Win32/kernelverbs.rc", file=sys.stderr)
    except:
        pass  # Path analysis failed, continue anyway

    # Ensure output directory exists or can be created
    if not output_path.exists():
        try:
            print(f"Creating output directory: {output_path}", file=sys.stderr)
            output_path.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            print(f"ERROR: Cannot create output directory: {output_path}", file=sys.stderr)
            print(f"  Reason: {e}", file=sys.stderr)
            return False

    # Check output path looks like tests directory
    if output_path.name != 'tests':
        print(f"WARNING: Output directory is not named 'tests': {output_path.name}", file=sys.stderr)
        print(f"  Stub files are typically generated to 'tests/' directory", file=sys.stderr)

    return True


def generate_processor_stub(processor: EFPProcessor, verb_names: List[str]) -> str:
    """
    Generate a complete C stub file for a processor.

    Args:
        processor: EFPProcessor object with name and verb count
        verb_names: List of verb names (should match verb_count length)

    Returns:
        String containing complete C source file
    """
    proc_name = processor.name
    verb_count = processor.verb_count

    # Ensure we have the right number of verbs
    if len(verb_names) < verb_count:
        # Pad with generic names if we don't have all verb names
        verb_names = verb_names + [f"verb{i}" for i in range(len(verb_names), verb_count)]

    lines = [
        f'/*',
        f' * headless_{proc_name}_verbs.c - {proc_name.capitalize()} processor verbs (GENERATED FILE)',
        f' *',
        f' * Auto-generated by tools/kernelverbs_parser/generate_processor_stubs.py',
        f' * DO NOT EDIT BY HAND - To regenerate, run: python3 generate_processor_stubs.py',
        f' *',
        f' * This is a stub implementation for Phase 1 testing.',
        f' * All verbs currently return false/"not implemented".',
        f' * See docs/verb_implementation_status.md for implementation roadmap.',
        f' */',
        f'',
        '#include "frontier.h"',
        '#include "standard.h"',
        '',
        '#include "memory.h"',
        '#include "strings.h"',
        '#include "lang.h"',
        '#include "langinternal.h"',
        '#include "tablestructure.h"',
        '',
        f'/* Token enum for all verbs in the {proc_name} processor */',
        'enum {',
    ]

    # Generate enum with all tokens
    for i in range(verb_count):
        prefix = f"{proc_name[0:3]}v"  # e.g., "strv" for string processor
        token_name = f"{prefix}_{verb_names[i]}"
        if i < verb_count - 1:
            lines.append(f"    {token_name} = {i},")
        else:
            lines.append(f"    {token_name} = {i}")

    lines.extend([
        '};',
        '',
        f'static boolean {proc_name}_valueproc(short token, hdltreenode hparam1,',
        '                                     tyvaluerecord *vreturned,',
        '                                     bigstring bserror) {',
        '    switch(token) {',
    ])

    # Generate switch cases for all verbs (all returning false for now)
    for i in range(verb_count):
        prefix = f"{proc_name[0:3]}v"
        token_name = f"{prefix}_{verb_names[i]}"
        lines.extend([
            f"        case {token_name}:",
            f"            /* Verb #{i}: {proc_name}.{verb_names[i]} - not yet implemented */",
            f"            if (bserror) copystring(BIGSTRING(\"\\pnot implemented\"), bserror);",
            f"            return false;",
        ])

    lines.extend([
        '        default:',
        '            return false;',
        '    }',
        '}',
        '',
        f'boolean {proc_name}initverbs(void) {{',
        '    hdlhashtable htable = nil;',
        '    bigstring bsname;',
        '',
        f'    copystring(BIGSTRING("\\p{proc_name}"), bsname);',
        '',
        f'    if (!newfunctionprocessor(bsname, &{proc_name}_valueproc, false, &htable))',
        '        return false;',
        '',
        '    pushhashtable(htable);',
        '',
        '    #define ADD_VERB(name, tok) do { \\',
        '        bigstring bs; \\',
        '        copystring(name, bs); \\',
        '        if (!langaddkeyword(bs, tok)) { \\',
        '            pophashtable(); \\',
        '            return false; \\',
        '        } \\',
        '    } while(0)',
        '',
    ])

    # Generate ADD_VERB calls for all verbs
    for i, verb_name in enumerate(verb_names[:verb_count]):
        lines.append(f'    ADD_VERB(BIGSTRING("\\p{verb_name}"), {prefix}_{verb_name});')

    lines.extend([
        '',
        '    #undef ADD_VERB',
        '',
        '    pophashtable();',
        '    return true;',
        '}',
        '',
    ])

    return '\n'.join(lines)


def extract_verb_names(rc_content: str, processor_name: str, verb_count: int) -> List[str]:
    """
    Extract actual verb names from RC file for a processor.

    Searches for the processor block in the RC file and extracts verb names
    from the string list following the processor definition. The RC file format is:
      "processor_name\0",
      true/false,                    // window required
      number,                        // verb count
      "verb1\0", "verb2\0", ...     // verb names

    Falls back to generic names if extraction fails.

    Args:
        rc_content: Raw RC file content
        processor_name: Name of processor to find verbs for
        verb_count: Expected number of verbs

    Returns:
        List of verb names (actual or generic fallback)
    """
    try:
        # Find the ACTUAL processor definition block
        # Must match: "processor_name\0", followed by true/false and a number
        # This prevents matching data type references that just have "name\0",
        # Allow for comments (//...) between elements
        processor_block_pattern = rf'"{processor_name}\\0"\s*,\s*(?://[^\n]*)?\s*(true|false)\s*,\s*(?://[^\n]*)?\s*(\d+)\s*,\s*(?://[^\n]*)?'
        processor_match = re.search(processor_block_pattern, rc_content, re.MULTILINE)

        if not processor_match:
            return [f"verb{i}" for i in range(verb_count)]

        # Verify the verb count matches what we expect
        found_verb_count = int(processor_match.group(2))
        if found_verb_count != verb_count:
            print(f"Warning: Expected {verb_count} verbs for {processor_name}, "
                  f"but RC file declares {found_verb_count}", file=sys.stderr)

        # Start collecting verbs from after the verb count
        verb_start_pos = processor_match.end()
        verb_content = rc_content[verb_start_pos:]

        # Extract verb names - quoted strings followed by \0
        # Stop at verb_count to avoid picking up the next processor
        verb_pattern = r'"([^"\\]+)\\0"'

        verbs = []
        seen_verbs = set()  # Track duplicates

        for match in re.finditer(verb_pattern, verb_content):
            verb_name = match.group(1)

            # Stop if we've collected enough verbs
            if len(verbs) >= verb_count:
                break

            # Detect and warn about duplicates
            if verb_name in seen_verbs:
                print(f"Warning: Duplicate verb '{verb_name}' in {processor_name} processor "
                      f"(index {len(verbs)}), renaming to '{verb_name}_{len(verbs)}'",
                      file=sys.stderr)
                # Append index to make it unique
                verb_name = f"{verb_name}_{len(verbs)}"

            seen_verbs.add(verb_name)
            verbs.append(verb_name)

        # If we got the expected number of verbs, return them
        if len(verbs) == verb_count:
            return verbs

        # If we got some but not all, pad with generic names
        if len(verbs) > 0:
            remaining = verb_count - len(verbs)
            verbs.extend([f"verb{len(verbs) + i}" for i in range(remaining)])
            return verbs

    except Exception as e:
        print(f"Error extracting verbs for {processor_name}: {e}", file=sys.stderr)

    # Fallback: return generic names
    return [f"verb{i}" for i in range(verb_count)]


def main() -> None:
    """Main entry point."""
    if len(sys.argv) < 3:
        print("Usage: generate_processor_stubs.py <input.rc> <output_dir> [--implemented proc1,proc2,...]",
              file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_dir = sys.argv[2]

    # Parse optional --implemented flag
    implemented = set(HEADLESS_REGISTERED)
    if len(sys.argv) > 3 and sys.argv[3] == '--implemented':
        implemented = set(sys.argv[4].split(','))

    # Validate paths before proceeding
    if not validate_stub_generation_paths(input_path, output_dir):
        print("\nValidation failed. Please check paths and try again.", file=sys.stderr)
        sys.exit(1)

    # Parse RC file
    print(f"Parsing {input_path}...", file=sys.stderr)
    processors, had_errors = parse_kernelverbs_rc(input_path)

    if not processors:
        print("Error: No EFP processors found in input file", file=sys.stderr)
        sys.exit(1)

    # Separate implemented vs unimplemented
    unimplemented = [p for p in processors if p.name not in implemented]

    print(f"Found {len(unimplemented)} unimplemented processors to generate", file=sys.stderr)

    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Read RC file for verb name extraction (optional)
    with open(input_path, 'r', encoding='utf-8', errors='replace') as f:
        rc_content = f.read()

    # Generate stub file for each unimplemented processor
    generated_count = 0
    for proc in unimplemented:
        # Extract verb names (fallback to generic if not found)
        verb_names = extract_verb_names(rc_content, proc.name, proc.verb_count)

        # Generate C code
        c_code = generate_processor_stub(proc, verb_names)

        # Write to file
        output_file = output_path / f"headless_{proc.name}_verbs.c"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(c_code)

        print(f"✓ Generated {output_file.name}", file=sys.stderr)
        generated_count += 1

    print(f"\nGenerated {generated_count} processor stub files", file=sys.stderr)
    print(f"Output directory: {output_path}", file=sys.stderr)


if __name__ == '__main__':
    main()
