#!/usr/bin/env python3
"""
parse_kernelverbs.py - Generate kernel_verbs_init.c from kernelverbs.rc

Parses the Windows resource file containing EFP (External Function Processor)
definitions and generates C initialization code that calls all verb processor
init functions.

Usage:
    python3 parse_kernelverbs.py <input.rc> <output.c>

Example:
    python3 parse_kernelverbs.py Common/resources/Win32/kernelverbs.rc generated/kernel_verbs_init.c
"""

import sys
import re
from typing import List, Dict
from pathlib import Path


class EFPProcessor:
    """Represents an External Function Processor from kernelverbs.rc"""

    def __init__(self, efp_id: str, name: str, window_required: bool, verb_count: int):
        self.efp_id = efp_id
        self.name = name
        self.window_required = window_required
        self.verb_count = verb_count
        self.init_func = f"{name}initverbs"

    def __repr__(self):
        return f"EFP({self.efp_id}, {self.name}, {self.verb_count} verbs)"


def parse_kernelverbs_rc(rc_path: str) -> List[EFPProcessor]:
    """
    Parse kernelverbs.rc and extract all EFP processor definitions.

    Returns a list of EFPProcessor objects, one for each processor.
    """
    with open(rc_path, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    processors = []

    # Find all EFP blocks
    # Pattern: <number> /*comment*/ EFP DISCARDABLE
    efp_pattern = r'(\d+)\s+/\*[^*]*\*/\s+EFP\s+DISCARDABLE'

    for match in re.finditer(efp_pattern, content):
        efp_id = match.group(1)
        block_start = match.end()

        # Find the BEGIN...END block
        begin_match = re.search(r'BEGIN', content[block_start:block_start + 100])
        if not begin_match:
            continue

        block_content_start = block_start + begin_match.end()

        # Find matching END
        end_match = re.search(r'\bEND\b', content[block_content_start:])
        if not end_match:
            continue

        block_content = content[block_content_start:block_content_start + end_match.start()]

        # Parse the block content
        # Format:
        #   N,                      // Number of "blocks" in this resource
        #       "processor1\0",      // Processor name
        #       true/false,         // Window required
        #           count,          // Verb count
        #           "verb1\0",
        #           ...
        #       "processor2\0",     // Another processor (if N > 1)
        #       ...

        # Some EFPs have multiple processors in one block
        # We need to find each processor name and its associated verb count

        # Split by processor name patterns to find all sub-blocks
        # Pattern: "name\0", followed by comma, then newline/tabs/spaces/comments, true/false, comma, newline/tabs/spaces/comments, then number
        # Example:
        #   "op\0",			//Function Processor Name
        #       true,			//Window required
        #           45,			//Count of verbs
        # Use (?:...) for non-capturing groups to skip comments
        # Pattern matches: name, then optionally whitespace/comment, then true/false, then optionally whitespace/comment, then number
        processor_pattern = r'"([^"]+)\\0"[^,]*,\s*(?://[^\n]*)?\s*(true|false)\s*,\s*(?://[^\n]*)?\s*(\d+)'

        for proc_match in re.finditer(processor_pattern, block_content):
            processor_name = proc_match.group(1)
            window_required = proc_match.group(2) == 'true'
            verb_count = int(proc_match.group(3))

            processor = EFPProcessor(efp_id, processor_name, window_required, verb_count)
            processors.append(processor)

    return processors


def generate_kernel_verbs_init_c(processors: List[EFPProcessor], rc_path: str) -> str:
    """
    Generate the C source code for kernel_verbs_init.c

    Args:
        processors: List of EFPProcessor objects
        rc_path: Path to the source kernelverbs.rc (for comments)

    Returns:
        String containing the complete C source file
    """
    lines = [
        "/* Auto-generated from kernelverbs.rc - DO NOT EDIT BY HAND */",
        f"/* Generated from: {rc_path} */",
        "/*",
        " * This file is automatically generated by tools/kernelverbs_parser/parse_kernelverbs.py",
        " * To regenerate, run: make in frontier-cli directory",
        " */",
        "",
        "#include \"frontier.h\"",
        "#include \"standard.h\"",
        "#include \"langinternal.h\"",
        "",
        "/* Forward declarations for verb processor initialization functions */",
    ]

    # Add forward declarations
    for proc in processors:
        lines.append(f"extern boolean {proc.init_func}(void);  /* EFP {proc.efp_id}: {proc.name} ({proc.verb_count} verbs) */")

    lines.extend([
        "",
        "/**",
        " * headless_init_kernel_verbs - Initialize all kernel verb processors",
        " *",
        " * This function calls the initialization function for each verb processor",
        " * defined in kernelverbs.rc. Each init function registers its verbs with",
        " * the UserTalk language runtime.",
        " *",
        f" * Total processors: {len(processors)}",
        f" * Total verbs: {sum(p.verb_count for p in processors)}",
        " *",
        " * Returns: true if all processors initialized successfully, false otherwise",
        " */",
        "boolean headless_init_kernel_verbs(void) {",
    ])

    # Add initialization calls for each processor
    for proc in processors:
        lines.extend([
            f"    /* Initialize {proc.name} processor (EFP {proc.efp_id}, {proc.verb_count} verbs) */",
            f"    if (!{proc.init_func}())",
            f"        return false;",
            ""
        ])

    lines.extend([
        "    return true;",
        "}",
        ""
    ])

    return "\n".join(lines)


def main():
    """Main entry point"""
    if len(sys.argv) != 3:
        print("Usage: parse_kernelverbs.py <input.rc> <output.c>")
        print()
        print("Example:")
        print("  python3 parse_kernelverbs.py Common/resources/Win32/kernelverbs.rc generated/kernel_verbs_init.c")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    # Validate input file exists
    if not Path(input_path).exists():
        print(f"Error: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    # Parse the RC file
    print(f"Parsing {input_path}...")
    processors = parse_kernelverbs_rc(input_path)

    if not processors:
        print("Warning: No EFP processors found in input file", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(processors)} verb processors:")
    for proc in processors:
        print(f"  - {proc.name:20s} (EFP {proc.efp_id:4s}, {proc.verb_count:3d} verbs)")

    # Generate the C code
    print(f"\nGenerating {output_path}...")
    c_code = generate_kernel_verbs_init_c(processors, input_path)

    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write output file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(c_code)

    print(f"✓ Generated {output_path}")
    print(f"  Total processors: {len(processors)}")
    print(f"  Total verbs: {sum(p.verb_count for p in processors)}")
    print()
    print("Next steps:")
    print("  1. Implement missing processor init functions in tests/headless_*_verbs.c")
    print("  2. Add source files to frontier-cli/Makefile HEADLESS_STUBS")
    print("  3. Rebuild: make clean && make")


if __name__ == '__main__':
    main()
