/*
 * Frontier CLI - NDJSON Protocol Handler
 *
 * protocol_handler.c - Structured JSON protocol loop for batch test execution
 *
 * Reads one JSON object per line from stdin, dispatches on "op" field,
 * writes one JSON response line to stdout. Designed for integration test
 * acceleration: one long-lived process per worker instead of per-test spawning.
 *
 * JSON parsing is intentional simple string scanning — incoming messages are
 * machine-generated by Python's json.dumps() with a fixed schema, so we don't
 * need a general-purpose JSON parser.
 *
 * Copyright (C) 1992-2004 UserLand Software, Inc.
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include "protocol_handler.h"
#include "cli_json_output.h"
#include "repl_variables.h"
#include "repl.h"

#include "../Common/headers/frontier.h"
#include "../Common/headers/lang.h"
#include "../Common/headers/langexternal.h"
#include "../Common/headers/memory.h"
#include "../Common/headers/logging.h"
#include "../Common/headers/langinternal.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>

#define PROTOCOL_LINE_MAX 65536

/* Protocol output stream. In protocol mode, we redirect the C library's stdout
 * to /dev/null (to suppress stray printf output from verb implementations) and
 * write protocol messages to this saved copy of the original stdout fd. */
static FILE *g_protocol_out = NULL;

/* ========================================================================
 * Minimal JSON field extraction
 *
 * These helpers extract string and integer values from a known-schema JSON
 * line. They are NOT general-purpose JSON parsers — they rely on the input
 * being machine-generated with predictable formatting.
 * ======================================================================== */

/*
 * Extract a JSON string value for a given key from a JSON line.
 * Handles JSON escape sequences in the value (\n, \t, \\, \", \uXXXX).
 * Returns a malloc'd C string (caller must free), or NULL if key not found.
 *
 * Looks for: "key":"value" or "key": "value"
 */
static char *json_extract_string(const char *json, const char *key) {
    /* Build search pattern: "key" */
    char pattern[128];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);

    const char *pos = strstr(json, pattern);
    if (pos == NULL) {
        return NULL;
    }

    /* Skip past "key" */
    pos += strlen(pattern);

    /* Skip optional whitespace and colon */
    while (*pos == ' ' || *pos == ':') {
        pos++;
    }

    /* Expect opening quote */
    if (*pos != '"') {
        return NULL;
    }
    pos++;  /* skip opening quote */

    /* Parse the JSON string value, handling escape sequences */
    size_t capacity = 256;
    size_t len = 0;
    char *result = malloc(capacity);
    if (result == NULL) {
        return NULL;
    }

    while (*pos != '\0' && *pos != '"') {
        char c;

        if (*pos == '\\') {
            pos++;
            switch (*pos) {
                case '"':  c = '"';  break;
                case '\\': c = '\\'; break;
                case '/':  c = '/';  break;
                case 'b':  c = '\b'; break;
                case 'f':  c = '\f'; break;
                case 'n':  c = '\n'; break;
                case 'r':  c = '\r'; break;
                case 't':  c = '\t'; break;
                case 'u': {
                    /* \uXXXX — decode 4 hex digits. Handles surrogate pairs
                     * (\uD800-\uDBFF followed by \uDC00-\uDFFF) for codepoints > U+FFFF.
                     * For BMP chars < 128, emit as ASCII. Others as UTF-8. */
                    if (pos[1] && pos[2] && pos[3] && pos[4]) {
                        char hex[5] = { pos[1], pos[2], pos[3], pos[4], '\0' };
                        unsigned int codepoint = (unsigned int)strtoul(hex, NULL, 16);
                        pos += 4;  /* skip the 4 hex digits */

                        /* Check for high surrogate (U+D800..U+DBFF) */
                        if (codepoint >= 0xD800 && codepoint <= 0xDBFF) {
                            /* Expect \uDCxx low surrogate */
                            if (pos[1] == '\\' && pos[2] == 'u') {
                                char hex2[5] = { pos[3], pos[4], pos[5], pos[6], '\0' };
                                unsigned int low = (unsigned int)strtoul(hex2, NULL, 16);
                                if (low >= 0xDC00 && low <= 0xDFFF) {
                                    codepoint = 0x10000 + ((codepoint - 0xD800) << 10) + (low - 0xDC00);
                                    pos += 6;  /* skip \uXXXX of low surrogate */
                                }
                            }
                        }

                        /* Encode codepoint as UTF-8 */
                        size_t need = (codepoint < 0x80) ? 1 : (codepoint < 0x800) ? 2 : (codepoint < 0x10000) ? 3 : 4;
                        if (len + need >= capacity) {
                            capacity = (capacity + need) * 2;
                            char *tmp = realloc(result, capacity);
                            if (tmp == NULL) { free(result); return NULL; }
                            result = tmp;
                        }
                        if (codepoint < 0x80) {
                            c = (char)codepoint;
                            /* fall through to append below */
                        } else if (codepoint < 0x800) {
                            result[len++] = (char)(0xC0 | (codepoint >> 6));
                            result[len++] = (char)(0x80 | (codepoint & 0x3F));
                            pos++;
                            continue;
                        } else if (codepoint < 0x10000) {
                            result[len++] = (char)(0xE0 | (codepoint >> 12));
                            result[len++] = (char)(0x80 | ((codepoint >> 6) & 0x3F));
                            result[len++] = (char)(0x80 | (codepoint & 0x3F));
                            pos++;
                            continue;
                        } else {
                            result[len++] = (char)(0xF0 | (codepoint >> 18));
                            result[len++] = (char)(0x80 | ((codepoint >> 12) & 0x3F));
                            result[len++] = (char)(0x80 | ((codepoint >> 6) & 0x3F));
                            result[len++] = (char)(0x80 | (codepoint & 0x3F));
                            pos++;
                            continue;
                        }
                    } else {
                        c = '?';  /* malformed \u escape */
                    }
                    break;
                }
                default:
                    c = *pos;  /* unknown escape, pass through */
                    break;
            }
        } else {
            c = *pos;
        }

        /* Append character */
        if (len + 1 >= capacity) {
            capacity *= 2;
            char *tmp = realloc(result, capacity);
            if (tmp == NULL) { free(result); return NULL; }
            result = tmp;
        }
        result[len++] = c;
        pos++;
    }

    result[len] = '\0';
    return result;
}

/*
 * Extract a JSON integer value for a given key.
 * Looks for: "key":123 or "key": 123
 * Returns the integer value, or -1 if not found.
 */
static long json_extract_int(const char *json, const char *key) {
    char pattern[128];
    snprintf(pattern, sizeof(pattern), "\"%s\"", key);

    const char *pos = strstr(json, pattern);
    if (pos == NULL) {
        return -1;
    }

    pos += strlen(pattern);

    /* Skip whitespace and colon */
    while (*pos == ' ' || *pos == ':') {
        pos++;
    }

    /* Parse integer */
    char *end;
    long val = strtol(pos, &end, 10);
    if (end == pos) {
        return -1;
    }

    return val;
}

/* ========================================================================
 * Value type name for JSON response
 * ======================================================================== */

static const char *valuetype_name(tyvaluetype t) {
    switch (t) {
        case novaluetype:       return "none";
        case charvaluetype:     return "char";
        case intvaluetype:      return "int";
        case longvaluetype:     return "long";
        case booleanvaluetype:  return "boolean";
        case stringvaluetype:   return "string";
        case doublevaluetype:   return "double";
        case datevaluetype:     return "date";
        case addressvaluetype:  return "address";
        case directionvaluetype:return "direction";
        case externalvaluetype: return "external";
        case listvaluetype:     return "list";
        case recordvaluetype:   return "record";
        case binaryvaluetype:   return "binary";
        default:                return "unknown";
    }
}

/* ========================================================================
 * Response writers — one JSON line per response
 * ======================================================================== */

/*
 * Write a success response with a value result.
 * The value is coerced to string for the "value" field.
 * Writes to stdout and flushes.
 */
static void write_eval_success(long id, tyvaluerecord *val) {
    const char *type_name = valuetype_name(val->valuetype);

    /* Coerce to string for the response value */
    tyvaluerecord coerced = *val;

    if (coerced.valuetype == novaluetype) {
        /* No return value — emit null */
        fprintf(g_protocol_out, "{\"id\":%ld,\"result\":{\"value\":null,\"type\":\"none\"},\"success\":true}\n", id);
        fflush(g_protocol_out);
        return;
    }

    /* Special handling for tables */
    if (coerced.valuetype == externalvaluetype) {
        hdlexternalvariable hv = (hdlexternalvariable)coerced.data.externalvalue;
        if (hv != nil && (**hv).id == idtableprocessor) {
            fprintf(g_protocol_out, "{\"id\":%ld,\"result\":{\"value\":\"[table]\",\"type\":\"table\"},\"success\":true}\n", id);
            fflush(g_protocol_out);
            return;
        }
    }

    if (!coercetostring(&coerced)) {
        fprintf(g_protocol_out, "{\"id\":%ld,\"result\":{\"value\":null,\"type\":\"%s\"},\"success\":true}\n", id, type_name);
        fflush(g_protocol_out);
        return;
    }

    /* Extract the string from the handle */
    Handle hstring = coerced.data.stringvalue;
    long len = gethandlesize(hstring);

    fprintf(g_protocol_out, "{\"id\":%ld,\"result\":{\"value\":", id);
    cli_json_write_escaped_buffer(g_protocol_out, (const char *)*hstring, len);
    fprintf(g_protocol_out, ",\"type\":\"%s\"},\"success\":true}\n", type_name);
    fflush(g_protocol_out);
}

/*
 * Write an error response.
 */
static void write_eval_error(long id, const char *error_msg) {
    fprintf(g_protocol_out, "{\"id\":%ld,\"error\":{\"message\":", id);
    cli_json_write_escaped_string(g_protocol_out, error_msg);
    fprintf(g_protocol_out, ",\"category\":\"script\"},\"success\":false}\n");
    fflush(g_protocol_out);
}

/*
 * Write a simple success acknowledgement (for clearContext, etc).
 */
static void write_ack(long id) {
    fprintf(g_protocol_out, "{\"id\":%ld,\"success\":true}\n", id);
    fflush(g_protocol_out);
}

/* ========================================================================
 * Operation handlers
 * ======================================================================== */

static void handle_script_eval(long id, const char *json_line) {
    /* Extract expression from params.expression.
     * The JSON looks like: {"op":"script/eval","id":1,"params":{"expression":"..."}}
     * json_extract_string will find the first "expression" key. */
    char *expression = json_extract_string(json_line, "expression");
    if (expression == NULL) {
        write_eval_error(id, "Missing 'expression' in params");
        return;
    }

    tyvaluerecord result;
    bigstring error_msg;

    initvalue(&result, novaluetype);
    setemptystring(error_msg);

    boolean ok = repl_eval_with_variables_value(expression, &result, error_msg);

    if (ok) {
        write_eval_success(id, &result);
    } else {
        /* Convert Pascal string error to C string */
        char c_error[256];
        long errlen = stringlength(error_msg);
        if (errlen > 0 && errlen < (long)sizeof(c_error)) {
            memcpy(c_error, stringbaseaddress(error_msg), errlen);
            c_error[errlen] = '\0';
        } else if (errlen == 0) {
            snprintf(c_error, sizeof(c_error), "Script evaluation failed");
        } else {
            snprintf(c_error, sizeof(c_error), "Script error (message too long)");
        }
        write_eval_error(id, c_error);
    }

    /* Clean up the result value if it was coerced/allocated */
    if (result.valuetype == stringvaluetype && result.data.stringvalue != nil) {
        disposehandle(result.data.stringvalue);
    }

    free(expression);
}

static void handle_clear_context(long id) {
    /* Clear REPL variables table */
    hdlhashtable vars = repl_get_variables_table();
    if (vars != nil) {
        emptyhashtable(vars, true);
    }

    /* Reset focus to root */
    repl_jump_path("");

    /* Reset error state — prevents stale langerrordisable from
       affecting subsequent evaluations in protocol mode */
    langerrordisable = 0;
    langerrorlogdisable = 0;
    fllangerror = false;

    write_ack(id);
}

/* ========================================================================
 * Main protocol loop
 * ======================================================================== */

int protocol_main(cli_options_t *options) {
    (void)options;

    char *line_buf = malloc(PROTOCOL_LINE_MAX);
    if (line_buf == NULL) {
        fprintf(stderr, "protocol: failed to allocate line buffer\n");
        return 1;
    }

    /* Save the real stdout as our protocol output channel, then redirect
     * the C library's stdout to /dev/null. This prevents stray printf output
     * from verb implementations (msg(), dialog prompts, etc.) from
     * contaminating the NDJSON protocol stream. */
    int saved_stdout_fd = dup(STDOUT_FILENO);
    if (saved_stdout_fd < 0) {
        fprintf(stderr, "protocol: failed to dup stdout\n");
        free(line_buf);
        return 1;
    }
    g_protocol_out = fdopen(saved_stdout_fd, "w");
    if (g_protocol_out == NULL) {
        fprintf(stderr, "protocol: failed to fdopen saved stdout\n");
        close(saved_stdout_fd);
        free(line_buf);
        return 1;
    }
    /* Line-buffer the protocol output */
    setvbuf(g_protocol_out, NULL, _IOLBF, 0);

    /* Redirect stdout to /dev/null */
    FILE *devnull = fopen("/dev/null", "w");
    if (devnull != NULL) {
        dup2(fileno(devnull), STDOUT_FILENO);
        fclose(devnull);
    }

    log_info(LOG_COMP_GENERAL, "Protocol mode: ready for NDJSON on stdin");

    while (fgets(line_buf, PROTOCOL_LINE_MAX, stdin) != NULL) {
        /* Strip trailing newline */
        size_t len = strlen(line_buf);
        while (len > 0 && (line_buf[len - 1] == '\n' || line_buf[len - 1] == '\r')) {
            line_buf[--len] = '\0';
        }

        /* Skip empty lines */
        if (len == 0) {
            continue;
        }

        /* Extract op and id */
        char *op = json_extract_string(line_buf, "op");
        long id = json_extract_int(line_buf, "id");

        if (op == NULL) {
            if (id >= 0) {
                write_eval_error(id, "Missing 'op' field");
            }
            /* else: silently skip malformed lines */
            continue;
        }

        /* Dispatch on operation */
        if (strcmp(op, "script/eval") == 0) {
            handle_script_eval(id, line_buf);
        } else if (strcmp(op, "script/clearContext") == 0) {
            handle_clear_context(id);
        } else if (strcmp(op, "shutdown") == 0) {
            write_ack(id);
            free(op);
            break;
        } else {
            if (id >= 0) {
                char err[256];
                snprintf(err, sizeof(err), "Unknown operation: %s", op);
                write_eval_error(id, err);
            }
        }

        free(op);
    }

    free(line_buf);

    if (g_protocol_out != NULL) {
        fclose(g_protocol_out);
        g_protocol_out = NULL;
    }

    log_info(LOG_COMP_GENERAL, "Protocol mode: shutting down");
    return 0;
}
