/*
 * Runtime stubs header for portable Frontier
 */

#ifndef RUNTIME_STUBS_H
#define RUNTIME_STUBS_H

// Forward declaration for types needed by the stubs
typedef struct { int dummy; } tyvaluerecord;

#include "standard_portable.h"

// Basic memory and handle functions
void *newclearhandle(long size);
void *newfilledhandle(long size);
void enlargehandle(void *handle, long newsize);
void disposehandle(void *handle);
long gethandlesize(void *handle);

// String functions
void *newheapstring(const char *str);
void *newtexthandle(const char *str);
void copystring(const char *src, char *dst);
void deletestring(void *str);

// Hash table functions
void *newhashtable(void);
void disposehashtable(void *table);
void chainhashtable(void *table);
void unchainhashtable(void *table);
void *currenthashtable(void);

// Basic operations
boolean pushhandle(void *handle);
boolean pushstring(const char *str);
boolean pushint(long value);

// Error handling
void langerror(short errorcode);
void langerrorclear(void);
int langerrorenabled(void);

// Additional stub functions for missing symbols
void *aliastofilespec(void *alias);
void *aliastostring(void *alias);
int alllower(const char *str);
void *bytestohexstring(const void *data, long length);
void cleartmpstack(void);
void *coercelistvalue(void *value);
void *coercetoalias(void *value);
void *coercetolist(void *value);
void *coercetoobjspec(void *value);
int comparehandles(void *h1, void *h2);
void copyctopstring(const char *src, char *dst);
void copyheapstring(const char *src, char *dst);
void countwords(const char *str);
void *currentprocess(void);
void dbpushreleasestack(void);
void *dbrefhandle(void *handle);
void dirtostring(const char *dir);
void disablelangerror(void);
void disposetmpvalue(void *value);
void dolongswap(void *data);
void doshortswap(void *data);
void *efptable(void);
void enablelangerror(void);
void equalhandles(void *h1, void *h2);
void equalidentifiers(const char *id1, const char *id2);
void equalstrings(const char *str1, const char *str2);
void equaltextidentifiers(const char *id1, const char *id2);
void *evaluateobjspec(void *spec);
void *evaluateosascript(const char *script);
void exemptfromtmpstack(void *value);
void fileendloop(void);
void fileinitloop(void);
void filenextloop(void);
void filespecaddvalue(void *spec, void *value);
void filespecsubtractvalue(void *spec, void *value);
void *filewindowtable(void);
void *findinparenttable(void *table, const char *key);
void fldisableyield(void);
void *flfindanyspecialsymbol(const char *name);
void fllangerror(const char *msg);
void *fllangexternalvalueprotect(void *value);
void *fllanghashassignprotect(void *value);
void *floattostring(double value);
void flstackoverflow(void);
void *gestalt(long selector);
long getoserror(void);
void *getstringlist(void);
void *getsystemerrorstring(long error);
void *getsystemtablescript(const char *name);
void grabthreadglobals(void);
void hashassign(void *table, const char *key, void *value);
void hashdelete(void *table, const char *key);
void *hashgetiteminfo(void *table, const char *key);
void *hashgettypestring(void *table, const char *key);
void *hashgetvaluestring(void *table, const char *key);
void hashinsert(void *table, const char *key, void *value);
void *hashinversesearch(void *table, void *value);
void *hashlookupnode(void *table, const char *key);
void *hashresolvevalue(void *table, const char *key);
void hashsetlocality(void *table, const char *key);
int hashsymbolexists(void *table, const char *key);
void hashtableassign(void *table, const char *key, void *value);
void hashtabledelete(void *table, const char *key);
void *hashtablelookup(void *table, const char *key);
void *hashtablelookupnode(void *table, const char *key);
int hashtablesymbolexists(void *table, const char *key);
void *hexstringtonumber(const char *str);
void insertinhandle(void *handle, long offset, const void *data, long length);
void insertstring(const char *str, long offset, const char *insert);
int isallnumeric(const char *str);
int iscurrentapplication(void);
int isobjspectree(void *tree);
int isosascriptnode(void *node);
int keyboardstatus(void);
void lang2paramerror(short errorcode, const bigstring param1, const bigstring param2);
void langarrayreferror(const char *msg);
void *langassignnewtablevalue(void);
void langbackgroundtask(void);
void langbadexternaloperror(short errorcode, tyvaluerecord param);
void langcheckstacklimit(void);
void langcheckstackspace(void);
void *langcompilescript(void *script);
void langdebuggercall(void);
void *langdisposetree(void *tree);
void langendtrace(void);
void *langerrormessage(void);
void *langexternalbracketname(const char *name);
void *langexternalcopyvalue(void *value);
void langexternaldisposevalue(void *value);
void *langexternalgetfullpath(const char *path);
void *langexternalgetquotedpath(const char *path);
void *langexternalgettable(void *table);
void *langexternalgettype(void *value);
void *langexternalgettypeid(void *value);
void *langexternalpacktotext(void *value);
void *langexternaltypestring(void *value);
void *langexternalvaltocode(void *value);
void *langexternalvaltotable(void *value);
void *langfindsymbol(const char *name);
void *langgetlistitem(void *list, long index);
long langgetlistsize(void *list);
void *langgetstringlist(void);
void *langgetsymbolval(void *symbol);
void *langgetthisaddress(void);
void *langgettypeid(void *value);
void *langgettypestring(void *value);
long langgetvalsize(void *value);
void *langgetwithvaluename(void);
int langheapallocated(void *value);
void *langipccomplexmessage(void *message);
void *langipchandlercall(void *handler);
void *langipckernelfunction(void *function);
void *langipcmessage(void *message);
void *langipcself(void);
void *langipctablemessage(void *message);
int langisremotefunction(void *function);
void langlongparamerror(short errorcode, long param);
void langostypeparamerror(short errorcode, OSType param);
void *langpackvalue(void *value);
void *langpackverb(const char *verb);
void langparamerror(short errorcode, const bigstring param);
void langpoplocalchain(void);
void langpopsourcecode(void);
void langpushlocalchain(void);
void langpushsourcecode(void);
void *langremotefunctioncall(void *function);
void langsetsymboltableval(void *table, const char *key, void *value);
void langsetsymbolval(void *symbol, void *value);
void langsetthisvalue(void *value);
void *langsymbolchanged(void *symbol);
void *langtrace(void);
void *langunpackvalue(void *value);
void *langunpackverb(void *verb);
void languserescaped(void);
void *langvisitcodetree(void *tree);
void *listaddvalue(void *list, void *value);
void *listarrayvalue(void *list, long index);
void listassignvalue(void *list, long index, void *value);
int listcomparevalue(void *list1, void *list2);
void listdeletevalue(void *list, long index);
void *listsubtractvalue(void *list, void *value);
void *loadfromhandle(void *handle);
void *makelistvalue(void);
void *makerecordvalue(void);
void midinsertstring(char *str, long offset, const char *insert);
void *myMoof(void);
void *nameroottable(void);
void *newconstnode(void);
void *newidnode(void);
void *nthword(const char *str, long n);
void *numbertohexstring(long number);
void *numbertostring(long number);
void *objspectoaddress(void *spec);
void *objspectofilespec(void *spec);
void *objspectostring(void *spec);
void *opcopylist(void *list);
void opdisposelist(void *list);
void oppopoutline(void);
void oppushoutline(void);
void *ostypetostring(void *ostype);
void *outlinedata(void);
void *parsedialogstring(const char *str);
void parseerror(const char *msg);
void *parseparamstring(const char *str);
void *pathstable(void);
int patternmatch(const char *pattern, const char *str);
void *pophashtable(void);
void popleadingchars(const char *str);
void popprocess(void);
void *pullfromhandle(void *handle);
void *pushbinaryoperation(void *op);
void *pushchar(char ch);
void *pushfunctioncall(void *func);
void *pushfunctionreference(void *func);
void *pushkernelcall(void *call);
void *pushlastlink(void *link);
void *pushloop(void *loop);
void *pushloopbody(void *body);
void *pushoperation(void *op);
void *pushprocess(void *process);
void *pushquadruplet(void *quad);
void *pushtexthandle(void *handle);
void *pushtmpstackvalue(void *value);
void *pushtriplet(void *triplet);
void *pushtripletstatementlists(void *lists);
void *pushunaryoperation(void *op);
void *pushunarystatementlist(void *list);
void *pushvalueontmpstack(void *value);
void releaseheaptmp(void *value);
void releasethreadglobals(void);
void *roottable(void);
void *rootvariable(void);
void *searchhandle(void *handle, const void *data, long length);
void sethandlecontents(void *handle, const void *data, long length);
void setobjspecverb(void *spec, const char *verb);
void setparseparams(void *params);
void shellblockevents(void);
void *shellinternalerrormessage(void);
void shellpoperrorhook(void);
void shellpopevents(void);
void shellpusherrorhook(void);
void *shorttostring(short value);
void stringdeletechars(char *str, long start, long length);
void stringreplaceall(char *str, const char *find, const char *replace);
void *stringtodir(const char *str);
void *stringtofloat(const char *str);
void *stringtonumber(const char *str);
void *stringtoostype(const char *str);
void *stringtotime(const char *str);
void *subtractstrings(const char *str1, const char *str2);
void *timedatestring(void *time);
int timegreaterthan(void *time1, void *time2);
int timelessthan(void *time1, void *time2);
void *timenow(void);
void truenoop(void);
void *validdirection(void *dir);
int validhandle(void *handle);
void *zerostring(void);

#endif // RUNTIME_STUBS_H
