/*
 * menuverbs_headless.c - Menu processor verb dispatcher (headless build)
 *
 * Per ADR-016 the headless menu state lives in system.menus.data.<bar>.<menu>.
 * <item>. The mutating verbs route their effect through the write-side
 * projection helpers in Common/source/menudata_headless.c whenever the verb's
 * first-arg address points into the projection.
 *
 * This file is the canonical dispatcher for the menu processor in headless
 * mode. It is registered at startup by headless_init_kernel_verbs() (which
 * is generated by tools/kernelverbs_parser/parse_kernelverbs.py from
 * Common/resources/Win32/kernelverbs.rc). Issue #585 consolidated the
 * previous two-dispatcher arrangement (kernel-side menufunctionvalue + a
 * headless dispatcher under tests/) into this single canonical implementation.
 *
 * Verbs whose first arg points OUTSIDE system.menus.data still no-op-true
 * (preserves the prior behaviour for non-projection callers).
 *
 * GUI-only verbs that have no projection meaning remain no-ops:
 *   - menu.buildmenubar, clearmenubar, getScript, getCommandKey
 *   - menu.zoomScript (returns false; opens an editor window in GUI builds)
 */

#include "frontier.h"
#include "standard.h"

#ifdef FRONTIER_HEADLESS

#include "memory.h"
#include "strings.h"
#include "lang.h"
#include "langinternal.h"
#include "tablestructure.h"
#include "tableverbs.h"
#include "logging.h"
#include "menudata_headless.h"

/* Token enum for all verbs in the menu processor */
enum {
    menv_zoomscript = 0,
    menv_buildmenubar = 1,
    menv_clearmenubar = 2,
    menv_isinstalled = 3,
    menv_install = 4,
    menv_remove = 5,
    menv_getscript = 6,
    menv_setscript = 7,
    menv_addmenucommand = 8,
    menv_deletemenucommand = 9,
    menv_addsubmenu = 10,
    menv_deletesubmenu = 11,
    menv_getcommandkey = 12,
    menv_setcommandkey = 13,
    menv_list = 14,
    menv_describe = 15
};

static boolean menu_valueproc(short token, hdltreenode hparam1,
                                     tyvaluerecord *vreturned,
                                     bigstring bserror) {
    (void)bserror;

    switch(token) {
        case menv_zoomscript:
            /*
             * menu.zoomScript opens a script-editor window — purely GUI by
             * design. In headless we mirror the file-header contract for
             * other GUI-only menu verbs: report success at the verb-dispatch
             * level (return true) but set the script-visible result to
             * false (no editor window opened). This avoids surfacing
             * "not implemented" through bserror, which UserTalk treats as
             * a script error rather than a no-op.
             */
            (void)hparam1;
            return setbooleanvalue(false, vreturned);

        case menv_buildmenubar:
            /* menu.buildmenubar - no-op in headless mode (no GUI menubar) */
            return setbooleanvalue(true, vreturned);

        case menv_clearmenubar:
            /* menu.clearMenuBar - no-op in headless mode */
            return setbooleanvalue(true, vreturned);

        case menv_isinstalled: {
            /*
             * menu.isInstalled(@bar) — read system.menus.data.<bar>.installed
             * via the projection. Addresses outside system.menus.data report
             * false (no projection => not installed).
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenu, bsitem;
            short depth;
            boolean fl = false;

            flnextparamislast = true;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenu, bsitem);

            if (depth >= 1) {
                if (!menudata_get_installed(bsbar, &fl))
                    return false;
            }

            return setbooleanvalue(fl, vreturned);
        }

        case menv_install: {
            /*
             * menu.install(@bar) — set system.menus.data.<bar>.installed=true.
             * Addresses outside system.menus.data are no-op-true (preserves
             * prior behaviour for non-projection callers; Mac legacy path
             * tested elsewhere).
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenu, bsitem;
            short depth;

            flnextparamislast = true;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenu, bsitem);

            if (depth >= 1) {
                if (!menudata_set_installed(bsbar, true))
                    return false;
            }

            return setbooleanvalue(true, vreturned);
        }

        case menv_remove: {
            /* menu.remove(@bar) — set installed=false in projection. */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenu, bsitem;
            short depth;

            flnextparamislast = true;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenu, bsitem);

            if (depth >= 1) {
                if (!menudata_set_installed(bsbar, false))
                    return false;
            }

            return setbooleanvalue(true, vreturned);
        }

        case menv_getscript:
            /* menu.getScript - return empty string in headless mode */
            return setstringvalue(BIGSTRING("\p"), vreturned);

        case menv_setscript: {
            /*
             * Headless overload: menu.setScript(@leaf, "scripttext").
             * The address points at the leaf sub-table directly (depth 3 in
             * the projection). Updates the leaf's .script field. Leaf must
             * already exist — set_script returns false otherwise (matching
             * "setScript is for updates, not creation" contract).
             *
             * Script body extraction: getexempttextvalue gives us the full
             * heap-string Handle (any length), not a 255-byte bigstring.
             * Real menu scripts trivially exceed 255 bytes, so the bigstring
             * path would silently truncate the source — see PR review of
             * #580. Caller owns the resulting handle and must dispose it.
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenu, bsitem;
            short depth;
            Handle hscript = nil;
            boolean ok;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            flnextparamislast = true;

            if (!getexempttextvalue(hparam1, 2, &hscript))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenu, bsitem);

            if (depth < 3) {
                disposehandle(hscript);
                return setbooleanvalue(true, vreturned); /* not a leaf */
            }

            ok = menudata_set_script(bsbar, bsmenu, bsitem, hscript);
            disposehandle(hscript);

            if (!ok)
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case menv_addmenucommand: {
            /*
             * menu.addMenuCommand(@bar, "menuname", "itemname", "scripttext").
             * Lazy-creates @bar.<menuname>.<itemname> with label/script/
             * enabled fields per ADR-016.
             *
             * Script body extraction: getexempttextvalue retrieves the full
             * heap-string Handle for the script param (no 255-byte bigstring
             * truncation). Caller owns the returned handle.
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenudummy, bsitemdummy;
            short depth;
            bigstring bsmenu;
            bigstring bsitem;
            Handle hscript = nil;
            boolean ok;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            if (!getstringvalue(hparam1, 2, bsmenu))
                return false;
            if (!getstringvalue(hparam1, 3, bsitem))
                return false;

            flnextparamislast = true;

            if (!getexempttextvalue(hparam1, 4, &hscript))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenudummy, bsitemdummy);

            if (depth < 1) {
                disposehandle(hscript);
                return setbooleanvalue(true, vreturned); /* not in projection */
            }

            ok = menudata_add_command(bsbar, bsmenu, bsitem, hscript);
            disposehandle(hscript);

            if (!ok)
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case menv_deletemenucommand: {
            /*
             * menu.deleteMenuCommand(@bar, "menuname", "itemname"). Removes
             * the leaf at @bar.<menuname>.<itemname>. Idempotent on absent
             * targets per menudata_delete_item contract.
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenudummy, bsitemdummy;
            short depth;
            bigstring bsmenu;
            bigstring bsitem;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            if (!getstringvalue(hparam1, 2, bsmenu))
                return false;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 3, bsitem))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenudummy, bsitemdummy);

            if (depth < 1)
                return setbooleanvalue(true, vreturned); /* not in projection */

            if (!menudata_delete_item(bsbar, bsmenu, bsitem))
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case menv_addsubmenu: {
            /*
             * menu.addSubMenu(@bar, "menuname", "itemname"). Creates an
             * empty intermediate sub-table at @bar.<menuname>.<itemname>
             * for downstream addCommand/addSubMenu calls to populate.
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenudummy, bsitemdummy;
            short depth;
            bigstring bsmenu;
            bigstring bsitem;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            if (!getstringvalue(hparam1, 2, bsmenu))
                return false;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 3, bsitem))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenudummy, bsitemdummy);

            if (depth < 1)
                return setbooleanvalue(true, vreturned); /* not in projection */

            if (!menudata_add_submenu(bsbar, bsmenu, bsitem))
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case menv_deletesubmenu: {
            /*
             * menu.deleteSubMenu(@bar, "menuname"). Removes an entire
             * <menuname> subtree. The third (item) arg is omitted per the
             * legacy verb shape — pass-through to menudata_delete_item with
             * empty itemname triggers menu-level deletion.
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenudummy, bsitemdummy;
            short depth;
            bigstring bsmenu;
            bigstring bsempty;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            flnextparamislast = true;

            if (!getstringvalue(hparam1, 2, bsmenu))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenudummy, bsitemdummy);

            if (depth < 1)
                return setbooleanvalue(true, vreturned); /* not in projection */

            setemptystring(bsempty);
            if (!menudata_delete_item(bsbar, bsmenu, bsempty))
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case menv_getcommandkey:
            /* menu.getCommandKey - return empty char in headless mode */
            return setcharvalue('\0', vreturned);

        case menv_setcommandkey: {
            /*
             * Headless overload: menu.setCommandKey(@leaf, 'X'). Updates the
             * leaf's .cmdkey field. Leaf must already exist (set_cmdkey
             * returns false otherwise — same "for updates, not creation"
             * contract as set_script).
             */
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsbar, bsmenu, bsitem;
            short depth;
            char ch;

            if (!getvarparam(hparam1, 1, &hparent, bsname))
                return false;

            flnextparamislast = true;

            if (!getcharvalue(hparam1, 2, &ch))
                return false;

            depth = menudata_resolve_bar_path(hparent, bsname,
                                              bsbar, bsmenu, bsitem);

            if (depth < 3)
                return setbooleanvalue(true, vreturned); /* not a leaf */

            if (!menudata_set_cmdkey(bsbar, bsmenu, bsitem, ch, 0))
                return false;

            return setbooleanvalue(true, vreturned);
        }

        case menv_list: {
            /*
             * menu.list(adrApp = nil) -> list of @system.menus.data.<app>.
             *     <menu>.<item> leaf addresses.
             *
             * If adrApp is nil/omitted, walk the entire system.menus.data
             * subtree. If non-nil, scope to the given app (or any sub-table
             * the caller chose to point at).
             *
             * Per ADR-016 the verb semantics are documented for the read-side
             * first-switch contract; the actual list/describe walks live in
             * Common/source/menudata_headless.c so callers can reuse them
             * without going through the verb dispatcher.
             *
             * IMPORTANT: must NOT use getoptionaltableparam — that helper
             * calls langassignnewtablevalue which CREATES a fresh empty
             * table at the address, blowing away the caller's data. We
             * resolve the address by hand: getoptionaladdressparam to extract
             * (parent, name), then findnamedtable for read-only access.
             */
            short ctconsumed = 0, ctpositional = 0;
            hdlhashtable hparent = nil;
            bigstring bsname;
            bigstring bsadrApp;
            hdlhashtable hscope = nil;

            flnextparamislast = true;

            copystring(BIGSTRING("\x06" "adrApp"), bsadrApp);
            setemptystring(bsname);

            if (!getoptionaladdressparam(hparam1, &ctconsumed, &ctpositional,
                                         bsadrApp, &hparent, bsname))
                return false;

            if (hparent != nil && !isemptystring(bsname)) {
                if (!findnamedtable(hparent, bsname, &hscope))
                    return false;
            }

            return menudata_list_leaves(hscope, vreturned);
        }

        case menv_describe: {
            /*
             * menu.describe(adrItem) -> 9-field record with documented
             * defaults for absent fields. adrItem must point at a leaf
             * sub-table (deepest rung of the system.menus.data chain).
             */
            hdlhashtable hcontainer;
            bigstring bsname;
            hdlhashtable hleaf = nil;

            flnextparamislast = true;

            if (!getvarparam(hparam1, 1, &hcontainer, bsname))
                return false;

            if (!findnamedtable(hcontainer, bsname, &hleaf))
                return false;

            return menudata_describe_leaf(hleaf, vreturned);
        }

        default:
            return false;
    }
}

boolean menuinitverbs(void) {
    hdlhashtable htable = nil;
    bigstring bsname;

    copystring(PSTRING("\004", "menu"), bsname);

    if (!newfunctionprocessor(bsname, &menu_valueproc, false, &htable))
        return false;

    pushhashtable(htable);

    #define ADD_VERB(name, tok) do { \
        bigstring bs; \
        copystring(name, bs); \
        if (!langaddkeyword(bs, tok)) { \
            pophashtable(); \
            return false; \
        } \
    } while(0)

    ADD_VERB(PSTRING("\012", "zoomscript"), menv_zoomscript);
    ADD_VERB(PSTRING("\014", "buildmenubar"), menv_buildmenubar);
    ADD_VERB(PSTRING("\014", "clearmenubar"), menv_clearmenubar);
    ADD_VERB(PSTRING("\013", "isinstalled"), menv_isinstalled);
    ADD_VERB(PSTRING("\007", "install"), menv_install);
    ADD_VERB(PSTRING("\006", "remove"), menv_remove);
    ADD_VERB(PSTRING("\011", "getscript"), menv_getscript);
    ADD_VERB(PSTRING("\011", "setscript"), menv_setscript);
    ADD_VERB(PSTRING("\016", "addmenucommand"), menv_addmenucommand);
    ADD_VERB(PSTRING("\021", "deletemenucommand"), menv_deletemenucommand);
    ADD_VERB(PSTRING("\012", "addsubmenu"), menv_addsubmenu);
    ADD_VERB(PSTRING("\015", "deletesubmenu"), menv_deletesubmenu);
    ADD_VERB(PSTRING("\015", "getcommandkey"), menv_getcommandkey);
    ADD_VERB(PSTRING("\015", "setcommandkey"), menv_setcommandkey);
    ADD_VERB(PSTRING("\004", "list"), menv_list);
    ADD_VERB(PSTRING("\010", "describe"), menv_describe);

    #undef ADD_VERB

    pophashtable();
    return true;
}

#endif /* FRONTIER_HEADLESS */
